# -*- coding: utf-8 -*-
# Grup 11 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 11
DATA = {
 "discovery": ("dis-KA-vı-ri", "the act of finding something new", "The <b>discovery</b> of the cure saved many lives."),
 "traditional": ("trı-Dİ-şı-nıl", "following old customs", "They wore <b>traditional</b> clothes at the wedding."),
 "material": ("mı-Tİ-ri-ıl", "what something is made of; cloth", "Cotton is a soft <b>material</b>."),
 "case": ("KEYS", "a situation; a legal matter; a box", "In that <b>case</b>, we should leave early."),
 "used to": ("YUST-tu", "did regularly in the past", "I <b>used to</b> play tennis when I was young."),
 "accept": ("ık-SEPT", "to agree to take or receive", "She <b>accepted</b> the job offer."),
 "continent": ("KON-ti-nınt", "a very large area of land, like Asia", "Africa is a huge <b>continent</b>."),
 "according to": ("ı-KOR-ding-tu", "as said or shown by", "<b>According to</b> the news, it will snow."),
 "climate": ("KLAY-mıt", "the usual weather of a place", "Spain has a warm <b>climate</b>."),
 "carpet": ("KAR-pit", "a thick cover for a floor", "There is a red <b>carpet</b> in the hall."),
 "source": ("SORS", "where something comes from", "The sun is our main <b>source</b> of light."),
 "polite": ("pı-LAYT", "having good manners", "It is <b>polite</b> to say thank you."),
 "van": ("VEN", "a vehicle for carrying goods", "The delivery <b>van</b> stopped outside."),
 "silver": ("SİL-vır", "a shiny grey metal", "She wore a <b>silver</b> ring."),
 "blow": ("BLOU", "to push air out of your mouth; a hit", "<b>Blow</b> out the candles!"),
 "completely": ("kım-PLİİT-li", "totally; in every way", "I <b>completely</b> agree with you."),
 "neck": ("NEK", "the part joining your head and body", "She wore a scarf around her <b>neck</b>."),
 "ordinary": ("OR-dın-ri", "normal; not special", "It was an <b>ordinary</b> day at work."),
 "mind": ("MAYND", "the part of you that thinks; to object", "Would you <b>mind</b> closing the window?"),
 "protect": ("prı-TEKT", "to keep safe from harm", "A helmet <b>protects</b> your head."),
 "rather": ("RA-dır", "quite; more willingly", "I would <b>rather</b> stay at home tonight."),
 "quantity": ("KUON-tı-ti", "an amount or number", "Add a small <b>quantity</b> of salt."),
 "adventure": ("ıd-VEN-çır", "an exciting or risky experience", "The trip was a great <b>adventure</b>."),
 "steal": ("STİİL", "to take something that is not yours", "Someone tried to <b>steal</b> my bike."),
 "winner": ("Uİ-nır", "the person who wins", "She was the <b>winner</b> of the race."),
 "musical": ("MYU-zi-kıl", "related to music; a play with songs", "He comes from a <b>musical</b> family."),
 "position": ("pı-Zİ-şın", "the place where something is; a job", "Put the chair in that <b>position</b>."),
 "involve": ("in-VOLV", "to include as a necessary part", "The job <b>involves</b> a lot of travel."),
 "such": ("SAÇ", "of this kind; so much", "I've never seen <b>such</b> a big dog."),
 "tablet": ("TEB-lıt", "a small flat computer; a pill", "She reads books on her <b>tablet</b>."),
 "excellent": ("EK-sı-lınt", "extremely good", "Your English is <b>excellent</b>."),
 "all right": ("ol-RAYT", "good enough; okay", "Are you feeling <b>all right</b>?"),
 "behaviour": ("bi-HEY-vyır", "the way someone acts", "The teacher praised the children's <b>behaviour</b>."),
 "community": ("kı-MYU-nı-ti", "a group of people living in one area", "Our <b>community</b> has a new park."),
 "figure": ("Fİ-gır", "a number; a shape or body", "The sales <b>figures</b> went up this year."),
 "death": ("DET", "the end of life", "The film is about life and <b>death</b>."),
 "recently": ("RİİS-nt-li", "not long ago", "I <b>recently</b> moved to a new flat."),
 "towards": ("tı-UORDZ", "in the direction of", "She walked <b>towards</b> the door."),
 "fix": ("FİKS", "to repair; to make firm", "Can you <b>fix</b> my computer?"),
 "schedule": ("ŞED-yul", "a plan of times for things to happen", "The train <b>schedule</b> changed."),
 "enormous": ("i-NOR-mıs", "very large", "They live in an <b>enormous</b> house."),
 "feed": ("FİİD", "to give food to", "Don't forget to <b>feed</b> the cat."),
 "divorced": ("di-VORST", "no longer married", "Her parents are <b>divorced</b>."),
 "manage": ("ME-nic", "to control; to succeed in doing", "She <b>manages</b> a big team."),
 "nervous": ("NÖR-vıs", "worried or afraid", "I feel <b>nervous</b> before exams."),
 "lecture": ("LEK-çır", "a talk that teaches something", "The professor gave a <b>lecture</b> on history."),
 "couple": ("KA-pıl", "two people together; a few", "A young <b>couple</b> moved in next door."),
 "method": ("ME-tıd", "a way of doing something", "This is a good <b>method</b> for learning words."),
 "further": ("FÖR-dır", "at a greater distance; more", "For <b>further</b> information, call us."),
 "lead": ("LİİD", "to guide; to be first; a soft metal", "This road will <b>lead</b> you to the station."),
 "possession": ("pı-ZE-şın", "something you own; having something", "The old watch is her favourite <b>possession</b>."),
 "extremely": ("iks-TRİİM-li", "very; to a great degree", "It was <b>extremely</b> hot in the desert."),
 "smell": ("SMEL", "a scent; to notice a scent", "I love the <b>smell</b> of fresh bread."),
 "forward": ("FOR-uıd", "towards the front", "Take one step <b>forward</b>."),
 "pilot": ("PAY-lıt", "a person who flies a plane", "The <b>pilot</b> welcomed the passengers."),
 "fit": ("FİT", "the right size; healthy", "These shoes don't <b>fit</b> me."),
 "heart": ("HART", "the organ that pumps blood", "My <b>heart</b> beats fast when I run."),
 "direction": ("day-REK-şın", "the way something moves or points", "We walked in the wrong <b>direction</b>."),
 "push": ("PUŞ", "to press and move away", "<b>Push</b> the door to open it."),
 "care": ("KE-ır", "looking after; to feel concern", "She takes <b>care</b> of her little brother."),
 "reduce": ("ri-DUS", "to make smaller or less", "We must <b>reduce</b> waste."),
 "record": ("RE-kord", "stored information; to store sound", "Keep a <b>record</b> of your spending."),
 "sadly": ("SED-li", "unfortunately; in a sad way", "<b>Sadly</b>, the shop has closed."),
 "electric": ("i-LEK-trik", "using electricity", "They bought an <b>electric</b> car."),
 "ski": ("SKİİ", "to move on snow with long boards", "We learned to <b>ski</b> in the mountains."),
 "depend": ("di-PEND", "to be decided by; to rely on", "Our plans <b>depend</b> on the weather."),
 "device": ("di-VAYS", "a piece of equipment made for a job", "A phone is a useful <b>device</b>."),
 "media": ("Mİİ-di-ı", "TV, radio, newspapers and the internet", "The story was on all the <b>media</b>."),
 "any more": ("e-ni-MOR", "no longer", "I don't work there <b>any more</b>."),
 "error": ("E-rır", "a mistake", "There is an <b>error</b> in your calculation."),
 "pants": ("PENTS", "trousers; underwear", "He bought a new pair of <b>pants</b>."),
 "lorry": ("LO-ri", "a large vehicle for carrying goods", "The <b>lorry</b> was full of boxes."),
 "runner": ("RA-nır", "a person who runs", "The <b>runner</b> won the marathon."),
 "colleague": ("KO-liig", "a person you work with", "My <b>colleague</b> helped me finish the report."),
 "danger": ("DEYN-cır", "the chance of harm", "The sign warns of <b>danger</b> ahead."),
 "sheet": ("ŞİİT", "a large cloth for a bed; a page", "Put a clean <b>sheet</b> on the bed."),
 "church": ("ÇÖRÇ", "a building where Christians pray", "The old <b>church</b> is in the town centre."),
 "itself": ("it-SELF", "used for a thing already mentioned", "The cat cleaned <b>itself</b>."),
 "speech": ("SPİİÇ", "a formal talk; the ability to speak", "The president gave a short <b>speech</b>."),
 "disappear": ("di-sı-Pİ-ır", "to go out of sight", "The sun <b>disappeared</b> behind the clouds."),
 "golf": ("GOLF", "a game played with clubs and a small ball", "My uncle plays <b>golf</b> on Sundays."),
 "round": ("RAUND", "shaped like a circle; a stage of a game", "The Earth is <b>round</b>."),
 "produce": ("PRO-dus", "to make or grow something", "This factory <b>produces</b> cars."),
 "essay": ("E-sey", "a short piece of writing on a topic", "I wrote an <b>essay</b> about my city."),
 "pattern": ("PE-tın", "a repeated design; a regular way", "Her dress had a flower <b>pattern</b>."),
 "might": ("MAYT", "used to show something is possible", "It <b>might</b> rain later."),
 "fair": ("FE-ır", "treating people equally; an outdoor event", "It isn't <b>fair</b> to blame him."),
 "employer": ("im-PLO-yır", "a person or company that pays workers", "My <b>employer</b> gave me a day off."),
 "unhappy": ("an-HE-pi", "not happy; sad", "He was <b>unhappy</b> with his test result."),
 "incredible": ("in-KRE-dı-bıl", "very hard to believe; amazing", "The view from the top was <b>incredible</b>."),
 "least": ("LİİST", "the smallest amount", "This is the <b>least</b> expensive option."),
 "lovely": ("LAV-li", "very nice; beautiful", "What a <b>lovely</b> surprise!"),
 "coach": ("KOUÇ", "a sports trainer; a long-distance bus", "The <b>coach</b> taught the team new skills."),
 "extreme": ("iks-TRİİM", "very great; the most", "Be careful in <b>extreme</b> heat."),
 "against": ("ı-GENST", "opposed to; touching", "Our team played <b>against</b> theirs."),
 "scene": ("SİİN", "a part of a play or film; a place of an event", "My favourite <b>scene</b> is at the end."),
 "borrow": ("BO-rou", "to take and use something for a while", "Can I <b>borrow</b> your pen?"),
 "myself": ("may-SELF", "my own person", "I made this cake <b>myself</b>."),
 "stomach": ("STA-mık", "the part of the body that holds food", "My <b>stomach</b> hurts after eating too much."),
 "criminal": ("KRİ-mi-nıl", "a person who commits a crime", "The police caught the <b>criminal</b>."),
}
