# -*- coding: utf-8 -*-
# Grup 12 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 12
DATA = {
 "knock": ("NOK", "to hit a door to be let in", "Please <b>knock</b> before you enter."),
 "empty": ("EMP-ti", "having nothing inside", "The box was <b>empty</b>."),
 "kid": ("KİD", "a child (informal)", "The <b>kids</b> are playing outside."),
 "army": ("AR-mi", "a country's soldiers", "He joined the <b>army</b> at eighteen."),
 "rubbish": ("RA-biş", "waste; nonsense", "Please put the <b>rubbish</b> in the bin."),
 "storm": ("STORM", "very bad weather with wind and rain", "The <b>storm</b> broke several windows."),
 "possibility": ("po-sı-Bİ-lı-ti", "a thing that may happen", "There is a <b>possibility</b> of rain."),
 "tradition": ("trı-Dİ-şın", "a custom passed down over time", "It's a family <b>tradition</b> to eat together."),
 "attend": ("ı-TEND", "to be present at", "Will you <b>attend</b> the meeting?"),
 "choice": ("ÇOYS", "the act of choosing; an option", "You made the right <b>choice</b>."),
 "search": ("SÖRÇ", "an attempt to find; to look carefully", "The <b>search</b> for the lost dog lasted hours."),
 "independent": ("in-di-PEN-dınt", "not controlled by others; free", "She is very <b>independent</b>."),
 "feature": ("FİİÇ-ır", "an important part or quality", "The camera is the phone's best <b>feature</b>."),
 "audience": ("O-di-ıns", "the people watching or listening", "The <b>audience</b> clapped loudly."),
 "original": ("ı-Rİ-cı-nıl", "first; new and different", "This is the <b>original</b> painting."),
 "likely": ("LAYK-li", "probable; expected", "It is <b>likely</b> to snow tonight."),
 "basketball": ("BAS-kit-bol", "a game where you throw a ball through a hoop", "They play <b>basketball</b> after school."),
 "image": ("İ-mic", "a picture; how something appears", "The <b>image</b> on the screen was clear."),
 "queen": ("KUİİN", "a female ruler; a king's wife", "The <b>queen</b> visited the city."),
 "ancient": ("EYN-şınt", "very old; from long ago", "We saw <b>ancient</b> ruins in Greece."),
 "column": ("KO-lım", "a tall post; a narrow part of a page", "The roof rests on stone <b>columns</b>."),
 "organize": ("OR-gı-nayz", "to arrange or plan something", "She will <b>organize</b> the party."),
 "serve": ("SÖRV", "to give food; to help customers", "The waiter <b>served</b> our meal."),
 "cigarette": ("si-gı-RET", "a small roll of tobacco for smoking", "Smoking a <b>cigarette</b> is bad for you."),
 "asleep": ("ı-SLİİP", "sleeping", "The baby is <b>asleep</b>."),
 "focus": ("FOU-kıs", "to give attention to; the centre", "<b>Focus</b> on your work."),
 "typical": ("Tİ-pi-kıl", "usual; showing the normal features", "It was a <b>typical</b> winter day."),
 "purpose": ("PÖR-pıs", "the reason for doing something", "The <b>purpose</b> of the meeting was to plan the trip."),
 "frog": ("FROG", "a small jumping animal that lives near water", "A <b>frog</b> jumped into the pond."),
 "listener": ("Lİ-sı-nır", "a person who listens", "She is a good <b>listener</b>."),
 "regular": ("RE-gyu-lır", "happening at even times; usual", "He is a <b>regular</b> customer here."),
 "shut": ("ŞAT", "to close", "Please <b>shut</b> the door quietly."),
 "camp": ("KEMP", "a place to stay in tents", "We set up <b>camp</b> near the river."),
 "everyday": ("EV-ri-dey", "ordinary; happening each day", "These are <b>everyday</b> clothes."),
 "closed": ("KLOUZD", "not open", "The shop is <b>closed</b> on Sundays."),
 "anywhere": ("E-ni-ue-ır", "in or to any place", "You can sit <b>anywhere</b> you like."),
 "gas": ("GES", "a substance like air; fuel", "Turn off the <b>gas</b> after cooking."),
 "loud": ("LAUD", "making a lot of noise", "The music is too <b>loud</b>."),
 "ocean": ("OU-şın", "a very large sea", "The Pacific is the biggest <b>ocean</b>."),
 "metal": ("ME-tıl", "a hard material like iron or gold", "The gate is made of <b>metal</b>."),
 "working": ("UÖR-king", "in operation; having a job", "Is the lift <b>working</b> today?"),
 "bright": ("BRAYT", "full of light; clever", "The sun is very <b>bright</b> today."),
 "celebrity": ("sı-LEB-rı-ti", "a famous person", "A film <b>celebrity</b> visited our town."),
 "fork": ("FORK", "a tool with points for eating", "Use a <b>fork</b> to eat the salad."),
 "apply": ("ıp-LAY", "to ask for a job formally; to put on", "She will <b>apply</b> for the job."),
 "oil": ("OYL", "a thick liquid used for cooking or fuel", "Add some olive <b>oil</b> to the pan."),
 "identify": ("ay-DEN-ti-fay", "to say who or what something is", "Can you <b>identify</b> this bird?"),
 "rude": ("RUD", "not polite", "It's <b>rude</b> to interrupt people."),
 "engineer": ("en-ci-Nİ-ır", "a person who designs machines or buildings", "My sister is an <b>engineer</b>."),
 "burn": ("BÖRN", "to be on fire; to hurt with heat", "Be careful not to <b>burn</b> the toast."),
 "finger": ("FİN-gır", "one of the parts on your hand", "She cut her <b>finger</b> on the knife."),
 "poster": ("POUS-tır", "a large printed sheet for a wall", "There is a film <b>poster</b> on his door."),
 "corner": ("KOR-nır", "where two lines or streets meet", "The shop is on the <b>corner</b>."),
 "including": ("in-KLU-ding", "having as a part", "Everyone came, <b>including</b> the teacher."),
 "awful": ("O-fıl", "very bad", "The food tasted <b>awful</b>."),
 "hurt": ("HÖRT", "to cause pain; to feel pain", "I fell and <b>hurt</b> my knee."),
 "baseball": ("BEYS-bol", "an American game with a bat and ball", "They watched a <b>baseball</b> game."),
 "ah": ("A", "used to show a feeling", "<b>Ah</b>, now I understand!"),
 "stair": ("STE-ır", "one step in a set of steps", "Be careful on the top <b>stair</b>."),
 "item": ("AY-tım", "a single thing in a list", "The first <b>item</b> on the list is bread."),
 "affect": ("ı-FEKT", "to change or influence", "Cold weather can <b>affect</b> your mood."),
 "bit": ("BİT", "a small piece or amount", "I'm a little <b>bit</b> tired."),
 "perhaps": ("pır-HEPS", "maybe", "<b>Perhaps</b> we should wait a while."),
 "disagree": ("di-sı-GRİİ", "to have a different opinion", "I <b>disagree</b> with that idea."),
 "platform": ("PLET-form", "a raised area; where trains stop", "The train leaves from <b>platform</b> two."),
 "united": ("yu-NAY-tid", "joined together", "The two clubs are now <b>united</b>."),
 "sweet": ("SUİİT", "tasting like sugar; kind", "This tea is very <b>sweet</b>."),
 "driving": ("DRAY-ving", "controlling a car", "<b>Driving</b> at night can be tiring."),
 "herself": ("hır-SELF", "used for a female already mentioned", "She made the dress <b>herself</b>."),
 "president": ("PRE-zi-dınt", "the leader of a country or group", "The <b>president</b> gave a speech."),
 "fear": ("Fİ-ır", "the feeling of being afraid", "He has a <b>fear</b> of heights."),
 "square": ("SKUE-ır", "a shape with four equal sides; an open place in a town", "We met in the town <b>square</b>."),
 "peace": ("PİİS", "a time without war; calm", "Everyone wants <b>peace</b>."),
 "board": ("BORD", "a flat piece of wood; a group of managers", "The teacher wrote on the <b>board</b>."),
 "download": ("DAUN-loud", "to copy from the internet to a device", "<b>Download</b> the app to your phone."),
 "easily": ("İİ-zı-li", "without difficulty", "She passed the test <b>easily</b>."),
 "score": ("SKOR", "the points won; to win points", "The final <b>score</b> was two to one."),
 "view": ("VYU", "an opinion; what you can see", "The room has a lovely <b>view</b> of the sea."),
 "count": ("KAUNT", "to say numbers in order; to matter", "<b>Count</b> to ten slowly."),
 "fishing": ("Fİ-şing", "the activity of catching fish", "My father goes <b>fishing</b> at the weekend."),
 "narrow": ("NE-rou", "not wide", "The street is very <b>narrow</b>."),
 "copy": ("KO-pi", "something made to look the same", "Please make a <b>copy</b> of this page."),
 "society": ("sı-SA-yı-ti", "people living together; a club", "Education is important for <b>society</b>."),
 "lucky": ("LA-ki", "having good luck", "You are <b>lucky</b> to have such good friends."),
 "respond": ("ris-POND", "to answer or react", "She didn't <b>respond</b> to my email."),
 "symbol": ("SİM-bıl", "a sign that means something", "A heart is a <b>symbol</b> of love."),
 "traveller": ("TRE-vı-lır", "a person who travels", "The <b>traveller</b> visited many countries."),
 "wild": ("UAYLD", "living in nature; not tame", "We saw <b>wild</b> horses in the field."),
 "moon": ("MUN", "the round object that shines in the night sky", "The <b>moon</b> is bright tonight."),
 "clothing": ("KLOU-ding", "clothes in general", "Take warm <b>clothing</b> for the trip."),
 "expression": ("iks-PRE-şın", "a look on the face; a phrase", "She had a happy <b>expression</b>."),
 "fridge": ("FRİC", "a machine that keeps food cold", "Put the milk in the <b>fridge</b>."),
 "rest": ("REST", "a period of relaxing; the remaining part", "Let's take a short <b>rest</b>."),
 "exact": ("ig-ZEKT", "completely correct", "What is the <b>exact</b> time?"),
 "mail": ("MEYL", "letters and parcels; to send", "I received your <b>mail</b> this morning."),
 "hero": ("Hİ-rou", "a brave or admired person", "The firefighter was a real <b>hero</b>."),
 "marry": ("ME-ri", "to become husband and wife", "They will <b>marry</b> next spring."),
 "opportunity": ("o-pır-TYU-nı-ti", "a good chance to do something", "This job is a great <b>opportunity</b>."),
 "direct": ("day-REKT", "going straight; to guide", "Is there a <b>direct</b> train to Ankara?"),
 "middle": ("Mİ-dıl", "the centre; halfway", "He stood in the <b>middle</b> of the room."),
}
