# -*- coding: utf-8 -*-
# Grup 13 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 13
DATA = {
 "organization": ("or-gı-nay-ZEY-şın", "a group of people working together", "She works for a charity <b>organization</b>."),
 "teenage": ("TİİN-eyc", "aged between 13 and 19", "They have two <b>teenage</b> sons."),
 "weight": ("UEYT", "how heavy something is", "What is the <b>weight</b> of this bag?"),
 "physical": ("Fİ-zi-kıl", "relating to the body", "Football is good <b>physical</b> exercise."),
 "lake": ("LEYK", "a large area of water surrounded by land", "We swam in the <b>lake</b>."),
 "plate": ("PLEYT", "a flat dish for food", "She put the cake on a <b>plate</b>."),
 "lost": ("LOST", "unable to find your way; missing", "We got <b>lost</b> in the old city."),
 "brush": ("BRAŞ", "a tool with hairs for cleaning; to clean with it", "<b>Brush</b> your teeth twice a day."),
 "hold": ("HOULD", "to have in your hands; to keep", "Can you <b>hold</b> my bag for a minute?"),
 "scary": ("SKE-ri", "frightening", "That film was really <b>scary</b>."),
 "engine": ("EN-cin", "the part of a machine that makes it move", "The car's <b>engine</b> is very quiet."),
 "separate": ("SEP-rıt", "not joined; to divide", "The children sleep in <b>separate</b> rooms."),
 "digital": ("Dİ-ci-tıl", "using electronic technology", "I keep my photos in a <b>digital</b> album."),
 "top": ("TOP", "the highest part", "The cat sat on <b>top</b> of the wall."),
 "pain": ("PEYN", "an unpleasant feeling in the body", "I felt a sharp <b>pain</b> in my leg."),
 "thin": ("TİN", "not thick; not fat", "Cut the bread into <b>thin</b> slices."),
 "sky": ("SKAY", "the space above us where clouds are", "The <b>sky</b> is clear and blue."),
 "soft": ("SOFT", "not hard; gentle", "The pillow is very <b>soft</b>."),
 "hide": ("HAYD", "to put out of sight; to keep secret", "The children <b>hide</b> behind the tree."),
 "receive": ("ri-SİİV", "to get something given to you", "Did you <b>receive</b> my letter?"),
 "competition": ("kom-pı-Tİ-şın", "an event where people try to win", "She won first place in the <b>competition</b>."),
 "print": ("PRİNT", "to put words or pictures on paper", "I need to <b>print</b> this document."),
 "knife": ("NAYF", "a tool with a blade for cutting", "Use a <b>knife</b> to cut the meat."),
 "suggest": ("sı-CEST", "to offer an idea", "I <b>suggest</b> we leave early."),
 "suggestion": ("sı-CES-çın", "an idea you offer", "That's a good <b>suggestion</b>."),
 "track": ("TREK", "a mark left behind; a path; a song", "We followed the <b>track</b> through the forest."),
 "joke": ("COUK", "something said to make people laugh", "He told a funny <b>joke</b>."),
 "enter": ("EN-tır", "to go into", "Please <b>enter</b> the room quietly."),
 "employee": ("im-plo-Yİİ", "a person who works for a company", "The company has fifty <b>employees</b>."),
 "boss": ("BOS", "the person in charge at work", "My <b>boss</b> gave me a new task."),
 "remove": ("ri-MUV", "to take away", "Please <b>remove</b> your shoes at the door."),
 "crime": ("KRAYM", "an action against the law", "Stealing is a <b>crime</b>."),
 "system": ("SİS-tım", "a set of connected things or rules", "The school has a new computer <b>system</b>."),
 "petrol": ("PET-rıl", "fuel for cars", "We stopped to buy <b>petrol</b>."),
 "impossible": ("im-PO-sı-bıl", "not able to happen or be done", "It's <b>impossible</b> to finish in one day."),
 "bear (animal)": ("BE-ır", "a large wild animal with thick fur", "We saw a brown <b>bear</b> in the forest."),
 "crazy": ("KREY-zi", "wild or silly; mentally ill", "That's a <b>crazy</b> idea!"),
 "fortunately": ("FOR-çı-nıt-li", "luckily", "<b>Fortunately</b>, no one was hurt."),
 "race": ("REYS", "a competition of speed; a group of people", "He won the running <b>race</b>."),
 "guy": ("GAY", "a man (informal)", "That <b>guy</b> is my neighbour."),
 "suddenly": ("SA-dın-li", "quickly and without warning", "<b>Suddenly</b>, the lights went out."),
 "per cent": ("pır-SENT", "one part in a hundred", "Ninety <b>per cent</b> of students passed."),
 "speaker": ("SPİİ-kır", "a person who talks; a device for sound", "The <b>speaker</b> talked about health."),
 "sense": ("SENS", "a way of feeling (sight, smell...); meaning", "Dogs have a strong <b>sense</b> of smell."),
 "daily": ("DEY-li", "happening every day", "Reading is part of my <b>daily</b> routine."),
 "journalist": ("CÖR-nı-list", "a person who writes news", "The <b>journalist</b> asked many questions."),
 "classical": ("KLE-si-kıl", "traditional in style, especially music", "She enjoys <b>classical</b> music."),
 "manner": ("ME-nır", "the way something is done", "He spoke in a friendly <b>manner</b>."),
 "series": ("Sİ-riz", "a set of related things; a TV show", "I'm watching a new TV <b>series</b>."),
 "headache": ("HE-deyk", "a pain in your head", "I have a bad <b>headache</b>."),
 "personality": ("pör-sı-NE-lı-ti", "the qualities that make a person", "She has a cheerful <b>personality</b>."),
 "none": ("NAN", "not any", "<b>None</b> of the shops were open."),
 "develop": ("di-VE-lıp", "to grow or make better", "The company wants to <b>develop</b> new products."),
 "advantage": ("ıd-VAN-tic", "something that helps you", "Speaking English is a big <b>advantage</b>."),
 "stress": ("STRES", "a feeling of worry; emphasis", "Too much work causes <b>stress</b>."),
 "pack": ("PEK", "to put things in a bag; a packet", "I need to <b>pack</b> for my trip."),
 "expect": ("iks-PEKT", "to think something will happen", "We <b>expect</b> good weather tomorrow."),
 "temperature": ("TEMP-rı-çır", "how hot or cold something is", "The <b>temperature</b> dropped last night."),
 "factory": ("FEK-tı-ri", "a building where goods are made", "He works in a car <b>factory</b>."),
 "anyway": ("E-ni-uey", "used to change or continue a subject", "It was raining, but we went out <b>anyway</b>."),
 "predict": ("pri-DİKT", "to say what will happen", "No one can <b>predict</b> the future."),
 "factor": ("FEK-tır", "one thing that affects a result", "Price is an important <b>factor</b>."),
 "whose": ("HUZ", "belonging to which person", "<b>Whose</b> book is this?"),
 "quietly": ("KUA-yıt-li", "without noise", "She closed the door <b>quietly</b>."),
 "hole": ("HOUL", "an opening or empty space", "There is a <b>hole</b> in my sock."),
 "process": ("PROU-ses", "a series of steps", "Making bread is a slow <b>process</b>."),
 "disease": ("di-ZİİZ", "an illness", "The doctor treated a serious <b>disease</b>."),
 "option": ("OP-şın", "a choice", "You have two <b>options</b>: stay or go."),
 "wedding": ("UE-ding", "a marriage ceremony", "We danced all night at the <b>wedding</b>."),
 "curly": ("KÖR-li", "having curls; not straight", "She has <b>curly</b> brown hair."),
 "government": ("GA-vın-mınt", "the group that rules a country", "The <b>government</b> built a new hospital."),
 "ability": ("ı-Bİ-lı-ti", "the power or skill to do something", "He has the <b>ability</b> to learn quickly."),
 "power": ("PA-uır", "strength; control; energy", "The storm cut off the <b>power</b>."),
 "secondly": ("SE-kınd-li", "in the second place", "Firstly it's cheap, and <b>secondly</b> it's fast."),
 "sort": ("SORT", "a type; to arrange", "What <b>sort</b> of music do you like?"),
 "international": ("in-tır-NE-şı-nıl", "between countries", "She works for an <b>international</b> company."),
 "chemistry": ("KE-mist-ri", "the science of substances", "We did an experiment in <b>chemistry</b> class."),
 "worried": ("UA-rid", "feeling anxious", "I'm <b>worried</b> about the exam."),
 "explanation": ("eks-plı-NEY-şın", "a reason that makes something clear", "Please give an <b>explanation</b> for being late."),
 "tidy": ("TAY-di", "neat and in order", "Keep your desk <b>tidy</b>."),
 "active": ("EK-tiv", "busy and full of energy", "My grandmother is still very <b>active</b>."),
 "fashion": ("FE-şın", "the popular style of clothes", "She is interested in <b>fashion</b>."),
 "gap": ("GEP", "an empty space between things", "There is a <b>gap</b> in the fence."),
 "exactly": ("ig-ZEKT-li", "in a precise way", "Tell me <b>exactly</b> what happened."),
 "rate": ("REYT", "a level or speed; to judge", "The success <b>rate</b> is very high."),
 "anybody": ("E-ni-bo-di", "any person", "Is <b>anybody</b> home?"),
 "electricity": ("i-lek-TRİ-sı-ti", "energy that powers lights and machines", "The house had no <b>electricity</b> after the storm."),
 "guest": ("GEST", "a person you invite", "We have a <b>guest</b> staying this weekend."),
 "heat": ("HİİT", "warmth; to make warm", "The <b>heat</b> of the fire warmed the room."),
 "soap": ("SOUP", "what you use with water to wash", "Wash your hands with <b>soap</b>."),
 "painter": ("PEYN-tır", "an artist; a person who paints walls", "The <b>painter</b> sold his picture."),
 "along": ("ı-LONG", "from one end towards the other", "We walked <b>along</b> the beach."),
 "badly": ("BED-li", "in a poor way; seriously", "He did <b>badly</b> in the test."),
 "trouble": ("TRA-bıl", "a problem or difficulty", "The car gave us a lot of <b>trouble</b>."),
 "per": ("PÖR", "for each", "The room costs fifty liras <b>per</b> night."),
 "communicate": ("kı-MYU-ni-keyt", "to share information", "We <b>communicate</b> by email."),
 "strategy": ("STRE-tı-ci", "a plan to reach a goal", "The team needs a better <b>strategy</b>."),
 "wow": ("UAU", "used to show surprise or admiration", "<b>Wow</b>, that's amazing!"),
 "nowhere": ("NOU-ue-ır", "not in or to any place", "There was <b>nowhere</b> to sit."),
 "god": ("GOD", "a being that people worship", "Many people believe in <b>God</b>."),
}
