# -*- coding: utf-8 -*-
# Grup 14 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 14
DATA = {
 "react": ("ri-EKT", "to act because of something", "How did she <b>react</b> to the news?"),
 "field": ("FİİLD", "an area of open land; a subject area", "The cows are in the <b>field</b>."),
 "billion": ("BİL-yın", "the number 1,000,000,000", "The company is worth a <b>billion</b> dollars."),
 "wheel": ("UİİL", "a round part that turns on a vehicle", "A car has four <b>wheels</b>."),
 "clearly": ("KLİ-ır-li", "in a way that is easy to see or understand", "Please speak more <b>clearly</b>."),
 "actually": ("EK-çu-ı-li", "in fact; really", "<b>Actually</b>, I prefer tea."),
 "recognize": ("RE-kıg-nayz", "to know someone or something you have seen before", "I didn't <b>recognize</b> you with your new haircut."),
 "abroad": ("ıb-ROD", "in or to a foreign country", "They travelled <b>abroad</b> last summer."),
 "successful": ("sık-SES-fıl", "having a good result; doing well", "She is a <b>successful</b> writer."),
 "parking": ("PAR-king", "leaving a car in a place; a place for cars", "There is no <b>parking</b> on this street."),
 "oven": ("A-vın", "the part of a cooker for baking", "Put the bread in the <b>oven</b>."),
 "inside": ("İN-sayd", "in the inner part", "Let's stay <b>inside</b> because it's raining."),
 "knowledge": ("NO-lic", "the things a person knows", "He has a lot of <b>knowledge</b> about history."),
 "training": ("TREY-ning", "learning skills for a job or sport", "The new staff need some <b>training</b>."),
 "individual": ("in-di-Vİ-cu-ıl", "a single person; for one person", "Each <b>individual</b> has different needs."),
 "secretary": ("SEK-rıt-ri", "a person who does office work; a minister", "The <b>secretary</b> answered the phone."),
 "truck": ("TRAK", "a large vehicle for carrying goods", "The <b>truck</b> delivered the furniture."),
 "soldier": ("SOUL-cır", "a member of an army", "The <b>soldier</b> stood at the gate."),
 "noise": ("NOYZ", "a loud or unpleasant sound", "The <b>noise</b> from the street kept me awake."),
 "belt": ("BELT", "a band worn around the waist", "He wore a leather <b>belt</b>."),
 "shout": ("ŞAUT", "to say something very loudly", "Don't <b>shout</b>; I can hear you."),
 "creative": ("kri-EY-tiv", "good at making new things or ideas", "She has a <b>creative</b> mind."),
 "skin": ("SKİN", "the outer covering of the body", "Sun cream protects your <b>skin</b>."),
 "instrument": ("İN-strı-mınt", "a tool; a device for making music", "The violin is a beautiful <b>instrument</b>."),
 "thick": ("TİK", "wide; not thin", "He wore a <b>thick</b> winter coat."),
 "cooker": ("KU-kır", "a machine for cooking food", "The <b>cooker</b> has four rings."),
 "advertising": ("ED-vır-tay-zing", "making adverts to sell things", "She works in <b>advertising</b>."),
 "celebrate": ("SE-li-breyt", "to do something special for an event", "We <b>celebrate</b> New Year with fireworks."),
 "mathematics": ("me-tı-ME-tiks", "the study of numbers and shapes", "<b>Mathematics</b> is a difficult subject for me."),
 "architecture": ("AR-ki-tek-çır", "the design of buildings", "The city is famous for its old <b>architecture</b>."),
 "destroy": ("dis-TROY", "to damage completely", "The fire <b>destroyed</b> the building."),
 "charity": ("ÇE-rı-ti", "an organization that helps people", "They gave money to <b>charity</b>."),
 "degree": ("di-GRİİ", "a unit for temperature or angles; a university qualification", "It is thirty <b>degrees</b> today."),
 "task": ("TASK", "a piece of work to do", "Cleaning the house is a big <b>task</b>."),
 "usual": ("YU-jıl", "normal; happening most often", "I got up at my <b>usual</b> time."),
 "although": ("ol-DOU", "in spite of the fact that", "<b>Although</b> it was cold, we went out."),
 "discussion": ("dis-KA-şın", "a talk about a subject", "We had a long <b>discussion</b> about money."),
 "advertisement": ("ıd-VÖR-tis-mınt", "a notice that sells something", "I saw the job in an <b>advertisement</b>."),
 "cry": ("KRAY", "to shed tears; to shout", "The baby began to <b>cry</b>."),
 "save": ("SEYV", "to rescue; to keep for later; to store data", "Firefighters <b>saved</b> the family."),
 "size": ("SAYZ", "how big or small something is", "What <b>size</b> shoes do you wear?"),
 "surprise": ("sıp-RAYZ", "an unexpected event; to shock", "The party was a lovely <b>surprise</b>."),
 "succeed": ("sık-SİİD", "to do well; to come after", "If you work hard, you will <b>succeed</b>."),
 "drop": ("DROP", "to let fall; a small amount of liquid", "Be careful not to <b>drop</b> the plate."),
 "male": ("MEYL", "of the sex that does not give birth", "A <b>male</b> lion has a large mane."),
 "rock": ("ROK", "hard stone; a type of music", "The children climbed on the <b>rocks</b>."),
 "seat": ("SİİT", "something you sit on", "Please take your <b>seat</b>."),
 "effect": ("i-FEKT", "a change caused by something", "Music has a calming <b>effect</b> on me."),
 "coast": ("KOUST", "land next to the sea", "We drove along the <b>coast</b>."),
 "rise": ("RAYZ", "to go up; an increase", "Prices <b>rise</b> every year."),
 "lady": ("LEY-di", "a polite word for a woman", "An old <b>lady</b> asked me for help."),
 "reply": ("rip-LAY", "to answer", "She didn't <b>reply</b> to my message."),
 "patient": ("PEY-şınt", "a sick person; able to wait calmly", "The doctor saw ten <b>patients</b> today."),
 "salary": ("SE-lı-ri", "money paid for a job each month", "He earns a good <b>salary</b>."),
 "may": ("MEY", "used to show something is possible or allowed", "It <b>may</b> rain this afternoon."),
 "express": ("iks-PRES", "to show a feeling; fast", "It's hard to <b>express</b> my thanks."),
 "reporter": ("ri-POR-tır", "a person who reports news", "A <b>reporter</b> interviewed the mayor."),
 "instructor": ("in-STRAK-tır", "a person who teaches a skill", "The driving <b>instructor</b> was patient."),
 "worry": ("UA-ri", "to feel anxious", "Don't <b>worry</b>; everything will be fine."),
 "finally": ("FAY-nı-li", "at last; in the end", "We <b>finally</b> arrived home."),
 "definitely": ("DE-fi-nıt-li", "certainly; without doubt", "I will <b>definitely</b> come to your party."),
 "single": ("SİN-gıl", "only one; not married", "Not a <b>single</b> person came."),
 "environment": ("in-VAY-rın-mınt", "the natural world; your surroundings", "We must protect the <b>environment</b>."),
 "heavy": ("HE-vi", "weighing a lot", "This suitcase is too <b>heavy</b>."),
 "valley": ("VE-li", "low land between hills", "A river runs through the <b>valley</b>."),
 "circle": ("SÖR-kıl", "a round shape", "Draw a <b>circle</b> around the answer."),
 "simple": ("SİM-pıl", "easy; not complicated", "The instructions are very <b>simple</b>."),
 "beef": ("BİİF", "the meat of a cow", "We had roast <b>beef</b> for dinner."),
 "gift": ("GİFT", "a present", "She gave me a birthday <b>gift</b>."),
 "sign": ("SAYN", "a notice; to write your name", "The <b>sign</b> says the shop is closed."),
 "camping": ("KEM-ping", "staying outdoors in a tent", "We go <b>camping</b> in the mountains."),
 "raise": ("REYZ", "to lift up; to bring up children", "<b>Raise</b> your hand if you know the answer."),
 "blank": ("BLENK", "empty; with no writing", "Leave the last line <b>blank</b>."),
 "distance": ("DİS-tıns", "the space between two places", "What is the <b>distance</b> to the airport?"),
 "fail": ("FEYL", "to not succeed", "He was afraid he would <b>fail</b> the exam."),
 "except": ("ik-SEPT", "not including", "Everyone came <b>except</b> Ali."),
 "desert": ("DE-zırt", "a dry sandy area; to leave", "Camels live in the <b>desert</b>."),
 "lazy": ("LEY-zi", "not wanting to work", "Don't be <b>lazy</b>; get up and help."),
 "provide": ("prı-VAYD", "to give what is needed", "The hotel <b>provides</b> free breakfast."),
 "research": ("Rİİ-sörç", "careful study to find facts", "She is doing <b>research</b> on plants."),
 "employ": ("im-PLOY", "to give someone a job", "The factory <b>employs</b> 200 people."),
 "stupid": ("STU-pid", "not clever; silly", "It was a <b>stupid</b> mistake."),
 "following": ("FO-lou-ing", "coming next; below", "Answer the <b>following</b> questions."),
 "ship": ("ŞİP", "a large boat", "The <b>ship</b> sailed across the ocean."),
 "decision": ("di-Sİ-jın", "a choice you make", "It was a hard <b>decision</b> to make."),
 "businessman": ("BİZ-nıs-men", "a man who works in business", "The <b>businessman</b> flew to New York."),
 "smile": ("SMAYL", "a happy look with your mouth", "She gave me a warm <b>smile</b>."),
 "ring": ("RİNG", "a round band for the finger; to make a bell sound", "The phone began to <b>ring</b>."),
 "ending": ("EN-ding", "the last part of a story", "The film has a happy <b>ending</b>."),
 "penny": ("PE-ni", "a small coin", "The sweet cost one <b>penny</b>."),
 "variety": ("vı-RA-yı-ti", "many different kinds", "The shop sells a <b>variety</b> of fruit."),
 "pop": ("POP", "popular music; a sudden sound", "She loves <b>pop</b> music."),
 "state": ("STEYT", "a condition; a country or region; to say", "The country is in a bad <b>state</b>."),
 "unusual": ("an-YU-jıl", "not common; strange", "It's <b>unusual</b> to see snow here."),
 "character": ("KE-rık-tır", "a person in a story; someone's nature", "My favourite <b>character</b> is the hero."),
 "while": ("UAYL", "during the time that", "She sang <b>while</b> she cooked."),
 "promise": ("PRO-mis", "to say you will surely do something", "I <b>promise</b> to call you tomorrow."),
 "kill": ("KİL", "to make something die", "The frost <b>killed</b> the plants."),
 "planet": ("PLE-nit", "a large body in space, like Earth", "Mars is a red <b>planet</b>."),
 "trainer": ("TREY-nır", "a sports coach; a sports shoe", "The <b>trainer</b> helped the team improve."),
}
