# -*- coding: utf-8 -*-
# Grup 15 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 15
DATA = {
 "gold": ("GOULD", "a valuable yellow metal", "She wore a <b>gold</b> necklace."),
 "earth": ("ÖRT", "the planet we live on; soil", "The <b>Earth</b> goes around the sun."),
 "particular": ("pır-TİK-yu-lır", "a specific one; special", "Is there a <b>particular</b> book you want?"),
 "chat": ("ÇET", "to talk in a friendly way", "We <b>chat</b> on the phone every evening."),
 "introduction": ("int-rı-DAK-şın", "the first part; making people known", "The book has a short <b>introduction</b>."),
 "railway": ("REYL-uey", "the track and system for trains", "The <b>railway</b> connects the two cities."),
 "deal": ("DİİL", "an agreement; to handle", "We made a good <b>deal</b> on the car."),
 "discover": ("dis-KA-vır", "to find something for the first time", "Scientists <b>discovered</b> a new planet."),
 "almost": ("OL-moust", "nearly; not quite", "It's <b>almost</b> midnight."),
 "drug": ("DRAG", "a medicine; an illegal substance", "This <b>drug</b> reduces pain."),
 "invent": ("in-VENT", "to make something for the first time", "Who <b>invented</b> the telephone?"),
 "cover": ("KA-vır", "to put something over; a lid or top", "<b>Cover</b> the pot with a lid."),
 "twin": ("TUİN", "one of two children born together", "She has a <b>twin</b> sister."),
 "correctly": ("kı-REKT-li", "without mistakes", "Answer the questions <b>correctly</b>."),
 "consider": ("kın-Sİ-dır", "to think about carefully", "Please <b>consider</b> my offer."),
 "professor": ("prı-FE-sır", "a senior university teacher", "The <b>professor</b> teaches history."),
 "close": ("KLOUS", "near; to shut", "The station is <b>close</b> to my house."),
 "ideal": ("ay-Dİ-ıl", "the best possible; perfect", "This is an <b>ideal</b> place for a picnic."),
 "ring": ("RİNG", "a round band for the finger; to sound a bell", "He gave her a gold <b>ring</b>."),
 "social": ("SOU-şıl", "relating to people and society", "She has a busy <b>social</b> life."),
 "can": ("KEN", "to be able to; a metal container", "I bought a <b>can</b> of beans."),
 "furniture": ("FÖR-ni-çır", "tables, chairs and other large objects", "They bought new <b>furniture</b> for the flat."),
 "sock": ("SOK", "clothing for your foot", "I can't find my other <b>sock</b>."),
 "wide": ("UAYD", "measuring a lot from side to side", "The river is very <b>wide</b> here."),
 "themselves": ("dım-SELVZ", "used for people already mentioned", "The children made lunch <b>themselves</b>."),
 "washing": ("UO-şing", "clothes that need cleaning; cleaning", "I hung the <b>washing</b> outside."),
 "designer": ("di-ZAY-nır", "a person who creates the style of things", "She is a famous fashion <b>designer</b>."),
 "taste": ("TEYST", "the flavour of food; to try food", "This soup has a nice <b>taste</b>."),
 "tour": ("TUR", "a journey to see places", "We went on a <b>tour</b> of the castle."),
 "drama": ("DRA-mı", "a serious play or story", "She is studying <b>drama</b> at college."),
 "unit": ("YU-nit", "a single thing; an amount used to measure", "A metre is a <b>unit</b> of length."),
 "unfortunately": ("an-FOR-çı-nıt-li", "sadly; by bad luck", "<b>Unfortunately</b>, the train was late."),
 "invitation": ("in-vi-TEY-şın", "a request to come to an event", "I got an <b>invitation</b> to the wedding."),
 "airline": ("E-ır-layn", "a company that flies planes", "The <b>airline</b> lost my suitcase."),
 "site": ("SAYT", "a place where something is; a website", "This is a good <b>site</b> for a new school."),
 "pocket": ("PO-kit", "a small bag sewn into clothes", "He put the keys in his <b>pocket</b>."),
 "worst": ("UÖRST", "the least good; the most bad", "That was the <b>worst</b> film I've ever seen."),
 "brilliant": ("BRİL-yınt", "very clever; very good", "What a <b>brilliant</b> idea!"),
 "clear": ("KLİ-ır", "easy to see or understand; not blocked", "The water is so <b>clear</b> you can see the fish."),
 "himself": ("him-SELF", "used for a male already mentioned", "He cut <b>himself</b> while shaving."),
 "towel": ("TA-uıl", "a cloth for drying", "Dry your hands with the <b>towel</b>."),
 "speed": ("SPİİD", "how fast something moves", "The car went at high <b>speed</b>."),
 "voice": ("VOYS", "the sound you make when speaking", "She has a beautiful singing <b>voice</b>."),
 "yet": ("YET", "until now; still", "Have you finished <b>yet</b>?"),
 "learning": ("LÖR-ning", "gaining knowledge or skill", "<b>Learning</b> a language takes time."),
 "rock": ("ROK", "hard stone; a type of loud music", "We sat on a large <b>rock</b>."),
 "wet": ("UET", "covered with water; not dry", "My clothes are <b>wet</b> from the rain."),
 "comedy": ("KO-mı-di", "a funny play or film", "We watched a <b>comedy</b> last night."),
 "term": ("TÖRM", "a word for something; a part of a school year", "'Gravity' is a scientific <b>term</b>."),
 "shape": ("ŞEYP", "the outer form of something", "A ball has a round <b>shape</b>."),
 "condition": ("kın-Dİ-şın", "the state of something; a rule", "The car is in good <b>condition</b>."),
 "exist": ("ig-ZİST", "to be real; to live", "Dinosaurs no longer <b>exist</b>."),
 "suppose": ("sı-POUZ", "to think something is probably true", "I <b>suppose</b> you are right."),
 "laughter": ("LAF-tır", "the sound of laughing", "The room was full of <b>laughter</b>."),
 "broken": ("BROU-kın", "not working; in pieces", "The clock is <b>broken</b>."),
 "hit": ("HİT", "to strike; a great success", "Don't <b>hit</b> your brother."),
 "bean": ("BİİN", "a seed used as food", "I had rice and <b>beans</b> for lunch."),
 "human": ("HYU-mın", "relating to people; a person", "Every <b>human</b> needs food and water."),
 "thought": ("TOT", "an idea in your mind", "I had a sudden <b>thought</b>."),
 "ill": ("İL", "not well; sick", "She stayed home because she was <b>ill</b>."),
 "loudly": ("LAUD-li", "in a way that makes a lot of noise", "He knocked <b>loudly</b> on the door."),
 "law": ("LO", "a rule made by a government", "It is against the <b>law</b> to steal."),
 "flu": ("FLU", "an illness like a bad cold", "He caught the <b>flu</b> and stayed in bed."),
 "jump": ("CAMP", "to push yourself into the air", "The cat <b>jumped</b> onto the table."),
 "invite": ("in-VAYT", "to ask someone to come", "Let's <b>invite</b> our friends for dinner."),
 "control": ("kın-TROUL", "power over something; to manage", "The driver lost <b>control</b> of the car."),
 "prison": ("PRİ-zın", "a place where criminals are kept", "The thief was sent to <b>prison</b>."),
 "side": ("SAYD", "one of the surfaces or edges; a team", "Write on both <b>sides</b> of the paper."),
 "mobile": ("MOU-bayl", "able to move; a mobile phone", "I called her on my <b>mobile</b>."),
 "missing": ("Mİ-sing", "not there; lost", "One piece of the puzzle is <b>missing</b>."),
 "evidence": ("E-vi-dıns", "facts that show something is true", "There is no <b>evidence</b> of a crime."),
 "architect": ("AR-ki-tekt", "a person who designs buildings", "The <b>architect</b> drew the plans."),
 "crowd": ("KRAUD", "a large group of people", "A big <b>crowd</b> watched the match."),
 "plastic": ("PLES-tik", "a light man-made material", "The bottle is made of <b>plastic</b>."),
 "throw": ("TROU", "to send through the air with your hand", "<b>Throw</b> the ball to me."),
 "included": ("in-KLU-did", "being part of something", "Breakfast is <b>included</b> in the price."),
 "secret": ("SİİK-rıt", "something kept hidden", "Can you keep a <b>secret</b>?"),
 "nearly": ("Nİ-ır-li", "almost", "It's <b>nearly</b> time to go."),
 "bar": ("BAR", "a place that sells drinks; a long piece", "We met friends at a <b>bar</b>."),
 "safe": ("SEYF", "not in danger; a box for money", "Keep your passport in a <b>safe</b> place."),
 "pick": ("PİK", "to choose; to take a fruit or flower", "<b>Pick</b> a card, any card."),
 "ourselves": ("au-ır-SELVZ", "we, used again as the object", "We painted the room <b>ourselves</b>."),
 "height": ("HAYT", "how tall something is", "What is your <b>height</b>?"),
 "dentist": ("DEN-tist", "a doctor for teeth", "I have an appointment with the <b>dentist</b>."),
 "nature": ("NEY-çır", "the natural world; someone's character", "We enjoy walking in <b>nature</b>."),
 "argue": ("AR-gyu", "to disagree angrily; to give reasons", "They often <b>argue</b> about money."),
 "recent": ("Rİİ-sınt", "happening a short time ago", "In <b>recent</b> years, prices have risen."),
 "novel": ("NO-vıl", "a long written story", "She is reading a <b>novel</b> by a Turkish author."),
 "laptop": ("LEP-top", "a small computer you can carry", "I do my work on a <b>laptop</b>."),
 "role": ("ROUL", "a part in a play; a job or function", "She played the main <b>role</b> in the film."),
 "brain": ("BREYN", "the organ inside your head that thinks", "The human <b>brain</b> is amazing."),
 "virus": ("VAY-rıs", "a tiny thing that causes illness; a harmful computer program", "A <b>virus</b> made him ill."),
 "foreign": ("FO-rın", "from another country", "She speaks three <b>foreign</b> languages."),
 "jazz": ("CEZ", "a type of music with a strong beat", "He plays <b>jazz</b> on the piano."),
 "avoid": ("ı-VOYD", "to keep away from", "Try to <b>avoid</b> the busy roads."),
 "appearance": ("ı-Pİ-rıns", "the way someone looks; arriving", "She cares about her <b>appearance</b>."),
 "necessary": ("NE-sı-sı-ri", "needed; that must be done", "It is <b>necessary</b> to book in advance."),
 "notice": ("NOU-tis", "to see or become aware; a written sign", "Did you <b>notice</b> anything strange?"),
 "shoulder": ("ŞOUL-dır", "the part where your arm joins your body", "He carried the bag on his <b>shoulder</b>."),
 "benefit": ("BE-ni-fit", "an advantage or help", "Exercise has many <b>benefits</b>."),
}
