# -*- coding: utf-8 -*-
# Grup 16 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 16
DATA = {
 "wind": ("UİND", "moving air", "The strong <b>wind</b> blew my hat off."),
 "wood": ("UUD", "the hard material of trees", "The table is made of <b>wood</b>."),
 "average": ("E-vı-ric", "usual; the middle amount", "The <b>average</b> temperature in July is 30 degrees."),
 "fight": ("FAYT", "to struggle physically; a struggle", "The two boys had a <b>fight</b>."),
 "goal": ("GOUL", "an aim; a point in football", "My <b>goal</b> is to speak English well."),
 "target": ("TAR-git", "something you aim at or try to reach", "The company reached its sales <b>target</b>."),
 "onto": ("ON-tu", "to a position on", "The cat jumped <b>onto</b> the roof."),
 "beat": ("BİİT", "to defeat; to hit again and again", "Our team <b>beat</b> theirs three to one."),
 "monkey": ("MANG-ki", "an animal that climbs trees", "The <b>monkey</b> ate a banana."),
 "conference": ("KON-fı-rıns", "a large formal meeting", "She spoke at a science <b>conference</b>."),
 "hall": ("HOL", "a large room; a passage inside a house", "The concert was held in a big <b>hall</b>."),
 "helpful": ("HELP-fıl", "giving useful help", "The staff were very <b>helpful</b>."),
 "refuse": ("ri-FYUZ", "to say no to something", "He <b>refused</b> to answer the question."),
 "national": ("NE-şı-nıl", "relating to a whole country", "Football is our <b>national</b> sport."),
 "rest": ("REST", "a period of relaxing; the remaining part", "I'll do the <b>rest</b> of the work tomorrow."),
 "refer": ("ri-FÖR", "to mention; to send to another place", "The teacher <b>referred</b> to an old book."),
 "nut": ("NAT", "a hard-shelled fruit; a metal part", "She added <b>nuts</b> to the cake."),
 "perform": ("pır-FORM", "to do something for an audience; to carry out", "The band will <b>perform</b> tonight."),
 "cycle": ("SAY-kıl", "a set of events that repeat; to ride a bike", "The washing machine has a short <b>cycle</b>."),
 "bin": ("BİN", "a container for rubbish", "Throw it in the <b>bin</b>."),
 "connected": ("kı-NEK-tid", "joined or linked", "The two rooms are <b>connected</b> by a door."),
 "scared": ("SKE-ırd", "frightened", "The child was <b>scared</b> of the dark."),
 "crowded": ("KRAU-did", "full of people", "The bus was very <b>crowded</b>."),
 "differently": ("DİF-rınt-li", "in another way", "She sees things <b>differently</b> from me."),
 "expert": ("EKS-pört", "a person with special skill or knowledge", "He is an <b>expert</b> in computers."),
 "compete": ("kım-PİİT", "to try to win against others", "Ten teams will <b>compete</b> in the match."),
 "careful": ("KE-ır-fıl", "giving attention to avoid harm", "Be <b>careful</b> with that hot pan."),
 "energy": ("E-nır-ci", "the power to do work; strength", "Children have a lot of <b>energy</b>."),
 "complain": ("kım-PLEYN", "to say you are not happy about something", "He <b>complained</b> about the cold food."),
 "underground": ("an-dır-GRAUND", "below the ground; a city train system", "We took the <b>underground</b> to the centre."),
 "industry": ("İN-dıst-ri", "the making of goods; a business area", "The car <b>industry</b> is very large here."),
 "detective": ("di-TEK-tiv", "a person who solves crimes", "The <b>detective</b> found an important clue."),
 "several": ("SEV-rıl", "more than two but not many", "I called her <b>several</b> times."),
 "toy": ("TOY", "an object children play with", "The baby dropped its <b>toy</b>."),
 "survey": ("SÖR-vey", "a set of questions to collect opinions", "We did a <b>survey</b> about shopping habits."),
 "pollution": ("pı-LU-şın", "dirty air, water or land", "Cars cause a lot of <b>pollution</b>."),
 "biology": ("bay-O-lı-ci", "the study of living things", "We studied plants in <b>biology</b> class."),
 "credit": ("KRE-dit", "a way to buy now and pay later; praise", "She paid with a <b>credit</b> card."),
 "huge": ("HYUC", "extremely large", "They live in a <b>huge</b> house."),
 "earn": ("ÖRN", "to get money by working", "How much do you <b>earn</b> a month?"),
 "understanding": ("an-dır-STEN-ding", "the ability to know or feel something", "She showed great <b>understanding</b> of the problem."),
 "ground": ("GRAUND", "the surface of the earth", "The children sat on the <b>ground</b>."),
 "lend": ("LEND", "to give something for a short time", "Can you <b>lend</b> me ten liras?"),
 "biscuit": ("BİS-kit", "a small hard sweet cake", "She had a <b>biscuit</b> with her tea."),
 "prize": ("PRAYZ", "an award for winning", "She won first <b>prize</b> in the contest."),
 "transport": ("TRENS-port", "moving people or goods; a way of travelling", "Public <b>transport</b> is cheap here."),
 "route": ("RUT", "the way you take to get somewhere", "This is the fastest <b>route</b> to the airport."),
 "solution": ("sı-LU-şın", "an answer to a problem", "We found a simple <b>solution</b>."),
 "especially": ("is-PE-şı-li", "more than usual; particularly", "I love fruit, <b>especially</b> oranges."),
 "cartoon": ("kar-TUN", "a funny drawing or animated film", "Children love <b>cartoons</b>."),
 "mirror": ("Mİ-rır", "glass that shows your reflection", "She looked at herself in the <b>mirror</b>."),
 "bottom": ("BO-tım", "the lowest part", "The keys are at the <b>bottom</b> of the bag."),
 "invention": ("in-VEN-şın", "something made for the first time", "The wheel was a great <b>invention</b>."),
 "normally": ("NOR-mı-li", "usually", "I <b>normally</b> walk to work."),
 "thief": ("TİİF", "a person who steals", "The <b>thief</b> took her purse."),
 "cross": ("KROS", "to go across; an X shape", "Look both ways before you <b>cross</b> the road."),
 "tip": ("TİP", "extra money for service; a piece of advice; the end", "I gave the waiter a <b>tip</b>."),
 "allow": ("ı-LAU", "to let someone do something", "They don't <b>allow</b> dogs in the shop."),
 "smoking": ("SMOU-king", "breathing in cigarette smoke", "<b>Smoking</b> is not allowed here."),
 "web": ("UEB", "the internet; a spider's net", "I found the answer on the <b>web</b>."),
 "step": ("STEP", "a movement of the foot; a stair; a stage", "Take one <b>step</b> forward."),
 "manager": ("ME-ni-cır", "a person who controls a business or team", "The <b>manager</b> gave us a day off."),
 "skiing": ("SKİİ-ing", "the sport of moving on snow with skis", "We go <b>skiing</b> every winter."),
 "lock": ("LOK", "a device to keep something shut; to shut with a key", "Don't forget to <b>lock</b> the door."),
 "wave": ("UEYV", "a raised line of water; to move your hand", "A big <b>wave</b> hit the boat."),
 "war": ("UOR", "fighting between countries", "Many people suffer during a <b>war</b>."),
 "researcher": ("Rİİ-sör-çır", "a person who studies to find facts", "The <b>researcher</b> published her findings."),
 "gun": ("GAN", "a weapon that fires bullets", "The police officer carried a <b>gun</b>."),
 "birth": ("BÖRT", "the time when a baby is born", "The <b>birth</b> of her son made her happy."),
 "normal": ("NOR-mıl", "usual; ordinary", "It is <b>normal</b> to feel tired after work."),
 "alive": ("ı-LAYV", "living; not dead", "The old tree is still <b>alive</b>."),
 "mine": ("MAYN", "belonging to me; a place to dig coal", "That book is <b>mine</b>."),
 "argument": ("AR-gyu-mınt", "an angry talk; a reason", "They had an <b>argument</b> about money."),
 "less": ("LES", "a smaller amount", "Try to eat <b>less</b> sugar."),
 "belong": ("bi-LONG", "to be owned by; to be a member", "This bag <b>belongs</b> to me."),
 "yours": ("YORZ", "belonging to you", "Is this pen <b>yours</b>?"),
 "recommend": ("re-kı-MEND", "to say something is good", "Can you <b>recommend</b> a good restaurant?"),
 "physics": ("Fİ-ziks", "the science of energy and matter", "<b>Physics</b> explains how things move."),
 "electronic": ("i-lek-TRO-nik", "using computers or small electric parts", "We use <b>electronic</b> tickets now."),
 "pronounce": ("prı-NAUNS", "to say the sounds of a word", "How do you <b>pronounce</b> this word?"),
 "lab": ("LEB", "a room for science work", "The students did an experiment in the <b>lab</b>."),
 "clever": ("KLE-vır", "quick to learn; intelligent", "She is a <b>clever</b> student."),
 "cupboard": ("KA-bırd", "a piece of furniture with shelves and doors", "The cups are in the <b>cupboard</b>."),
 "surprised": ("sıp-RAYZD", "feeling shock at something unexpected", "I was <b>surprised</b> to see her."),
 "pet": ("PET", "an animal kept at home", "Their <b>pet</b> is a small dog."),
 "suit": ("SUT", "a jacket and trousers together; to be right for", "He wore a black <b>suit</b> to the wedding."),
 "chef": ("ŞEF", "a professional cook", "The <b>chef</b> made a delicious meal."),
 "hill": ("HİL", "a raised area of land, smaller than a mountain", "The house is on top of a <b>hill</b>."),
 "formal": ("FOR-mıl", "following strict rules; official", "Wear <b>formal</b> clothes to the meeting."),
 "experiment": ("iks-PE-ri-mınt", "a scientific test", "They did an <b>experiment</b> with water and salt."),
 "code": ("KOUD", "a system of signs; computer instructions", "Enter your secret <b>code</b>."),
 "document": ("DOK-yu-mınt", "an official paper or file", "Please sign this <b>document</b>."),
 "general": ("CEN-rıl", "relating to most things; not detailed", "In <b>general</b>, the weather is warm here."),
 "disaster": ("di-ZAS-tır", "a very bad event", "The flood was a terrible <b>disaster</b>."),
 "act": ("EKT", "to do something; to perform in a play", "We must <b>act</b> quickly."),
 "available": ("ı-VEY-lı-bıl", "able to be used or bought", "Tickets are <b>available</b> online."),
 "sale": ("SEYL", "the act of selling; a time of low prices", "The shoes are on <b>sale</b> this week."),
 "lemon": ("LE-mın", "a sour yellow fruit", "Add a slice of <b>lemon</b> to your tea."),
 "dry": ("DRAY", "not wet; to remove water", "Hang the clothes out to <b>dry</b>."),
 "arrangement": ("ı-REYNC-mınt", "a plan; the way things are placed", "We made an <b>arrangement</b> to meet at noon."),
}
