# -*- coding: utf-8 -*-
# Grup 17 (A2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 17
DATA = {
 "grass": ("GRAS", "the green plant that covers fields", "The children played on the <b>grass</b>."),
 "stage": ("STEYC", "a raised area for performers; a step in a process", "The singer walked onto the <b>stage</b>."),
 "professional": ("prı-FE-şı-nıl", "doing something as a paid job; skilled", "She is a <b>professional</b> photographer."),
 "passenger": ("PE-sin-cır", "a person travelling in a vehicle", "The bus had twenty <b>passengers</b>."),
 "running": ("RA-ning", "the activity of moving fast on foot; managing", "<b>Running</b> is good exercise."),
 "support": ("sı-PORT", "to help; help or agreement", "My family always <b>supports</b> me."),
 "strange": ("STREYNC", "unusual; not familiar", "I heard a <b>strange</b> noise last night."),
 "flying": ("FLA-ying", "travelling by air; moving through the air", "<b>Flying</b> is faster than driving."),
 "cause": ("KOZ", "to make happen; a reason", "Heavy rain can <b>cause</b> floods."),
 "mention": ("MEN-şın", "to say something briefly", "She didn't <b>mention</b> the price."),
 "increase": ("İNG-kriis", "to become larger; a rise", "Prices <b>increase</b> every year."),
 "certain": ("SÖR-tın", "sure; particular", "I'm <b>certain</b> I locked the door."),
 "population": ("pop-yu-LEY-şın", "the number of people in a place", "The city has a large <b>population</b>."),
 "tower": ("TA-uır", "a tall narrow building", "We climbed to the top of the <b>tower</b>."),
 "uniform": ("YU-ni-form", "special clothes for a job or school", "The students wear a blue <b>uniform</b>."),
 "major": ("MEY-cır", "very important; large", "This is a <b>major</b> problem."),
 "mostly": ("MOUST-li", "mainly; usually", "The guests were <b>mostly</b> family."),
 "screen": ("SKRİİN", "the flat part where images appear", "Don't sit too close to the <b>screen</b>."),
 "pass": ("PAS", "to go by; to succeed in a test", "Did you <b>pass</b> your exam?"),
 "matter": ("ME-tır", "a subject or problem; to be important", "That's a serious <b>matter</b>."),
 "specific": ("spı-Sİ-fik", "exact; particular", "Give me a <b>specific</b> example."),
 "motorcycle": ("MOU-tı-say-kıl", "a two-wheeled vehicle with an engine", "He rides a <b>motorcycle</b> to work."),
 "female": ("FİİM-eyl", "of the sex that gives birth", "A <b>female</b> bird was feeding her young."),
 "blood": ("BLAD", "the red liquid in your body", "The nurse took a sample of my <b>blood</b>."),
 "stone": ("STOUN", "a hard piece of rock", "The wall is made of <b>stone</b>."),
 "attack": ("ı-TEK", "a violent action against someone; to fight", "The soldiers began the <b>attack</b> at dawn."),
 "serious": ("Sİ-ri-ıs", "important; not joking; bad", "This is a <b>serious</b> illness."),
 "touch": ("TAÇ", "to put your hand on; contact", "Please don't <b>touch</b> the paintings."),
 "context": ("KON-tekst", "the situation around something", "In this <b>context</b>, the word means 'happy'."),
 "attractive": ("ı-TREK-tiv", "pleasant to look at", "She has an <b>attractive</b> smile."),
 "boil": ("BOYL", "to heat water until it bubbles", "<b>Boil</b> the eggs for ten minutes."),
 "sail": ("SEYL", "to travel on water in a boat", "They will <b>sail</b> to the island tomorrow."),
 "relationship": ("ri-LEY-şın-şip", "the way people are connected", "They have a good <b>relationship</b>."),
 "hers": ("HÖRZ", "belonging to a female", "This umbrella is <b>hers</b>."),
 "wooden": ("UU-dın", "made of wood", "We sat on a <b>wooden</b> bench."),
 "jewellery": ("CU-ıl-ri", "rings, necklaces and other decorations", "She keeps her <b>jewellery</b> in a box."),
 "continue": ("kın-TİN-yu", "to keep doing something", "Please <b>continue</b> reading."),
 "immediately": ("i-Mİİ-di-ıt-li", "at once; right away", "Call an ambulance <b>immediately</b>."),
 "neither": ("Nİİ-dır", "not one and not the other", "<b>Neither</b> answer is correct."),
 "mark": ("MARK", "a small sign; to give a grade", "There is a dirty <b>mark</b> on your shirt."),
 "knee": ("Nİİ", "the joint in the middle of your leg", "He hurt his <b>knee</b> playing football."),
 "drawing": ("DRO-ing", "a picture made with a pen or pencil", "She made a <b>drawing</b> of a cat."),
 "progress": ("PROU-gres", "movement forward; improvement", "You are making good <b>progress</b>."),
 "bridge": ("BRİC", "a structure that goes over a river or road", "We walked across the <b>bridge</b>."),
 "ankle": ("ENG-kıl", "the joint between your foot and leg", "She twisted her <b>ankle</b> on the stairs."),
 "since": ("SİNS", "from a time in the past; because", "I have lived here <b>since</b> 2010."),
 "comfortable": ("KAMF-tı-bıl", "giving a pleasant feeling; relaxed", "This chair is very <b>comfortable</b>."),
 "behave": ("bi-HEYV", "to act in a certain way", "The children <b>behaved</b> well at the party."),
 "light": ("LAYT", "brightness; not heavy", "The bag is very <b>light</b>."),
 "user": ("YU-zır", "a person who uses something", "The app has millions of <b>users</b>."),
 "region": ("Rİİ-cın", "a large area of land", "This <b>region</b> is famous for its wine."),
 "comment": ("KO-ment", "a remark; an opinion", "She made a kind <b>comment</b> about my work."),
 "dead": ("DED", "no longer alive", "The plant is <b>dead</b> because no one watered it."),
 "achieve": ("ı-ÇİİV", "to succeed in doing something", "She <b>achieved</b> her dream of becoming a doctor."),
 "injury": ("İN-cı-ri", "harm to the body", "The player has a knee <b>injury</b>."),
 "illness": ("İL-nıs", "a disease; the state of being sick", "He missed school because of <b>illness</b>."),
 "greet": ("GRİİT", "to say hello to someone", "She <b>greeted</b> her guests at the door."),
 "teaching": ("TİİÇ-ing", "the work of a teacher", "She loves <b>teaching</b> young children."),
 "fiction": ("FİK-şın", "stories that are not true", "I mostly read <b>fiction</b>."),
 "data": ("DA-tı", "facts and information", "The scientist collected a lot of <b>data</b>."),
 "amount": ("ı-MAUNT", "how much of something there is", "A large <b>amount</b> of water was wasted."),
 "farming": ("FAR-ming", "the work of growing crops and keeping animals", "<b>Farming</b> is hard work."),
 "surprising": ("sıp-RAY-zing", "unexpected", "The result was quite <b>surprising</b>."),
 "somewhere": ("SAM-ue-ır", "in or to some place", "I left my keys <b>somewhere</b> in the house."),
 "season": ("Sİİ-zın", "one of the four parts of the year", "Autumn is my favourite <b>season</b>."),
 "alternative": ("ol-TÖR-nı-tiv", "another choice", "Tea is a good <b>alternative</b> to coffee."),
 "recipe": ("RE-sı-pi", "instructions for cooking a dish", "I followed the <b>recipe</b> for the cake."),
 "slowly": ("SLOU-li", "at a low speed", "Please drive <b>slowly</b>."),
 "store": ("STOR", "a shop; to keep for later", "The <b>store</b> sells clothes and shoes."),
 "seem": ("SİİM", "to appear to be", "You <b>seem</b> tired today."),
 "shake": ("ŞEYK", "to move quickly up and down; to tremble", "<b>Shake</b> the bottle before you open it."),
 "recording": ("ri-KOR-ding", "sound or video that has been stored", "Listen to the <b>recording</b> and repeat."),
 "memory": ("ME-mı-ri", "the ability to remember; a thing remembered", "She has a good <b>memory</b> for names."),
 "either": ("İİ-dır", "one or the other of two", "You can take <b>either</b> road."),
 "request": ("ri-KUEST", "a polite demand; to ask for", "They made a <b>request</b> for more time."),
 "firstly": ("FÖRST-li", "in the first place", "<b>Firstly</b>, let me thank you all."),
 "certainly": ("SÖR-tın-li", "definitely; of course", "I will <b>certainly</b> help you."),
 "jam": ("CEM", "a sweet fruit spread; a blockage", "I like strawberry <b>jam</b> on toast."),
 "reception": ("ri-SEP-şın", "the front desk; a welcome party", "Ask for your key at <b>reception</b>."),
 "informal": ("in-FOR-mıl", "relaxed; not official", "It was an <b>informal</b> meeting."),
 "cash": ("KEŞ", "coins and notes; money", "Can I pay in <b>cash</b>?"),
 "education": ("e-cu-KEY-şın", "the process of teaching and learning", "A good <b>education</b> is important."),
 "palace": ("PE-lıs", "a large grand home of a king or queen", "The king lives in a beautiful <b>palace</b>."),
 "solve": ("SOLV", "to find an answer to a problem", "Can you <b>solve</b> this puzzle?"),
 "contain": ("kın-TEYN", "to have inside", "This box <b>contains</b> old photos."),
 "double": ("DA-bıl", "two times as much; for two people", "I'd like a <b>double</b> room, please."),
 "pleased": ("PLİİZD", "happy or satisfied", "I'm <b>pleased</b> to meet you."),
 "response": ("ris-PONS", "an answer or reaction", "I got a quick <b>response</b> to my email."),
 "carefully": ("KE-ır-fı-li", "with care and attention", "Read the instructions <b>carefully</b>."),
 "insect": ("İN-sekt", "a small animal with six legs", "A bee is an <b>insect</b>."),
 "guide": ("GAYD", "a person who shows the way; to lead", "The <b>guide</b> showed us around the museum."),
 "sauce": ("SOS", "a thick liquid served with food", "Add tomato <b>sauce</b> to the pasta."),
 "forest": ("FO-rist", "a large area of trees", "We walked through the <b>forest</b>."),
 "attention": ("ı-TEN-şın", "careful thought or notice", "Please pay <b>attention</b> to the teacher."),
 "tourism": ("TO-ri-zım", "the business of holidays and travel", "<b>Tourism</b> is important for this town."),
 "maths": ("METS", "the study of numbers (short for mathematics)", "I have a <b>maths</b> test tomorrow."),
 "vehicle": ("Vİİ-ı-kıl", "a machine for carrying people, like a car", "No <b>vehicles</b> are allowed in the park."),
 "spoon": ("SPUN", "a tool for eating soup or stirring", "Stir the tea with a <b>spoon</b>."),
 "instead": ("in-STED", "in place of something", "Let's walk <b>instead</b> of driving."),
 "low": ("LOU", "not high; near the ground", "The plane flew very <b>low</b>."),
}
