# -*- coding: utf-8 -*-
# Grup 18 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 18
DATA = {
 "coal": ("KOUL", "a black rock burned for heat", "They burned <b>coal</b> to warm the house."),
 "apologize": ("ı-PO-lı-cayz", "to say you are sorry", "He <b>apologized</b> for being late."),
 "vote": ("VOUT", "a choice in an election; to make that choice", "She is old enough to <b>vote</b>."),
 "plus": ("PLAS", "added to; and also", "Two <b>plus</b> two is four."),
 "exhibition": ("ek-si-Bİ-şın", "a public show of art or objects", "We saw a photo <b>exhibition</b>."),
 "statistic": ("stı-TİS-tik", "a fact shown as a number", "This <b>statistic</b> shows the number of visitors."),
 "heavily": ("HE-vi-li", "in a heavy way; a lot", "It was raining <b>heavily</b>."),
 "explode": ("iks-PLOUD", "to burst with a loud bang", "The old bomb might <b>explode</b>."),
 "relaxing": ("ri-LEK-sing", "helping you rest and feel calm", "A warm bath is very <b>relaxing</b>."),
 "backwards": ("BEK-uıdz", "towards the back", "Count <b>backwards</b> from ten."),
 "eastern": ("İİS-tın", "in or from the east", "They live in the <b>eastern</b> part of the country."),
 "childhood": ("ÇAYLD-hud", "the time when you are a child", "She had a happy <b>childhood</b>."),
 "ad": ("ED", "an advertisement", "I saw the job in an <b>ad</b>."),
 "mood": ("MUD", "the way you feel", "He is in a good <b>mood</b> today."),
 "printing": ("PRİN-ting", "the process of making words on paper", "The <b>printing</b> of the book took a week."),
 "nuclear": ("NUK-li-ır", "relating to atomic energy", "The country built a <b>nuclear</b> power station."),
 "remind": ("ri-MAYND", "to make someone remember", "Please <b>remind</b> me to call the doctor."),
 "agent": ("EY-cınt", "a person who acts for others; a spy", "A travel <b>agent</b> booked our trip."),
 "reality": ("ri-E-lı-ti", "the way things really are", "In <b>reality</b>, the job is very hard."),
 "absolutely": ("EB-sı-lut-li", "completely; totally", "You are <b>absolutely</b> right."),
 "sink": ("SİNK", "to go under water; a basin", "The heavy stone will <b>sink</b>."),
 "spicy": ("SPAY-si", "having a strong hot flavour", "I like <b>spicy</b> food."),
 "set": ("SET", "to put or fix; a group of things", "She has a full <b>set</b> of tools."),
 "assignment": ("ı-SAYN-mınt", "a task or piece of work", "The teacher gave us an <b>assignment</b>."),
 "protest": ("PROU-test", "a public show of disagreement", "Thousands joined the <b>protest</b>."),
 "range": ("REYNC", "a set of different things; the distance covered", "The shop sells a wide <b>range</b> of shoes."),
 "breathing": ("BRİİ-ding", "taking air in and out", "Deep <b>breathing</b> helps you relax."),
 "analysis": ("ı-NE-lı-sis", "a careful study of something", "The <b>analysis</b> showed a clear result."),
 "glad": ("GLED", "happy; pleased", "I'm <b>glad</b> you could come."),
 "previously": ("PRİİ-vi-ıs-li", "before now", "She had <b>previously</b> worked in a bank."),
 "poem": ("POU-im", "a piece of writing in verse", "He wrote a <b>poem</b> about the sea."),
 "shift": ("ŞİFT", "a work period; to move", "She works the night <b>shift</b>."),
 "queue": ("KYU", "a line of people waiting", "There was a long <b>queue</b> at the bank."),
 "stadium": ("STEY-di-ım", "a large sports ground with seats", "The football <b>stadium</b> was full."),
 "complaint": ("kım-PLEYNT", "a statement that you are not happy", "The customer made a <b>complaint</b>."),
 "lie (tell a lie)": ("LAY", "to say something untrue; an untrue statement", "Don't <b>lie</b> to me."),
 "disadvantage": ("di-sıd-VAN-tic", "something that makes things harder", "The high price is a <b>disadvantage</b>."),
 "exchange": ("iks-ÇEYNC", "to give one thing and get another", "Can I <b>exchange</b> this shirt for a bigger size?"),
 "pour": ("POR", "to make liquid flow out", "<b>Pour</b> the milk into the glass."),
 "translate": ("trenz-LEYT", "to change words into another language", "Can you <b>translate</b> this into Turkish?"),
 "retired": ("ri-TA-yıd", "no longer working because of age", "My grandfather is <b>retired</b>."),
 "contact": ("KON-tekt", "communication; to get in touch with", "Please <b>contact</b> me by email."),
 "spoken": ("SPOU-kın", "said in speech, not written", "Her <b>spoken</b> English is excellent."),
 "issue": ("İ-şu", "an important topic; a magazine number", "Money is a serious <b>issue</b>."),
 "coin": ("KOYN", "a piece of metal money", "She dropped a <b>coin</b> on the floor."),
 "flow": ("FLOU", "to move like a liquid; a steady movement", "The river <b>flows</b> to the sea."),
 "scan": ("SKEN", "to look over quickly; to use a machine to read", "The cashier will <b>scan</b> the barcode."),
 "warn": ("UORN", "to tell of a danger", "The sign <b>warns</b> drivers of ice."),
 "yard": ("YARD", "an area next to a building; a unit of length", "The children play in the <b>yard</b>."),
 "entrance": ("EN-trıns", "a way in", "The <b>entrance</b> is at the front of the building."),
 "software": ("SOFT-ue-ır", "computer programs", "We installed new <b>software</b> on the computer."),
 "unlikely": ("an-LAYK-li", "not probable", "It is <b>unlikely</b> to snow in summer."),
 "theme": ("TİİM", "the main subject or idea", "The <b>theme</b> of the film is friendship."),
 "excitement": ("ik-SAYT-mınt", "a feeling of being excited", "There was great <b>excitement</b> before the game."),
 "reservation": ("re-zır-VEY-şın", "a booking; a doubt", "I made a <b>reservation</b> at the restaurant."),
 "pin": ("PİN", "a thin pointed piece of metal", "She fixed the note with a <b>pin</b>."),
 "economic": ("e-kı-NO-mik", "relating to money and business", "The country has <b>economic</b> problems."),
 "despite": ("dis-PAYT", "in spite of", "<b>Despite</b> the rain, we enjoyed the trip."),
 "totally": ("TOU-tı-li", "completely", "I <b>totally</b> agree with you."),
 "port": ("PORT", "a town where ships load and unload", "The ship arrived at the <b>port</b>."),
 "determine": ("di-TÖR-min", "to decide or find out", "The test will <b>determine</b> your level."),
 "tiny": ("TAY-ni", "extremely small", "A <b>tiny</b> insect landed on my hand."),
 "repeated": ("ri-PİİT-id", "done again and again", "Her <b>repeated</b> efforts finally worked."),
 "legal": ("LİİG-ıl", "allowed by law", "It is <b>legal</b> to drive at eighteen."),
 "shell": ("ŞEL", "the hard outer cover of an egg or nut", "The crab hides in its <b>shell</b>."),
 "dust": ("DAST", "fine dry dirt", "There was <b>dust</b> on the old books."),
 "total": ("TOU-tıl", "the whole amount", "The <b>total</b> cost was fifty liras."),
 "fry": ("FRAY", "to cook in hot oil", "<b>Fry</b> the eggs for two minutes."),
 "presentation": ("pre-zın-TEY-şın", "a formal talk with information", "She gave a <b>presentation</b> about the project."),
 "relate": ("ri-LEYT", "to show a connection", "It's hard to <b>relate</b> these two ideas."),
 "coloured": ("KA-lırd", "having colour", "She drew with <b>coloured</b> pencils."),
 "prepared": ("pri-PE-ırd", "ready", "Are you <b>prepared</b> for the exam?"),
 "atmosphere": ("ET-mıs-fi-ır", "the air around the Earth; a mood", "The café had a friendly <b>atmosphere</b>."),
 "unpleasant": ("an-PLE-zınt", "not nice; unkind", "There was an <b>unpleasant</b> smell in the room."),
 "supply": ("sıp-LAY", "an amount available; to provide", "The town has a good water <b>supply</b>."),
 "channel": ("ÇE-nıl", "a TV station; a narrow area of water", "Which <b>channel</b> is the match on?"),
 "alcoholic": ("el-kı-HO-lik", "containing alcohol; addicted to alcohol", "They don't serve <b>alcoholic</b> drinks here."),
 "studio": ("STU-di-ou", "a room where art, music or films are made", "The band recorded the song in a <b>studio</b>."),
 "receipt": ("ri-SİİT", "a paper showing you paid", "Keep your <b>receipt</b> in case you return it."),
 "keen": ("KİİN", "very interested; eager", "She is <b>keen</b> to learn new things."),
 "brand": ("BREND", "a company's name for its products", "What <b>brand</b> of coffee do you buy?"),
 "symptom": ("SİMP-tım", "a sign of an illness", "A cough is a <b>symptom</b> of a cold."),
 "innocent": ("İ-nı-sınt", "not guilty; harmless", "The court found him <b>innocent</b>."),
 "surely": ("ŞOR-li", "certainly; without doubt", "<b>Surely</b> you remember me?"),
 "drunk": ("DRANK", "having had too much alcohol", "He was <b>drunk</b> after the party."),
 "continuous": ("kın-TİN-yu-ıs", "happening without stopping", "There was a <b>continuous</b> noise from the road."),
 "central": ("SENT-rıl", "in the middle; most important", "They live in a <b>central</b> part of town."),
 "related": ("ri-LEY-tid", "connected; in the same family", "These two problems are <b>related</b>."),
 "whenever": ("uen-E-vır", "at any time that", "Come <b>whenever</b> you like."),
 "celebration": ("se-li-BREY-şın", "a special event to mark something", "There was a big <b>celebration</b> for her birthday."),
 "therefore": ("DE-ır-for", "for that reason", "It was raining; <b>therefore</b>, we stayed inside."),
 "nation": ("NEY-şın", "a country and its people", "The whole <b>nation</b> watched the final."),
 "warning": ("UOR-ning", "something that tells of danger", "The weather <b>warning</b> said a storm was coming."),
 "update": ("AP-deyt", "to make current; the newest information", "Please <b>update</b> the app."),
 "treat": ("TRİİT", "to behave towards; to give medical care", "Doctors <b>treat</b> sick people."),
 "net": ("NET", "material with holes; the internet", "The fisherman threw his <b>net</b> into the sea."),
 "immigrant": ("İ-mig-rınt", "a person who moves to another country to live", "Her parents were <b>immigrants</b> from Italy."),
 "seriously": ("Sİ-ri-ıs-li", "in a serious way; really", "You should take this problem <b>seriously</b>."),
 "reject": ("ri-CEKT", "to refuse to accept", "The company may <b>reject</b> his offer."),
}
