# -*- coding: utf-8 -*-
# Grup 19 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 19
DATA = {
 "dirt": ("DÖRT", "dust, mud or other unclean matter", "His hands were covered in <b>dirt</b>."),
 "impact": ("İM-pekt", "a strong effect; a hit", "The new law had a big <b>impact</b> on farmers."),
 "attract": ("ıt-REKT", "to make someone or something come closer", "Bright flowers <b>attract</b> bees."),
 "living": ("Lİ-ving", "alive; the money you earn", "He earns a <b>living</b> by teaching."),
 "ugly": ("AG-li", "not nice to look at", "The old building is very <b>ugly</b>."),
 "indirect": ("in-day-REKT", "not going straight; not direct", "We took an <b>indirect</b> route to avoid traffic."),
 "payment": ("PEY-mınt", "money paid; the act of paying", "The first <b>payment</b> is due next month."),
 "leading": ("LİİD-ing", "most important; best", "She is a <b>leading</b> doctor in the city."),
 "forever": ("fı-RE-vır", "for all time", "I will remember this day <b>forever</b>."),
 "marketing": ("MAR-ki-ting", "the work of selling and advertising", "She works in <b>marketing</b>."),
 "survive": ("sır-VAYV", "to stay alive", "Plants cannot <b>survive</b> without water."),
 "file": ("FAYL", "a set of papers or computer data", "Save the <b>file</b> before you close it."),
 "hurry": ("HA-ri", "to move quickly; a need for speed", "<b>Hurry</b>, or we'll miss the bus!"),
 "unfair": ("an-FE-ır", "not just or equal", "It's <b>unfair</b> to blame only him."),
 "mall": ("MOL", "a large building with many shops", "We went shopping at the <b>mall</b>."),
 "sailor": ("SEY-lır", "a person who works on a ship", "The <b>sailor</b> tied the boat to the dock."),
 "technique": ("tek-NİİK", "a way of doing something skilfully", "She learned a new painting <b>technique</b>."),
 "client": ("KLA-yınt", "a person who pays for a service", "The lawyer met her <b>client</b>."),
 "bite": ("BAYT", "to cut with your teeth", "The dog might <b>bite</b> you."),
 "poet": ("POU-it", "a person who writes poems", "The <b>poet</b> read her work aloud."),
 "appreciate": ("ıp-RİİŞ-i-eyt", "to be grateful for; to value", "I <b>appreciate</b> your help."),
 "fighting": ("FAY-ting", "the act of struggling or battling", "The <b>fighting</b> lasted for days."),
 "divide": ("di-VAYD", "to split into parts", "<b>Divide</b> the cake into eight pieces."),
 "outdoors": ("aut-DORZ", "in the open air", "The children love playing <b>outdoors</b>."),
 "mixture": ("MİKS-çır", "a combination of different things", "Cake is a <b>mixture</b> of flour, eggs and sugar."),
 "pleasant": ("PLE-zınt", "nice; enjoyable", "We had a <b>pleasant</b> walk in the park."),
 "consequence": ("KON-si-kuıns", "a result of an action", "One <b>consequence</b> of the rain was a flood."),
 "countryside": ("KAN-tri-sayd", "land outside towns and cities", "We spent the weekend in the <b>countryside</b>."),
 "expedition": ("eks-pı-Dİ-şın", "a long journey for a purpose", "They went on an <b>expedition</b> to the North Pole."),
 "indoor": ("İN-dor", "inside a building", "The hotel has an <b>indoor</b> pool."),
 "friendship": ("FREND-şip", "a relationship between friends", "Their <b>friendship</b> lasted many years."),
 "gather": ("GE-dır", "to bring or come together", "A crowd began to <b>gather</b> in the square."),
 "discount": ("DİS-kaunt", "a reduction in price", "Students get a <b>discount</b> on tickets."),
 "recommendation": ("re-kı-men-DEY-şın", "a suggestion that something is good", "I bought the book on her <b>recommendation</b>."),
 "competitive": ("kım-PE-tı-tiv", "wanting to win; involving competition", "He is very <b>competitive</b> in sports."),
 "consist": ("kın-SİST", "to be made of", "The team <b>consists</b> of ten players."),
 "hunt": ("HANT", "to chase animals for food or sport", "Lions <b>hunt</b> at night."),
 "access": ("EK-ses", "a way to enter or use something", "Students have <b>access</b> to the library."),
 "represent": ("rep-ri-ZENT", "to act or speak for others; to be a sign of", "She will <b>represent</b> our school at the contest."),
 "truth": ("TRUT", "the real facts", "Please tell me the <b>truth</b>."),
 "political": ("pı-Lİ-ti-kıl", "relating to government and politics", "They discussed <b>political</b> news."),
 "trick": ("TRİK", "a clever action to fool someone", "The magician did an amazing <b>trick</b>."),
 "due": ("DU", "expected; needing to be paid", "The rent is <b>due</b> on the first of the month."),
 "stranger": ("STREYN-cır", "a person you do not know", "Don't talk to <b>strangers</b>."),
 "afford": ("ı-FORD", "to have enough money for", "We can't <b>afford</b> a new car."),
 "tape": ("TEYP", "a long thin strip that sticks; to record", "Use <b>tape</b> to fix the paper."),
 "quit": ("KUİT", "to stop or leave", "He decided to <b>quit</b> his job."),
 "content": ("kın-TENT", "what is inside; happy", "She felt <b>content</b> with her simple life."),
 "agreement": ("ı-GRİİ-mınt", "an arrangement people accept", "The two countries signed an <b>agreement</b>."),
 "convince": ("kın-VİNS", "to make someone believe something", "He tried to <b>convince</b> me to stay."),
 "authority": ("o-TO-rı-ti", "the power to control; an official group", "The teacher has <b>authority</b> over the class."),
 "deliver": ("di-Lİ-vır", "to take goods to a place", "They will <b>deliver</b> the sofa tomorrow."),
 "costume": ("KOS-tum", "special clothes for a role or event", "She wore a witch <b>costume</b> to the party."),
 "stick": ("STİK", "a thin piece of wood; to attach", "The dog fetched the <b>stick</b>."),
 "definite": ("DE-fi-nıt", "certain; clear", "We don't have a <b>definite</b> answer yet."),
 "chain": ("ÇEYN", "connected metal rings; a series", "The dog was on a <b>chain</b>."),
 "silent": ("SAY-lınt", "making no sound; quiet", "The whole room went <b>silent</b>."),
 "ingredient": ("in-GRİİ-di-ınt", "one of the foods used in a recipe", "Flour is the main <b>ingredient</b> in bread."),
 "policy": ("PO-lı-si", "a plan of action; an insurance document", "The company changed its <b>policy</b>."),
 "identity": ("ay-DEN-tı-ti", "who someone is", "The thief hid his <b>identity</b>."),
 "frequently": ("FRİİ-kuınt-li", "often", "She <b>frequently</b> travels for work."),
 "ceiling": ("SİİL-ing", "the top surface of a room", "There is a lamp on the <b>ceiling</b>."),
 "guard": ("GARD", "a person who protects; to protect", "A <b>guard</b> stood at the door."),
 "impressive": ("im-PRE-siv", "causing admiration", "The old castle was very <b>impressive</b>."),
 "frozen": ("FROU-zın", "turned to ice; very cold", "The lake was completely <b>frozen</b>."),
 "cruel": ("KRU-ıl", "causing pain on purpose; unkind", "It is <b>cruel</b> to hurt animals."),
 "embarrassing": ("im-BE-rı-sing", "making you feel ashamed", "It was an <b>embarrassing</b> mistake."),
 "battle": ("BE-tıl", "a fight in a war; a struggle", "The <b>battle</b> lasted all night."),
 "staff": ("STAF", "the people who work somewhere", "The hotel <b>staff</b> were very friendly."),
 "bake": ("BEYK", "to cook in an oven", "She likes to <b>bake</b> bread on Sundays."),
 "operation": ("o-pı-REY-şın", "a medical procedure; a planned activity", "He had an <b>operation</b> on his knee."),
 "youth": ("YUT", "the time of being young; young people", "She was a great dancer in her <b>youth</b>."),
 "clue": ("KLU", "a piece of information that helps solve something", "The police found an important <b>clue</b>."),
 "obvious": ("OB-vi-ıs", "easy to see or understand", "It was <b>obvious</b> that she was tired."),
 "suffer": ("SA-fır", "to feel pain or difficulty", "Many people <b>suffer</b> from back pain."),
 "row": ("ROU", "a line of things side by side", "We sat in the front <b>row</b>."),
 "latest": ("LEY-tist", "the most recent", "Have you heard the <b>latest</b> news?"),
 "account": ("ı-KAUNT", "a bank record; a description", "I opened a new bank <b>account</b>."),
 "loss": ("LOS", "the state of losing something", "The team's <b>loss</b> disappointed the fans."),
 "basis": ("BEY-sis", "the main idea or reason for something", "Trust is the <b>basis</b> of a good friendship."),
 "covered": ("KA-vırd", "having something over it", "The ground was <b>covered</b> with snow."),
 "invest": ("in-VEST", "to put money into something to gain more", "They <b>invest</b> in property."),
 "photography": ("fı-TOG-rı-fi", "the art of taking photos", "She studies <b>photography</b> at college."),
 "sight": ("SAYT", "the ability to see; something you see", "The mountains were a beautiful <b>sight</b>."),
 "flour": ("FLA-uır", "a powder from grain used to make bread", "Add two cups of <b>flour</b> to the bowl."),
 "talented": ("TE-lın-tid", "having natural skill", "She is a <b>talented</b> musician."),
 "shoot": ("ŞUT", "to fire a gun; to film", "Don't <b>shoot</b> the birds."),
 "practical": ("PREK-ti-kıl", "useful in real situations", "She gave me some <b>practical</b> advice."),
 "prayer": ("PRE-ır", "words spoken to a god", "She said a quiet <b>prayer</b>."),
 "analyse": ("E-nı-layz", "to study something carefully", "Scientists <b>analyse</b> the data."),
 "embarrassed": ("im-BE-rıst", "feeling ashamed or shy", "He was <b>embarrassed</b> when he forgot her name."),
 "producer": ("prı-DU-sır", "a person who makes films or goods", "The film <b>producer</b> found the money for the movie."),
 "reflect": ("ri-FLEKT", "to send back light or an image; to think", "The mirror <b>reflects</b> the light."),
 "poisonous": ("POY-zı-nıs", "able to cause illness or death", "Some mushrooms are <b>poisonous</b>."),
 "bomb": ("BOM", "a weapon that explodes", "The old <b>bomb</b> was found in the field."),
 "planning": ("PLE-ning", "the act of making plans", "Good <b>planning</b> saves time."),
 "judge": ("CAC", "a person who decides in court; to form an opinion", "The <b>judge</b> listened to both sides."),
 "union": ("YU-ni-ın", "a joining together; a workers' group", "He joined the workers' <b>union</b>."),
 "priest": ("PRİİST", "a religious leader", "The <b>priest</b> spoke to the people."),
 "romantic": ("rou-MEN-tik", "relating to love", "They had a <b>romantic</b> dinner."),
}
