# -*- coding: utf-8 -*-
# Grup 2 (A1) — okunuş / İngilizce açıklama / örnek cümle
# Okunuş: heceler tireli, vurgulu hece BÜYÜK, yalnız Türkçe harfler.
GRUP_NO = 2
DATA = {
 "else": ("ELS", "used to talk about other people or things; different", "What <b>else</b> do you need?"),
 "leave": ("LİİV", "to go away from a place; to let something stay", "We <b>leave</b> home at eight every morning."),
 "idea": ("ay-Dİ-yı", "a plan or thought in your mind", "That's a great <b>idea</b>!"),
 "possible": ("PO-sı-bıl", "able to happen or be done", "Is it <b>possible</b> to change my ticket?"),
 "video": ("Vİ-di-ou", "a recording of moving pictures", "We watched a funny <b>video</b> online."),
 "mouse": ("MAUS", "a small animal with a long tail; a computer tool", "The cat caught a <b>mouse</b>."),
 "seventeen": ("se-vın-TİİN", "the number 17", "She is <b>seventeen</b> years old."),
 "explain": ("iks-PLEYN", "to make something clear or easy to understand", "Can you <b>explain</b> this rule again?"),
 "mistake": ("mis-TEYK", "something you do wrong", "I made a <b>mistake</b> in the test."),
 "cut": ("KAT", "to divide something with a knife or scissors", "Please <b>cut</b> the bread."),
 "hear": ("HİİR", "to notice sounds with your ears", "Did you <b>hear</b> that noise?"),
 "table": ("TEY-bıl", "a piece of furniture with a flat top; a list of facts", "The keys are on the <b>table</b>."),
 "phrase": ("FREYZ", "a small group of words", "Learn this useful <b>phrase</b> by heart."),
 "last (final)": ("LAST", "coming after all the others", "December is the <b>last</b> month of the year."),
 "group": ("GRUP", "a number of people or things together", "We worked in a <b>group</b> of four."),
 "tired": ("TA-yırd", "needing rest or sleep", "I was very <b>tired</b> after work."),
 "two": ("TU", "the number 2", "I have <b>two</b> brothers."),
 "tourist": ("TU-rist", "a person who visits a place for holiday", "The city is full of <b>tourists</b> in summer."),
 "know": ("NOU", "to have information in your mind", "I <b>know</b> the answer."),
 "piano": ("pi-YE-nou", "a large musical instrument with black and white keys", "She plays the <b>piano</b> very well."),
 "pretty": ("PRİ-ti", "nice to look at; quite", "What a <b>pretty</b> dress!"),
 "hi": ("HAY", "an informal way to say hello", "<b>Hi</b>, how are you?"),
 "machine": ("mı-ŞİİN", "a piece of equipment that does a job", "This <b>machine</b> makes coffee."),
 "many": ("ME-ni", "a large number of", "<b>Many</b> students passed the exam."),
 "build": ("BİLD", "to make something like a house or bridge", "They want to <b>build</b> a new school here."),
 "bag": ("BEG", "a container for carrying things", "My <b>bag</b> is very heavy."),
 "soup": ("SUP", "a liquid food made from vegetables or meat", "We had tomato <b>soup</b> for dinner."),
 "spell": ("SPEL", "to say or write the letters of a word", "How do you <b>spell</b> your name?"),
 "writing": ("RAY-ting", "the activity of making words on paper; written words", "Her <b>writing</b> is very clear."),
 "cent": ("SENT", "a small unit of money (1/100 of a dollar or euro)", "The pen costs ninety-nine <b>cents</b>."),
 "hello": ("hı-LOU", "used as a greeting", "<b>Hello</b>, my name is Ayşe."),
 "clothes": ("KLOUZ", "things you wear, like shirts and trousers", "I bought some new <b>clothes</b>."),
 "Saturday": ("SE-tır-dey", "the day after Friday", "We go shopping on <b>Saturday</b>."),
 "body": ("BO-di", "the whole physical form of a person or animal", "Exercise is good for your <b>body</b>."),
 "somebody": ("SAM-bı-di", "a person you do not know or name", "<b>Somebody</b> left the door open."),
 "word": ("UÖRD", "a single unit of language", "What does this <b>word</b> mean?"),
 "letter": ("LE-tır", "a written message you send; a sign like A or B", "I wrote a <b>letter</b> to my grandmother."),
 "angry": ("ENG-ri", "feeling strong displeasure", "He was <b>angry</b> because the bus was late."),
 "fish": ("FİŞ", "an animal that lives and swims in water", "We caught three <b>fish</b> in the lake."),
 "name": ("NEYM", "the word people call you by", "My <b>name</b> is Mehmet."),
 "baby": ("BEY-bi", "a very young child", "The <b>baby</b> is sleeping now."),
 "watch": ("UOÇ", "to look at something for some time; a small clock", "We <b>watch</b> TV in the evening."),
 "ready": ("RE-di", "prepared and able to do something", "Dinner is <b>ready</b>!"),
 "favourite": ("FEY-vı-rit", "liked more than all others", "Blue is my <b>favourite</b> colour."),
 "delicious": ("di-Lİ-şıs", "very good to eat", "This cake is <b>delicious</b>!"),
 "wine": ("UAYN", "an alcoholic drink made from grapes", "They ordered a glass of <b>wine</b>."),
 "practice": ("PREK-tis", "doing something many times to get better", "You need more <b>practice</b> before the match."),
 "good": ("GUD", "of high quality; kind", "She is a <b>good</b> teacher."),
 "tonight": ("tı-NAYT", "on this night", "Are you free <b>tonight</b>?"),
 "sometimes": ("SAM-taymz", "on some occasions but not always", "I <b>sometimes</b> walk to work."),
 "that": ("DET", "the person or thing over there", "Whose is <b>that</b> car?"),
 "turn": ("TÖRN", "to move around; to change direction", "<b>Turn</b> left at the bank."),
 "diet": ("DA-yıt", "the food you usually eat; eating less to lose weight", "A healthy <b>diet</b> is important."),
 "interested": ("İN-tres-tid", "wanting to know more about something", "I'm <b>interested</b> in history."),
 "later": ("LEY-tır", "after some time", "See you <b>later</b>!"),
 "answer": ("AN-sır", "what you say or write to a question", "Do you know the <b>answer</b>?"),
 "March": ("MARÇ", "the third month of the year", "Spring begins in <b>March</b>."),
 "die": ("DAY", "to stop living", "Many plants <b>die</b> without water."),
 "beach": ("BİİÇ", "a sandy area next to the sea", "The children played on the <b>beach</b>."),
 "period": ("Pİ-ri-yıd", "a length of time", "We lived there for a short <b>period</b>."),
 "dictionary": ("DİK-şın-ri", "a book or app that explains words", "Look up new words in a <b>dictionary</b>."),
 "small": ("SMOL", "little in size", "They live in a <b>small</b> flat."),
 "pencil": ("PEN-sıl", "a thin tool for writing or drawing", "Write your name with a <b>pencil</b>."),
 "move": ("MUV", "to change place or position", "Can you help me <b>move</b> this table?"),
 "look": ("LUK", "to turn your eyes towards something; to seem", "<b>Look</b> at this photo!"),
 "adult": ("ı-DALT", "a fully grown person", "Tickets are cheaper for children than for <b>adults</b>."),
 "ago": ("ı-GOU", "before now; in the past", "We met two years <b>ago</b>."),
 "trousers": ("TRAU-zırz", "a piece of clothing for your legs", "These <b>trousers</b> are too long."),
 "mother": ("MA-dır", "a female parent", "My <b>mother</b> makes great soup."),
 "hard": ("HARD", "difficult; not soft", "The exam was very <b>hard</b>."),
 "after": ("AF-tır", "later than something", "Let's meet <b>after</b> lunch."),
 "October": ("ok-TOU-bır", "the tenth month of the year", "The weather gets cooler in <b>October</b>."),
 "teenager": ("TİİN-ey-cır", "a person between 13 and 19 years old", "The film is popular with <b>teenagers</b>."),
 "nothing": ("NA-ting", "not anything", "There is <b>nothing</b> in the box."),
 "past": ("PAST", "the time before now; beyond", "Forget the <b>past</b> and look forward."),
 "become": ("bi-KAM", "to start to be something", "She wants to <b>become</b> a doctor."),
 "taxi": ("TEK-si", "a car you pay to travel in", "We took a <b>taxi</b> to the airport."),
 "under": ("AN-dır", "below something", "The cat is <b>under</b> the table."),
 "dancing": ("DAN-sing", "moving your body to music", "She loves <b>dancing</b> at parties."),
 "help": ("HELP", "to do something useful for someone", "Can you <b>help</b> me with this bag?"),
 "meaning": ("Mİİ-ning", "what a word or sign tells you", "What is the <b>meaning</b> of this word?"),
 "neighbour": ("NEY-bır", "a person who lives near you", "Our <b>neighbour</b> has two dogs."),
 "miss": ("MİS", "to feel sad because someone is not there; to not catch", "I <b>miss</b> my old friends."),
 "lunch": ("LANÇ", "the meal you eat in the middle of the day", "We had <b>lunch</b> at noon."),
 "song": ("SONG", "a piece of music with words", "This is my favourite <b>song</b>."),
 "my": ("MAY", "belonging to me", "This is <b>my</b> phone."),
 "fruit": ("FRUT", "food like apples, oranges and bananas", "Eat fresh <b>fruit</b> every day."),
 "visitor": ("Vİ-zi-tır", "a person who comes to see a place or person", "The museum gets many <b>visitors</b>."),
 "study": ("STA-di", "to learn about something; learning", "I <b>study</b> English every evening."),
 "apple": ("E-pıl", "a round fruit with red or green skin", "She eats an <b>apple</b> every morning."),
 "prefer": ("pri-FÖR", "to like one thing more than another", "I <b>prefer</b> tea to coffee."),
 "thousand": ("TAU-zınd", "the number 1,000", "The castle is a <b>thousand</b> years old."),
 "midnight": ("MİD-nayt", "twelve o'clock at night", "The party ended at <b>midnight</b>."),
 "detail": ("Dİİ-teyl", "a small piece of information", "Tell me every <b>detail</b> of the trip."),
 "hobby": ("HO-bi", "an activity you enjoy in your free time", "Painting is my favourite <b>hobby</b>."),
 "class": ("KLAS", "a group of students; a lesson", "Our <b>class</b> starts at nine."),
 "month": ("MANT", "one of the twelve parts of a year", "July is the hottest <b>month</b> here."),
 "tea": ("Tİİ", "a hot drink made from dried leaves", "Would you like a cup of <b>tea</b>?"),
 "well": ("UEL", "in a good way; healthy", "She speaks English very <b>well</b>."),
 "life": ("LAYF", "the time between birth and death; way of living", "City <b>life</b> is busy and fast."),
}
