# -*- coding: utf-8 -*-
# Grup 20 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 20
DATA = {
 "cheerful": ("Çİ-ır-fıl", "happy and positive", "She has a <b>cheerful</b> smile."),
 "breath": ("BRET", "the air you take into your lungs", "Take a deep <b>breath</b> and relax."),
 "frighten": ("FRAY-tın", "to make someone afraid", "Loud noises <b>frighten</b> the dog."),
 "cap": ("KEP", "a soft hat; a lid", "He wore a baseball <b>cap</b>."),
 "indicate": ("İN-di-keyt", "to show or point out", "The sign <b>indicates</b> the way to the exit."),
 "belief": ("bi-LİİF", "a feeling that something is true", "It is her <b>belief</b> that hard work pays off."),
 "claim": ("KLEYM", "to say something is true; a demand", "He <b>claims</b> that he saw a ghost."),
 "unless": ("ın-LES", "except if", "I won't go <b>unless</b> you come with me."),
 "responsible": ("ris-PON-sı-bıl", "having a duty; to blame", "Parents are <b>responsible</b> for their children."),
 "indoors": ("in-DORZ", "inside a building", "We stayed <b>indoors</b> during the storm."),
 "supporter": ("sı-POR-tır", "a person who supports a team or idea", "He is a loyal <b>supporter</b> of the team."),
 "bell": ("BEL", "a metal object that makes a ringing sound", "The school <b>bell</b> rang at nine."),
 "mild": ("MAYLD", "not strong; gentle; not cold", "The winter was quite <b>mild</b> this year."),
 "racing": ("REY-sing", "the sport of competing for speed", "He loves horse <b>racing</b>."),
 "naturally": ("NE-çı-rı-li", "in a natural way; of course", "<b>Naturally</b>, she was happy about the news."),
 "personally": ("PÖR-sı-nı-li", "as your own opinion; in person", "<b>Personally</b>, I prefer tea."),
 "edge": ("EC", "the outer part of something", "Don't stand near the <b>edge</b> of the cliff."),
 "sensible": ("SEN-sı-bıl", "showing good judgement", "It was a <b>sensible</b> decision."),
 "base": ("BEYS", "the bottom; a main part", "The lamp has a heavy <b>base</b>."),
 "private": ("PRAY-vıt", "for one person only; not public", "This is a <b>private</b> garden."),
 "bury": ("BE-ri", "to put under the ground", "Dogs like to <b>bury</b> bones."),
 "category": ("KE-tı-gı-ri", "a group of similar things", "Books are sorted by <b>category</b>."),
 "security": ("si-KYU-rı-ti", "safety; protection", "Airport <b>security</b> checked our bags."),
 "conclusion": ("kın-KLU-jın", "the end; a decision after thinking", "At the <b>conclusion</b> of the talk, everyone clapped."),
 "basic": ("BEY-sik", "simple; most important", "He has a <b>basic</b> knowledge of French."),
 "unnecessary": ("an-NE-sı-sı-ri", "not needed", "Buying two was <b>unnecessary</b>."),
 "disappointed": ("di-sı-POYN-tid", "sad because something was not as good as hoped", "I was <b>disappointed</b> with the film."),
 "fixed": ("FİKST", "not moving or changing; repaired", "The prices are <b>fixed</b>."),
 "curtain": ("KÖR-tın", "cloth that hangs over a window", "Please close the <b>curtain</b>."),
 "injure": ("İN-cır", "to hurt the body", "He might <b>injure</b> himself on the ice."),
 "hurricane": ("HA-ri-kın", "a very strong tropical storm", "The <b>hurricane</b> damaged many homes."),
 "soil": ("SOYL", "the top layer of earth where plants grow", "The <b>soil</b> here is good for farming."),
 "alarm": ("ı-LARM", "a warning sound; a clock that wakes you", "The fire <b>alarm</b> went off."),
 "expand": ("iks-PEND", "to become larger", "The company plans to <b>expand</b> abroad."),
 "advanced": ("ıd-VANST", "at a high level", "She takes an <b>advanced</b> English class."),
 "folk": ("FOUK", "people; traditional (music)", "We listened to <b>folk</b> music."),
 "mess": ("MES", "an untidy state", "Your room is in a <b>mess</b>."),
 "typically": ("Tİ-pik-li", "usually; in a typical way", "I <b>typically</b> start work at nine."),
 "indeed": ("in-DİİD", "really; in fact", "It was a very cold day <b>indeed</b>."),
 "rough": ("RAF", "not smooth; not gentle; difficult", "The road was <b>rough</b> and bumpy."),
 "aged": ("EYCD", "of a certain age; old", "A man <b>aged</b> forty applied for the job."),
 "proper": ("PRO-pır", "correct; suitable", "Wear <b>proper</b> shoes for hiking."),
 "mine": ("MAYN", "belonging to me; a place to dig for coal", "The workers went down into the coal <b>mine</b>."),
 "organized": ("OR-gı-nayzd", "arranged well; tidy", "She is very <b>organized</b> at work."),
 "written": ("Rİ-tın", "put down in words on paper", "The rules are clearly <b>written</b>."),
 "lonely": ("LOUN-li", "sad because you are alone", "He felt <b>lonely</b> in the new city."),
 "generation": ("ce-nı-REY-şın", "all the people born around the same time", "My grandmother's <b>generation</b> worked very hard."),
 "location": ("lou-KEY-şın", "a place or position", "The shop is in a good <b>location</b>."),
 "garage": ("GE-ric", "a place to keep or fix a car", "He parks his car in the <b>garage</b>."),
 "measure": ("ME-jır", "to find the size; an action to solve a problem", "<b>Measure</b> the room before buying a carpet."),
 "alcohol": ("EL-kı-hol", "the substance in drinks like wine and beer", "He never drinks <b>alcohol</b>."),
 "production": ("prı-DAK-şın", "the process of making things", "Car <b>production</b> increased this year."),
 "nor": ("NOR", "and not (after neither)", "She neither called <b>nor</b> wrote."),
 "throughout": ("tru-AUT", "in every part; during the whole time", "It rained <b>throughout</b> the night."),
 "sudden": ("SA-dın", "happening quickly and unexpectedly", "There was a <b>sudden</b> change in the weather."),
 "slightly": ("SLAYT-li", "a little", "I feel <b>slightly</b> better today."),
 "element": ("E-li-mınt", "a basic part of something", "Trust is an important <b>element</b> of teamwork."),
 "royal": ("RO-yıl", "relating to a king or queen", "The <b>royal</b> family lives in a palace."),
 "southern": ("SA-dın", "in or from the south", "They come from the <b>southern</b> part of the country."),
 "hang": ("HENG", "to attach something at the top", "<b>Hang</b> your coat on the hook."),
 "mental": ("MEN-tıl", "relating to the mind", "Reading is good <b>mental</b> exercise."),
 "poetry": ("POU-ıt-ri", "poems in general", "She enjoys reading <b>poetry</b>."),
 "headline": ("HED-layn", "the title of a news story", "The <b>headline</b> was on the front page."),
 "ours": ("A-uırz", "belonging to us", "That house is <b>ours</b>."),
 "viewer": ("VYU-ır", "a person who watches TV", "The show has millions of <b>viewers</b>."),
 "importance": ("im-POR-tıns", "the quality of being important", "She explained the <b>importance</b> of sleep."),
 "fitness": ("FİT-nıs", "the state of being healthy and strong", "Running improves your <b>fitness</b>."),
 "promote": ("prı-MOUT", "to give a higher job; to advertise", "They will <b>promote</b> her to manager."),
 "meanwhile": ("MİİN-uayl", "at the same time", "I cooked; <b>meanwhile</b>, he cleaned."),
 "guilty": ("GİL-ti", "having done wrong", "The jury found him <b>guilty</b>."),
 "northern": ("NOR-dın", "in or from the north", "Winters are cold in the <b>northern</b> region."),
 "shine": ("ŞAYN", "to give out light", "The stars <b>shine</b> at night."),
 "episode": ("E-pi-soud", "one part of a TV series; an event", "I watched the last <b>episode</b> yesterday."),
 "unable": ("an-EY-bıl", "not able to do something", "She was <b>unable</b> to attend the meeting."),
 "generous": ("CE-nı-rıs", "willing to give and share", "He is very <b>generous</b> with his time."),
 "weigh": ("UEY", "to measure how heavy something is", "Please <b>weigh</b> the apples."),
 "located": ("lou-KEY-tid", "placed or situated", "The hotel is <b>located</b> near the beach."),
 "immediate": ("i-Mİİ-di-ıt", "happening at once", "The doctor gave <b>immediate</b> help."),
 "freeze": ("FRİİZ", "to turn to ice", "Water will <b>freeze</b> at zero degrees."),
 "rugby": ("RAG-bi", "a team sport with an oval ball", "They play <b>rugby</b> on Saturdays."),
 "quotation": ("kuou-TEY-şın", "words repeated from someone; a price offer", "She began her speech with a famous <b>quotation</b>."),
 "odd": ("OD", "strange; not even (of numbers)", "It's <b>odd</b> that he didn't call."),
 "sand": ("SEND", "tiny grains found on beaches", "The children built a castle in the <b>sand</b>."),
 "decade": ("DE-keyd", "a period of ten years", "She has lived here for a <b>decade</b>."),
 "entry": ("ENT-ri", "the act of entering; a way in", "<b>Entry</b> to the museum is free."),
 "plot": ("PLOT", "the story of a book or film; a secret plan", "The <b>plot</b> of the film was very exciting."),
 "neighbourhood": ("NEY-bır-hud", "the area around where you live", "It's a friendly <b>neighbourhood</b>."),
 "breathe": ("BRİİD", "to take air in and out", "It's hard to <b>breathe</b> at high altitude."),
 "upset": ("ap-SET", "unhappy or worried; to make sad", "She was <b>upset</b> about the bad news."),
 "wing": ("UİNG", "the part a bird or plane uses to fly", "The bird hurt its <b>wing</b>."),
 "development": ("di-VE-lıp-mınt", "the process of growing or improving", "The <b>development</b> of the town took years."),
 "determined": ("di-TÖR-mind", "having a strong wish to do something", "She is <b>determined</b> to win."),
 "host": ("HOUST", "a person who has guests; a TV presenter", "Our <b>host</b> welcomed us warmly."),
 "current": ("KA-rınt", "of the present time; a flow of water or electricity", "What is the <b>current</b> price of gold?"),
 "politics": ("PO-lı-tiks", "activities relating to government", "He is interested in <b>politics</b>."),
 "release": ("ri-LİİS", "to set free; to make available", "They will <b>release</b> the film next month."),
 "string": ("STRİNG", "thin cord; a series", "Tie the box with <b>string</b>."),
 "mad": ("MED", "crazy; very angry", "He was <b>mad</b> at me for being late."),
 "powder": ("PA-udır", "a fine dry substance", "Add the milk <b>powder</b> to the water."),
 "complex": ("KOM-pleks", "having many connected parts; not simple", "The machine has a <b>complex</b> design."),
}
