# -*- coding: utf-8 -*-
# Grup 21 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 21
DATA = {
 "expected": ("iks-PEK-tid", "thought likely to happen", "The train arrived at the <b>expected</b> time."),
 "scientific": ("sa-yın-Tİ-fik", "relating to science", "They did a <b>scientific</b> study of the plant."),
 "amazed": ("ı-MEYZD", "very surprised", "I was <b>amazed</b> by the beautiful view."),
 "confuse": ("kın-FYUZ", "to make someone unable to understand", "The map may <b>confuse</b> you."),
 "ambitious": ("em-Bİ-şıs", "having a strong wish to succeed", "She is a young and <b>ambitious</b> lawyer."),
 "painful": ("PEYN-fıl", "causing pain", "The injection was quite <b>painful</b>."),
 "trend": ("TREND", "a general change or direction", "There is a <b>trend</b> towards healthy eating."),
 "spirit": ("SPİ-rit", "the soul; energy and mood", "The team played with great <b>spirit</b>."),
 "slice": ("SLAYS", "a thin flat piece cut off", "Would you like a <b>slice</b> of cake?"),
 "application": ("ep-li-KEY-şın", "a formal request; a computer program", "She sent an <b>application</b> for the job."),
 "native": ("NEY-tiv", "relating to where you were born", "English is her <b>native</b> language."),
 "confident": ("KON-fi-dınt", "sure of yourself", "He felt <b>confident</b> before the exam."),
 "admire": ("ıd-MA-yır", "to respect and like", "I <b>admire</b> her courage."),
 "equal": ("İİ-kuıl", "the same in amount or value", "Cut the cake into <b>equal</b> pieces."),
 "limit": ("Lİ-mit", "the greatest amount allowed", "The speed <b>limit</b> is fifty here."),
 "respect": ("ris-PEKT", "admiration; to think highly of", "Students should <b>respect</b> their teachers."),
 "cheat": ("ÇİİT", "to act dishonestly to win", "Don't <b>cheat</b> in the exam."),
 "summary": ("SA-mı-ri", "a short account of the main points", "Write a <b>summary</b> of the story."),
 "campaign": ("kem-PEYN", "a planned set of actions for a goal", "They started a <b>campaign</b> to clean the beach."),
 "strongly": ("STRONG-li", "in a strong way; firmly", "I <b>strongly</b> disagree with that."),
 "fashionable": ("FE-şı-nı-bıl", "popular in style", "That coat is very <b>fashionable</b>."),
 "pan": ("PEN", "a metal container for cooking", "Heat the oil in a <b>pan</b>."),
 "competitor": ("kım-PE-ti-tır", "a person or company that competes", "Our main <b>competitor</b> lowered its prices."),
 "effective": ("i-FEK-tiv", "working well; producing a result", "This is an <b>effective</b> way to save money."),
 "giant": ("CA-yınt", "very large; a huge person", "A <b>giant</b> ship sailed into the port."),
 "essential": ("i-SEN-şıl", "extremely important; necessary", "Water is <b>essential</b> for life."),
 "sexual": ("SEK-şu-ıl", "relating to sex", "The film deals with <b>sexual</b> topics."),
 "risk": ("RİSK", "the chance of something bad", "There is a <b>risk</b> of injury in this sport."),
 "upon": ("ı-PON", "on", "The decision depends <b>upon</b> the results."),
 "management": ("ME-nic-mınt", "the control of a business; the managers", "The <b>management</b> announced new rules."),
 "magic": ("ME-cik", "a special power that seems impossible", "The children believe in <b>magic</b>."),
 "communication": ("kı-myu-ni-KEY-şın", "the sharing of information", "Good <b>communication</b> is important in a team."),
 "block": ("BLOK", "a solid piece; to stop movement", "A fallen tree <b>blocked</b> the road."),
 "violent": ("VA-yı-lınt", "using physical force to hurt", "The film has some <b>violent</b> scenes."),
 "emergency": ("i-MÖR-cın-si", "a sudden dangerous situation", "Call this number in an <b>emergency</b>."),
 "peaceful": ("PİİS-fıl", "calm and quiet; without war", "The village is a <b>peaceful</b> place."),
 "robot": ("ROU-bot", "a machine that can do tasks", "The factory uses a <b>robot</b> to build cars."),
 "poison": ("POY-zın", "a substance that can kill or harm", "The bottle was labelled '<b>poison</b>'."),
 "doubt": ("DAUT", "a feeling of not being sure", "There is no <b>doubt</b> that she is talented."),
 "worth": ("UÖRT", "having a certain value", "The painting is <b>worth</b> a lot of money."),
 "pleasure": ("PLE-jır", "a feeling of enjoyment", "It's a <b>pleasure</b> to meet you."),
 "goods": ("GUDZ", "things that are made to be sold", "The train carried <b>goods</b> across the country."),
 "relation": ("ri-LEY-şın", "a connection; a family member", "There is a close <b>relation</b> between diet and health."),
 "outdoor": ("AUT-dor", "happening in the open air", "They have an <b>outdoor</b> swimming pool."),
 "educated": ("E-cu-key-tid", "having had a good education", "She is a well-<b>educated</b> woman."),
 "educational": ("e-cu-KEY-şı-nıl", "helping people to learn", "The museum has many <b>educational</b> games."),
 "explosion": ("iks-PLOU-jın", "a sudden violent burst", "The <b>explosion</b> broke all the windows."),
 "tax": ("TEKS", "money paid to the government", "We pay <b>tax</b> on our income."),
 "photographer": ("fı-TOG-rı-fır", "a person who takes photos", "The wedding <b>photographer</b> took many pictures."),
 "equally": ("İİ-kuı-li", "in the same way; to the same degree", "The money was shared <b>equally</b>."),
 "investigate": ("in-VES-ti-geyt", "to examine carefully to find facts", "The police will <b>investigate</b> the crime."),
 "substance": ("SAB-stıns", "a material with certain properties", "Salt is a common <b>substance</b>."),
 "branch": ("BRANÇ", "a part of a tree; an office of a company", "The bank has a <b>branch</b> in every town."),
 "champion": ("ÇEM-pi-ın", "the winner of a competition", "She is the world swimming <b>champion</b>."),
 "entertainment": ("en-tır-TEYN-mınt", "things that amuse people", "The park offers <b>entertainment</b> for children."),
 "cultural": ("KAL-çı-rıl", "relating to the arts and customs", "The city has many <b>cultural</b> events."),
 "ahead": ("ı-HED", "in front; in the future", "Look <b>ahead</b>, not back."),
 "tongue": ("TANG", "the soft part in your mouth used for tasting", "The hot soup burned my <b>tongue</b>."),
 "appointment": ("ı-POYNT-mınt", "an arranged meeting", "I have a doctor's <b>appointment</b> at three."),
 "annoyed": ("ı-NOYD", "a little angry", "She was <b>annoyed</b> by the loud music."),
 "sharp": ("ŞARP", "having a fine edge; sudden", "Be careful; the knife is very <b>sharp</b>."),
 "unlike": ("an-LAYK", "different from", "<b>Unlike</b> her sister, she loves sport."),
 "liquid": ("Lİ-kuid", "a substance that flows, like water", "Water is a <b>liquid</b>."),
 "documentary": ("dok-yu-MEN-tri", "a film about real events", "We watched a <b>documentary</b> about lions."),
 "escape": ("is-KEYP", "to get free from a place", "The prisoner tried to <b>escape</b>."),
 "ambition": ("em-Bİ-şın", "a strong wish to achieve something", "Her <b>ambition</b> is to become a pilot."),
 "responsibility": ("ris-pon-sı-Bİ-lı-ti", "a duty to deal with something", "Cleaning the kitchen is my <b>responsibility</b>."),
 "require": ("ri-KUA-yır", "to need", "This recipe <b>requires</b> three eggs."),
 "particularly": ("pır-TİK-yu-lı-li", "especially", "I <b>particularly</b> like the blue one."),
 "academic": ("e-kı-DE-mik", "relating to education and study", "She had an excellent <b>academic</b> record."),
 "consume": ("kın-SUM", "to eat, drink or use up", "Cars <b>consume</b> a lot of fuel."),
 "emotion": ("i-MOU-şın", "a strong feeling", "Joy is a positive <b>emotion</b>."),
 "advise": ("ıd-VAYZ", "to give advice", "The doctor <b>advised</b> me to rest."),
 "religious": ("ri-Lİ-cıs", "relating to religion", "They hold <b>religious</b> ceremonies here."),
 "pot": ("POT", "a deep round container for cooking or plants", "She planted flowers in a <b>pot</b>."),
 "uncomfortable": ("an-KAMF-tı-bıl", "not comfortable", "The seats were hard and <b>uncomfortable</b>."),
 "fasten": ("FA-sın", "to join or fix firmly", "Please <b>fasten</b> your seat belt."),
 "wool": ("UUL", "the soft hair of sheep used for clothes", "This jumper is made of <b>wool</b>."),
 "annoy": ("ı-NOY", "to make someone a little angry", "Loud chewing can <b>annoy</b> people."),
 "old-fashioned": ("ould-FE-şınd", "not modern; out of style", "My grandmother has <b>old-fashioned</b> ideas."),
 "tight": ("TAYT", "fitting closely; firm", "These shoes are too <b>tight</b>."),
 "persuade": ("pır-SUEYD", "to make someone agree by giving reasons", "She <b>persuaded</b> him to come."),
 "shiny": ("ŞAY-ni", "bright and reflecting light", "He drove a <b>shiny</b> new car."),
 "border": ("BOR-dır", "the line between two countries; an edge", "They crossed the <b>border</b> into Greece."),
 "pipe": ("PAYP", "a tube for carrying water or gas", "Water flows through this <b>pipe</b>."),
 "announcement": ("ı-NAUNS-mınt", "a public statement", "There was an <b>announcement</b> at the station."),
 "ought": ("OT", "should; used to give advice", "You <b>ought</b> to see a doctor."),
 "fuel": ("FYU-ıl", "material burned to make energy", "The plane needs more <b>fuel</b>."),
 "version": ("VÖR-şın", "a form of something", "This is the newest <b>version</b> of the app."),
 "force": ("FORS", "power; to make someone do something", "The wind hit the boat with great <b>force</b>."),
 "pretend": ("pri-TEND", "to act as if something is true", "The children <b>pretend</b> to be pirates."),
 "religion": ("ri-Lİ-cın", "belief in a god or gods", "People of every <b>religion</b> live here."),
 "cloth": ("KLOT", "material made by weaving", "Wipe the table with a wet <b>cloth</b>."),
 "pale": ("PEYL", "light in colour; not bright", "She looked <b>pale</b> and tired."),
 "beauty": ("BYU-ti", "the quality of being beautiful", "We admired the <b>beauty</b> of the mountains."),
 "experienced": ("iks-Pİ-ri-ınst", "having a lot of skill from practice", "He is an <b>experienced</b> teacher."),
 "generally": ("CEN-rı-li", "usually; mostly", "<b>Generally</b>, I go to bed early."),
 "toe": ("TOU", "one of the parts at the end of your foot", "I hurt my <b>toe</b> on the door."),
 "careless": ("KE-ır-lıs", "not giving enough attention", "It was <b>careless</b> to leave the door open."),
 "bubble": ("BA-bıl", "a ball of air in liquid", "The child blew a soap <b>bubble</b>."),
}
