# -*- coding: utf-8 -*-
# Grup 22 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 22
DATA = {
 "global": ("GLOU-bıl", "relating to the whole world", "Climate change is a <b>global</b> problem."),
 "press": ("PRES", "to push firmly; the news media", "<b>Press</b> the button to start."),
 "click": ("KLİK", "to press a computer mouse; a short sharp sound", "<b>Click</b> the link to open the page."),
 "frightening": ("FRAYT-ning", "causing fear", "It was a <b>frightening</b> experience."),
 "smooth": ("SMUD", "having an even surface; without problems", "The baby's skin is very <b>smooth</b>."),
 "powerful": ("PA-uır-fıl", "having a lot of power", "The car has a <b>powerful</b> engine."),
 "battery": ("BE-tı-ri", "a device that stores electricity", "My phone <b>battery</b> is low."),
 "heating": ("HİİT-ing", "a system that keeps a building warm", "Turn on the <b>heating</b>; it's cold."),
 "various": ("VE-ri-ıs", "several different", "The shop sells <b>various</b> kinds of tea."),
 "earthquake": ("ÖRT-kueyk", "a sudden shaking of the ground", "The <b>earthquake</b> damaged many buildings."),
 "politician": ("po-lı-Tİ-şın", "a person in government or politics", "The <b>politician</b> gave a long speech."),
 "throat": ("TROUT", "the front of the neck; the passage to the stomach", "I have a sore <b>throat</b>."),
 "prince": ("PRİNS", "the son of a king or queen", "The <b>prince</b> lived in a castle."),
 "gentle": ("CEN-tıl", "kind and soft; not rough", "Be <b>gentle</b> with the baby."),
 "victim": ("VİK-tim", "a person who is harmed", "He was the <b>victim</b> of a robbery."),
 "whatever": ("uot-E-vır", "anything; no matter what", "Do <b>whatever</b> you think is best."),
 "rent": ("RENT", "money paid to use a home; to pay for use", "The monthly <b>rent</b> is high."),
 "murder": ("MÖR-dır", "the crime of killing someone", "The police are investigating a <b>murder</b>."),
 "layer": ("LE-ır", "a single thickness of something", "There was a thick <b>layer</b> of snow."),
 "confused": ("kın-FYUZD", "unable to understand", "I was <b>confused</b> by the directions."),
 "narrative": ("NE-rı-tiv", "a story or description of events", "The book has an exciting <b>narrative</b>."),
 "stick": ("STİK", "a thin piece of wood; to attach", "The dog chewed the <b>stick</b>."),
 "switch": ("SUİÇ", "a button to turn things on or off; to change", "<b>Switch</b> off the light before you leave."),
 "killing": ("Kİ-ling", "the act of causing death", "The <b>killing</b> of the elephants shocked everyone."),
 "organizer": ("OR-gı-nay-zır", "a person who plans an event", "She is the <b>organizer</b> of the festival."),
 "glove": ("GLAV", "a cover for the hand", "He wore thick <b>gloves</b> in the snow."),
 "race": ("REYS", "a speed competition; a group of people", "She came first in the <b>race</b>."),
 "financial": ("fı-NEN-şıl", "relating to money", "The company has <b>financial</b> problems."),
 "growth": ("GROUT", "the process of growing", "The <b>growth</b> of the city was fast."),
 "literature": ("Lİ-trı-çır", "written works like novels and poems", "She studies English <b>literature</b>."),
 "spending": ("SPEN-ding", "the act of using money", "The government cut its <b>spending</b>."),
 "educate": ("E-cu-keyt", "to teach; to give knowledge", "Schools <b>educate</b> children."),
 "import": ("İM-port", "goods brought from abroad; to bring in", "The country's main <b>import</b> is oil."),
 "western": ("UES-tın", "in or from the west", "They live on the <b>western</b> coast."),
 "familiar": ("fı-Mİ-li-ır", "well known; easy to recognize", "Her face looked <b>familiar</b>."),
 "calm": ("KAM", "quiet and relaxed; not rough", "Stay <b>calm</b> and don't panic."),
 "profession": ("prı-FE-şın", "a job that needs special training", "Teaching is a respected <b>profession</b>."),
 "bother": ("BO-dır", "to annoy; to make an effort", "Don't <b>bother</b> him while he's working."),
 "within": ("uid-İN", "inside; before the end of", "Please reply <b>within</b> three days."),
 "commit": ("kı-MİT", "to do a crime; to promise", "He would never <b>commit</b> a crime."),
 "improvement": ("im-PRUV-mınt", "the act of getting better", "There has been a big <b>improvement</b> in her health."),
 "economy": ("i-KO-nı-mi", "the money and business of a country", "The country's <b>economy</b> is growing."),
 "rare": ("RE-ır", "not common; unusual", "This is a <b>rare</b> kind of bird."),
 "solid": ("SO-lid", "hard and firm; not liquid", "Ice is water in a <b>solid</b> form."),
 "poverty": ("PO-vır-ti", "the state of being poor", "Many families live in <b>poverty</b>."),
 "similarly": ("Sİ-mı-lı-li", "in a similar way", "The two plans are <b>similarly</b> priced."),
 "departure": ("di-PAR-çır", "the act of leaving", "The <b>departure</b> of the train was delayed."),
 "necessarily": ("ne-sı-SE-rı-li", "as a certain result; always", "Expensive things are not <b>necessarily</b> better."),
 "live": ("LAYV", "to be alive; happening now", "We watched the concert <b>live</b> on TV."),
 "frightened": ("FRAY-tınd", "feeling afraid", "She was <b>frightened</b> by the thunder."),
 "leather": ("LE-dır", "material made from animal skin", "He carried a <b>leather</b> bag."),
 "underwear": ("AN-dır-ue-ır", "clothes worn under other clothes", "She packed clean <b>underwear</b> for the trip."),
 "candidate": ("KEN-di-deyt", "a person who applies for a job or election", "There are three <b>candidates</b> for the job."),
 "definition": ("de-fi-Nİ-şın", "the meaning of a word", "Look up the <b>definition</b> in the dictionary."),
 "seed": ("SİİD", "a small part of a plant that grows into a new one", "Plant the <b>seeds</b> in the spring."),
 "unemployment": ("an-im-PLOY-mınt", "the state of having no job", "<b>Unemployment</b> has risen this year."),
 "valuable": ("VEL-yu-bıl", "worth a lot; very useful", "The ring is very <b>valuable</b>."),
 "annoying": ("ı-NO-ying", "making you a little angry", "The dripping tap is very <b>annoying</b>."),
 "princess": ("PRİN-ses", "the daughter of a king or queen", "The <b>princess</b> wore a golden crown."),
 "shy": ("ŞAY", "nervous with other people", "He is too <b>shy</b> to speak in public."),
 "duty": ("DYU-ti", "something you must do; a tax", "It is a nurse's <b>duty</b> to care for patients."),
 "IT": ("ay-Tİİ", "information technology; computers", "She works in <b>IT</b> at a big company."),
 "prisoner": ("PRİZ-nır", "a person kept in prison", "The <b>prisoner</b> was released after five years."),
 "strength": ("STRENKT", "the quality of being strong", "He lifted the box with great <b>strength</b>."),
 "hire": ("HA-yır", "to pay to use; to employ", "We can <b>hire</b> a car at the airport."),
 "mainly": ("MEYN-li", "mostly", "The crowd was <b>mainly</b> young people."),
 "horror": ("HO-rır", "a feeling of great fear", "She screamed in <b>horror</b>."),
 "decorate": ("DE-kı-reyt", "to make something look nice", "We <b>decorate</b> the tree at New Year."),
 "directly": ("day-REKT-li", "in a straight way; at once", "The bus goes <b>directly</b> to the centre."),
 "contrast": ("KON-trast", "a clear difference", "There is a big <b>contrast</b> between the two cities."),
 "stuff": ("STAF", "things (informal)", "Put your <b>stuff</b> in the cupboard."),
 "explore": ("iks-PLOR", "to travel and discover; to examine", "They went to <b>explore</b> the old town."),
 "concentrate": ("KON-sınt-reyt", "to give all your attention", "I can't <b>concentrate</b> with the TV on."),
 "standard": ("STEN-dırd", "a level of quality; usual", "The hotel offers a high <b>standard</b> of service."),
 "container": ("kın-TEY-nır", "an object for holding things", "Put the rice in a plastic <b>container</b>."),
 "accommodation": ("ı-ko-mı-DEY-şın", "a place to stay", "The price includes <b>accommodation</b>."),
 "connection": ("kı-NEK-şın", "a link between things", "There is a <b>connection</b> between smoking and illness."),
 "diagram": ("DA-yıg-rem", "a simple drawing that explains something", "The <b>diagram</b> shows how the machine works."),
 "flag": ("FLEG", "a piece of cloth that is a symbol of a country", "The <b>flag</b> flew above the building."),
 "brave": ("BREYV", "not afraid of danger", "The <b>brave</b> firefighter saved the child."),
 "chapter": ("ÇEP-tır", "a section of a book", "I read the first <b>chapter</b> last night."),
 "aware": ("ı-UE-ır", "knowing about something", "Are you <b>aware</b> of the risks?"),
 "kiss": ("KİS", "to touch with the lips as a sign of love", "She gave her son a <b>kiss</b>."),
 "enemy": ("E-nı-mi", "a person who wishes you harm", "The two countries were <b>enemies</b>."),
 "attitude": ("E-ti-tyud", "a way of thinking or feeling", "She has a positive <b>attitude</b>."),
 "difficulty": ("Dİ-fi-kıl-ti", "the state of being hard; a problem", "He had <b>difficulty</b> opening the jar."),
 "fur": ("FÖR", "the soft hair on an animal", "The cat has soft grey <b>fur</b>."),
 "eventually": ("i-VEN-çu-ı-li", "in the end; after a long time", "We <b>eventually</b> found the house."),
 "sculpture": ("SKALP-çır", "a piece of art made from stone or metal", "There is a marble <b>sculpture</b> in the park."),
 "engineering": ("en-ci-Nİ-ring", "the work of designing machines and structures", "He studies <b>engineering</b> at university."),
 "pray": ("PREY", "to speak to a god", "They <b>pray</b> five times a day."),
 "intend": ("in-TEND", "to plan to do something", "I <b>intend</b> to study medicine."),
 "plenty": ("PLEN-ti", "a large amount; enough", "There is <b>plenty</b> of food for everyone."),
 "impression": ("im-PRE-şın", "an idea or feeling about something", "She made a good <b>impression</b> at the interview."),
 "ceremony": ("SE-rı-mı-ni", "a formal event for a special occasion", "The wedding <b>ceremony</b> was beautiful."),
 "chemical": ("KE-mi-kıl", "a substance used in chemistry", "Some <b>chemicals</b> are dangerous."),
 "muscle": ("MA-sıl", "a body part that helps you move", "Exercise makes your <b>muscles</b> stronger."),
 "lack": ("LEK", "the state of not having something", "The plant died from a <b>lack</b> of water."),
 "helicopter": ("HE-li-kop-tır", "an aircraft with turning blades on top", "A <b>helicopter</b> flew over the city."),
 "theirs": ("DE-ırz", "belonging to them", "This car is ours; that one is <b>theirs</b>."),
}
