# -*- coding: utf-8 -*-
# Grup 23 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 23
DATA = {
 "tube": ("TYUB", "a long hollow pipe; a soft container", "The paint comes in a <b>tube</b>."),
 "disappointing": ("di-sı-POYN-ting", "not as good as hoped", "The film was <b>disappointing</b>."),
 "treatment": ("TRİİT-mınt", "medical care; the way you deal with someone", "The new <b>treatment</b> cured the disease."),
 "addition": ("ı-Dİ-şın", "the act of adding; the sum", "In <b>addition</b> to tea, they served cakes."),
 "charge": ("ÇARC", "a price; to fill with electricity; an accusation", "There is no <b>charge</b> for children."),
 "luxury": ("LAK-şı-ri", "great comfort, usually expensive", "They stayed in a <b>luxury</b> hotel."),
 "whether": ("UE-dır", "used to show a choice or doubt", "I don't know <b>whether</b> to stay or go."),
 "involved": ("in-VOLVD", "taking part; connected", "Many people were <b>involved</b> in the project."),
 "fascinating": ("FE-si-ney-ting", "extremely interesting", "The book about space is <b>fascinating</b>."),
 "waste": ("UEYST", "to use badly; unwanted material", "Don't <b>waste</b> water."),
 "captain": ("KEP-tin", "the leader of a team or ship", "The <b>captain</b> steered the ship."),
 "script": ("SKRİPT", "the written words of a play or film", "The actor learned his <b>script</b>."),
 "comparison": ("kım-PE-ri-sın", "the act of comparing", "There is no <b>comparison</b> between the two."),
 "election": ("i-LEK-şın", "the process of choosing by voting", "The <b>election</b> will be held in June."),
 "grain": ("GREYN", "the seeds of food plants like wheat; a tiny piece", "Bread is made from <b>grain</b>."),
 "profit": ("PRO-fit", "money gained in business", "The shop made a good <b>profit</b> this year."),
 "convenient": ("kın-Vİİ-ni-ınt", "easy to use; suitable", "The shop is in a <b>convenient</b> location."),
 "reference": ("REF-rıns", "a mention; a source of information", "The book has a list of <b>references</b>."),
 "pressure": ("PRE-şır", "the force of pushing; stress", "He is under a lot of <b>pressure</b> at work."),
 "highlight": ("HAY-layt", "to draw attention to; the best part", "The teacher <b>highlighted</b> the key words."),
 "label": ("LEY-bıl", "a piece of paper giving information", "Read the <b>label</b> before you take the medicine."),
 "collection": ("kı-LEK-şın", "a group of things gathered together", "He has a large stamp <b>collection</b>."),
 "till": ("TİL", "until; a cash drawer in a shop", "Wait <b>till</b> I come back."),
 "admit": ("ıd-MİT", "to agree that something is true; to let in", "He <b>admitted</b> his mistake."),
 "revise": ("ri-VAYZ", "to study again; to change", "I need to <b>revise</b> for the test."),
 "honest": ("O-nist", "truthful; not lying", "She is an <b>honest</b> person."),
 "editor": ("E-di-tır", "a person who prepares texts for publishing", "The <b>editor</b> corrected the article."),
 "regularly": ("RE-gyu-lı-li", "at even times; often", "He exercises <b>regularly</b>."),
 "official": ("ı-Fİ-şıl", "approved by authority; a person in office", "This is the <b>official</b> website."),
 "approximately": ("ıp-ROK-si-mıt-li", "about; roughly", "The trip takes <b>approximately</b> two hours."),
 "drum": ("DRAM", "a musical instrument you hit", "He plays the <b>drum</b> in a band."),
 "perfectly": ("PÖR-fikt-li", "in a perfect way; completely", "The plan worked <b>perfectly</b>."),
 "dressed": ("DREST", "wearing clothes", "She got <b>dressed</b> quickly."),
 "arrest": ("ı-REST", "to take to a police station", "The police will <b>arrest</b> the thief."),
 "favour": ("FEY-vır", "a kind act; support", "Can you do me a <b>favour</b>?"),
 "challenge": ("ÇE-linc", "a difficult task; to question", "Learning a language is a <b>challenge</b>."),
 "bee": ("Bİİ", "an insect that makes honey", "A <b>bee</b> landed on the flower."),
 "highly": ("HAY-li", "very; to a high degree", "She is a <b>highly</b> skilled doctor."),
 "intention": ("in-TEN-şın", "a plan to do something", "It was not my <b>intention</b> to hurt you."),
 "wonder": ("UAN-dır", "to want to know; a feeling of surprise", "I <b>wonder</b> what time it is."),
 "encourage": ("in-KA-ric", "to give hope or support", "My teacher <b>encouraged</b> me to try again."),
 "punishment": ("PA-niş-mınt", "something done to a person for doing wrong", "The <b>punishment</b> was a large fine."),
 "punish": ("PA-niş", "to make someone suffer for doing wrong", "Parents should not <b>punish</b> children harshly."),
 "package": ("PE-kic", "a wrapped parcel; a set of things", "A <b>package</b> arrived in the post."),
 "destination": ("des-ti-NEY-şın", "the place you are going to", "Our final <b>destination</b> was Rome."),
 "achievement": ("ı-ÇİİV-mınt", "something done successfully", "Winning the prize was a great <b>achievement</b>."),
 "sex": ("SEKS", "being male or female", "Please write your name and <b>sex</b> on the form."),
 "worldwide": ("uörld-UAYD", "in all parts of the world", "The company has offices <b>worldwide</b>."),
 "property": ("PRO-pır-ti", "something you own; land and buildings", "The house is his personal <b>property</b>."),
 "keyboard": ("Kİİ-bord", "the set of keys on a computer or piano", "I typed the letter on my <b>keyboard</b>."),
 "path": ("PAT", "a narrow way for walking", "We followed the <b>path</b> to the lake."),
 "clause": ("KLOZ", "a part of a sentence; a section of a document", "This <b>clause</b> explains the rules."),
 "bank (river)": ("BENK", "the land along the side of a river", "We sat on the <b>bank</b> of the river."),
 "fence": ("FENS", "a barrier around a field or garden", "The dog jumped over the <b>fence</b>."),
 "fairly": ("FE-ır-li", "quite; in a just way", "The test was <b>fairly</b> easy."),
 "safety": ("SEYF-ti", "the state of being safe", "Wear a helmet for your <b>safety</b>."),
 "balance": ("BE-lıns", "a steady position; equal amounts", "She lost her <b>balance</b> and fell."),
 "tent": ("TENT", "a shelter made of cloth for camping", "We slept in a <b>tent</b> by the lake."),
 "flood": ("FLAD", "a large amount of water over land", "The <b>flood</b> destroyed many homes."),
 "combine": ("kım-BAYN", "to join together", "<b>Combine</b> the flour and the eggs."),
 "value": ("VEL-yu", "the worth of something", "The <b>value</b> of the house has risen."),
 "graduate": ("GRE-cu-ıt", "a person who has finished a degree", "She is a <b>graduate</b> of Oxford."),
 "grade": ("GREYD", "a mark for school work; a level", "He got a good <b>grade</b> in maths."),
 "secondary": ("SE-kınd-ri", "less important; after primary (school)", "He goes to a <b>secondary</b> school."),
 "engaged": ("in-GEYCD", "having agreed to marry; busy", "They got <b>engaged</b> last month."),
 "examine": ("ig-ZE-min", "to look at carefully", "The doctor will <b>examine</b> the patient."),
 "qualified": ("KUO-li-fayd", "having the right training or skills", "She is a <b>qualified</b> nurse."),
 "function": ("FANK-şın", "the purpose or use of something", "The <b>function</b> of the heart is to pump blood."),
 "possibly": ("PO-sıb-li", "perhaps; maybe", "He is <b>possibly</b> the best player in the team."),
 "length": ("LENKT", "how long something is", "What is the <b>length</b> of the room?"),
 "campus": ("KEM-pıs", "the grounds of a university", "The library is in the centre of the <b>campus</b>."),
 "smart": ("SMART", "clever; neat and tidy", "That's a <b>smart</b> idea."),
 "attach": ("ı-TEÇ", "to join or fix to something", "Please <b>attach</b> the file to your email."),
 "horrible": ("HO-rı-bıl", "very unpleasant; terrible", "The weather was <b>horrible</b> all week."),
 "currently": ("KA-rınt-li", "at the present time", "She is <b>currently</b> living in Ankara."),
 "leisure": ("LE-jır", "free time", "He spends his <b>leisure</b> time fishing."),
 "occur": ("ı-KÖR", "to happen", "Accidents often <b>occur</b> on this road."),
 "mystery": ("MİS-tri", "something that is hard to explain", "The cause of the fire is a <b>mystery</b>."),
 "servant": ("SÖR-vınt", "a person who works in someone's house", "The <b>servant</b> opened the door."),
 "confirm": ("kın-FÖRM", "to say that something is true or certain", "Please <b>confirm</b> your booking."),
 "historic": ("his-TO-rik", "important in history", "It was a <b>historic</b> moment for the country."),
 "grateful": ("GREYT-fıl", "feeling thankful", "I'm very <b>grateful</b> for your help."),
 "silly": ("Sİ-li", "not sensible; foolish", "Don't be <b>silly</b>; of course you can do it."),
 "lip": ("LİP", "one of the two soft edges of the mouth", "She bit her <b>lip</b> nervously."),
 "though": ("DOU", "in spite of the fact; however", "<b>Though</b> it was late, they kept working."),
 "injured": ("İN-cırd", "hurt or harmed", "Two people were <b>injured</b> in the crash."),
 "rarely": ("RE-ır-li", "not often", "She <b>rarely</b> eats meat."),
 "suitable": ("SU-tı-bıl", "right for a purpose", "This film is not <b>suitable</b> for children."),
 "historical": ("his-TO-ri-kıl", "relating to the past", "The museum has many <b>historical</b> objects."),
 "ignore": ("ig-NOR", "to pay no attention to", "Don't <b>ignore</b> the warning signs."),
 "export": ("EKS-port", "goods sold abroad; to send abroad", "Coffee is the country's main <b>export</b>."),
 "illegal": ("i-LİİG-ıl", "against the law", "It is <b>illegal</b> to park here."),
 "weapon": ("UE-pın", "an object used to fight or attack", "The knife was used as a <b>weapon</b>."),
 "happiness": ("HE-pi-nıs", "the feeling of being happy", "Money can't buy <b>happiness</b>."),
 "frame": ("FREYM", "a border around a picture; a structure", "She put the photo in a wooden <b>frame</b>."),
 "effort": ("E-fırt", "hard work; an attempt", "He passed the exam with a lot of <b>effort</b>."),
 "quote": ("KUOUT", "to repeat someone's words; a price offer", "She likes to <b>quote</b> famous writers."),
 "gentleman": ("CEN-tıl-mın", "a polite word for a man", "A <b>gentleman</b> held the door open for me."),
 "locate": ("lou-KEYT", "to find the position of", "We couldn't <b>locate</b> the hotel on the map."),
 "setting": ("SE-ting", "the place where something happens; an adjustment", "The <b>setting</b> of the film is a small village."),
}
