# -*- coding: utf-8 -*-
# Grup 24 (B1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 24
DATA = {
 "leaf": ("LİİF", "the flat green part of a plant", "A yellow <b>leaf</b> fell from the tree."),
 "tyre": ("TA-yır", "the rubber ring around a wheel", "The car had a flat <b>tyre</b>."),
 "primary": ("PRAY-mı-ri", "most important; first (school)", "Health is of <b>primary</b> importance."),
 "donate": ("dou-NEYT", "to give money or things to help", "They <b>donate</b> old clothes to charity."),
 "talent": ("TE-lınt", "a natural skill", "She has a real <b>talent</b> for singing."),
 "mud": ("MAD", "soft wet earth", "The children played in the <b>mud</b>."),
 "rope": ("ROUP", "thick strong cord", "They tied the boat with a <b>rope</b>."),
 "qualification": ("kuo-li-fi-KEY-şın", "an exam or skill that makes you able to do a job", "She has the right <b>qualifications</b> for the job."),
 "iron": ("A-yın", "a hard metal; a tool for pressing clothes", "The gate is made of <b>iron</b>."),
 "similarity": ("si-mı-LE-rı-ti", "the state of being alike", "There is a <b>similarity</b> between the two brothers."),
 "environmental": ("in-vay-rın-MEN-tıl", "relating to the natural world", "Pollution is a serious <b>environmental</b> problem."),
 "used": ("YUST", "not new; familiar with", "I'm not <b>used</b> to getting up early."),
 "cotton": ("KO-tın", "a soft white plant fibre used for cloth", "This shirt is made of <b>cotton</b>."),
 "bend": ("BEND", "to make something curved; a curve", "<b>Bend</b> your knees when you lift the box."),
 "properly": ("PRO-pı-li", "correctly; in the right way", "Close the door <b>properly</b>."),
 "relaxed": ("ri-LEKST", "calm and not worried", "He felt <b>relaxed</b> on holiday."),
 "participate": ("par-Tİ-si-peyt", "to take part in", "All students can <b>participate</b> in the contest."),
 "entertain": ("en-tır-TEYN", "to amuse people; to have guests", "The clown <b>entertained</b> the children."),
 "passion": ("PE-şın", "a very strong feeling; a great love for something", "Music is her <b>passion</b>."),
 "define": ("di-FAYN", "to explain the meaning of", "Can you <b>define</b> this word?"),
 "performance": ("pır-FOR-mıns", "a show; how well someone does", "The team's <b>performance</b> was excellent."),
 "influence": ("İN-flu-ıns", "the power to affect someone", "Friends have a big <b>influence</b> on us."),
 "portrait": ("POR-trıt", "a picture of a person", "The artist painted a <b>portrait</b> of the queen."),
 "album": ("EL-bım", "a collection of songs or photos", "The band released a new <b>album</b>."),
 "effectively": ("i-FEK-tiv-li", "in a way that works well", "She managed the team <b>effectively</b>."),
 "translation": ("trenz-LEY-şın", "words changed into another language", "I read an English <b>translation</b> of the novel."),
 "specifically": ("spı-Sİ-fik-li", "in a particular way; exactly", "This book is written <b>specifically</b> for beginners."),
 "apart": ("ı-PART", "separated by distance", "The two houses are far <b>apart</b>."),
 "fold": ("FOULD", "to bend so one part covers another", "<b>Fold</b> the paper in half."),
 "custom": ("KAS-tım", "a traditional way of doing things", "Shaking hands is a common <b>custom</b>."),
 "nail": ("NEYL", "a thin metal pin; the hard part on a finger", "Hammer the <b>nail</b> into the wood."),
 "roll": ("ROUL", "to move by turning over; a tube shape", "The ball <b>rolled</b> under the table."),
 "dislike": ("dis-LAYK", "to not like", "I <b>dislike</b> waiting in long queues."),
 "qualify": ("KUO-li-fay", "to reach the needed level; to gain the right", "She <b>qualified</b> as a doctor last year."),
 "trade": ("TREYD", "the buying and selling of goods", "There is a lot of <b>trade</b> between the two countries."),
 "ban": ("BEN", "to officially forbid; a rule against", "The school will <b>ban</b> mobile phones."),
 "fancy": ("FEN-si", "decorated; to want or like", "She wore a <b>fancy</b> dress to the party."),
 "spot": ("SPOT", "a small mark; a place; to notice", "There is a <b>spot</b> of ink on the page."),
 "spread": ("SPRED", "to open out; to reach more places", "The fire <b>spread</b> quickly."),
 "ghost": ("GOUST", "the spirit of a dead person", "The old house is said to have a <b>ghost</b>."),
 "summarize": ("SA-mı-rayz", "to give the main points shortly", "Please <b>summarize</b> the article in one paragraph."),
 "announce": ("ı-NAUNS", "to tell people officially", "They will <b>announce</b> the winner tonight."),
 "incredibly": ("in-KRE-dıb-li", "extremely; hard to believe", "The test was <b>incredibly</b> difficult."),
 "statue": ("STE-çu", "a model of a person made of stone or metal", "There is a <b>statue</b> of a soldier in the square."),
 "percentage": ("pır-SEN-tic", "an amount out of a hundred", "A large <b>percentage</b> of students pass."),
 "commercial": ("kı-MÖR-şıl", "relating to business; a TV advert", "The area has many <b>commercial</b> buildings."),
 "kick": ("KİK", "to hit with your foot", "He <b>kicked</b> the ball into the goal."),
 "medium": ("Mİİ-di-ım", "in the middle; average", "I'd like a <b>medium</b> coffee, please."),
 "aim": ("EYM", "a goal; to point at", "Our <b>aim</b> is to finish by Friday."),
 "prove": ("PRUV", "to show that something is true", "Can you <b>prove</b> that you were at home?"),
 "unemployed": ("an-im-PLOYD", "not having a job", "He has been <b>unemployed</b> for six months."),
 "simply": ("SİMP-li", "in an easy way; just", "<b>Simply</b> add water and stir."),
 "reaction": ("ri-EK-şın", "a response to something", "Her <b>reaction</b> to the news was surprise."),
 "sample": ("SAM-pıl", "a small part that shows the whole", "The nurse took a blood <b>sample</b>."),
 "volunteer": ("vo-lın-Tİ-ır", "a person who works without pay", "She works as a <b>volunteer</b> at the hospital."),
 "remain": ("ri-MEYN", "to stay; to be left", "Please <b>remain</b> in your seats."),
 "laboratory": ("lı-BO-rıt-ri", "a room for scientific work", "The samples were tested in a <b>laboratory</b>."),
 "successfully": ("sık-SES-fı-li", "in a way that succeeds", "She <b>successfully</b> passed all her exams."),
 "imaginary": ("i-ME-ci-nı-ri", "not real; existing only in the mind", "The child has an <b>imaginary</b> friend."),
 "theory": ("Tİ-ı-ri", "an idea that explains something", "He has a <b>theory</b> about why birds sing."),
 "obviously": ("OB-vi-ıs-li", "clearly; as anyone can see", "She was <b>obviously</b> very tired."),
 "diamond": ("DA-yı-mınd", "a very hard, valuable clear stone", "The ring has a large <b>diamond</b>."),
 "intelligence": ("in-TE-li-cıns", "the ability to learn and think; secret information", "Dolphins have great <b>intelligence</b>."),
 "tend": ("TEND", "to usually do something", "I <b>tend</b> to wake up early."),
 "journal": ("CÖR-nıl", "a serious magazine; a daily record", "She writes in her <b>journal</b> every night."),
 "court": ("KORT", "a place where legal cases are heard; a sports area", "The case went to <b>court</b>."),
 "resource": ("ri-ZORS", "something useful you can use", "Water is a valuable <b>resource</b>."),
 "tail": ("TEYL", "the part at the back of an animal", "The dog wagged its <b>tail</b>."),
 "damage": ("DE-mic", "harm to something; to harm", "The storm caused a lot of <b>damage</b>."),
 "previous": ("PRİİ-vi-ıs", "coming before", "In the <b>previous</b> lesson, we studied verbs."),
 "retire": ("ri-TA-yır", "to stop working because of age", "He plans to <b>retire</b> at sixty-five."),
 "proud": ("PRAUD", "feeling pleased about something you did", "She was <b>proud</b> of her exam results."),
 "kind (caring)": ("KAYND", "gentle and caring towards others", "It was <b>kind</b> of you to help."),
 "cottage": ("KO-tic", "a small house in the countryside", "They spent the weekend in a <b>cottage</b>."),
 "arrival": ("ı-RAY-vıl", "the act of arriving", "We waited for the <b>arrival</b> of the train."),
 "attraction": ("ıt-REK-şın", "something that pulls interest", "The castle is a popular tourist <b>attraction</b>."),
 "assist": ("ı-SİST", "to help", "A nurse will <b>assist</b> the doctor."),
 "relative": ("RE-lı-tiv", "a family member; compared to something else", "Many <b>relatives</b> came to the wedding."),
 "originally": ("ı-Rİ-cı-nı-li", "at first; in the beginning", "The house was <b>originally</b> a school."),
 "remote": ("ri-MOUT", "far away; distant", "They live in a <b>remote</b> village."),
 "surface": ("SÖR-fis", "the top or outer part", "The <b>surface</b> of the lake was calm."),
 "employment": ("im-PLOY-mınt", "the state of having a job", "She is looking for <b>employment</b>."),
 "currency": ("KA-rın-si", "the money used in a country", "The <b>currency</b> of Japan is the yen."),
 "marriage": ("ME-ric", "the state of being married", "Their <b>marriage</b> has lasted thirty years."),
 "signal": ("SİG-nıl", "a sign that gives information", "The green light is a <b>signal</b> to go."),
 "lay": ("LEY", "to put down carefully", "<b>Lay</b> the baby on the bed."),
 "mix": ("MİKS", "to combine things together", "<b>Mix</b> the sugar and the butter."),
 "occasion": ("ı-KEY-jın", "a special event; a time when something happens", "A wedding is a happy <b>occasion</b>."),
 "chest": ("ÇEST", "the front of the body; a large strong box", "He felt a pain in his <b>chest</b>."),
 "consumer": ("kın-SYU-mır", "a person who buys goods", "<b>Consumers</b> want lower prices."),
 "conclude": ("kın-KLUD", "to end; to decide after thinking", "The judge will <b>conclude</b> the case today."),
 "technical": ("TEK-ni-kıl", "relating to skills or machines", "The report is full of <b>technical</b> words."),
 "tin": ("TİN", "a metal container; a soft metal", "She opened a <b>tin</b> of beans."),
 "hardly": ("HARD-li", "almost not", "I can <b>hardly</b> hear you."),
 "shelf": ("ŞELF", "a flat board for holding things", "Put the books on the <b>shelf</b>."),
 "prediction": ("pri-DİK-şın", "a statement about what will happen", "Her <b>prediction</b> about the weather was correct."),
 "reliable": ("ri-LA-yı-bıl", "able to be trusted", "He is a <b>reliable</b> worker."),
 "needle": ("NİİD-ıl", "a thin pointed tool for sewing", "She threaded the <b>needle</b> carefully."),
 "bride": ("BRAYD", "a woman on her wedding day", "The <b>bride</b> wore a white dress."),
}
