# -*- coding: utf-8 -*-
# Grup 25 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 25
DATA = {
 "wire": ("UA-yır", "a thin thread of metal", "The fence is made of <b>wire</b>."),
 "feedback": ("FİİD-bek", "comments about how well something is done", "The teacher gave helpful <b>feedback</b>."),
 "sympathy": ("SİM-pı-ti", "understanding of another's sadness", "She felt <b>sympathy</b> for the poor family."),
 "willing": ("Uİ-ling", "ready and happy to do something", "He is <b>willing</b> to help us."),
 "sponsor": ("SPON-sır", "a company that pays for an event; to pay for", "A local bank will <b>sponsor</b> the team."),
 "fund": ("FAND", "an amount of money for a purpose; to pay for", "They started a <b>fund</b> for the new hospital."),
 "barrier": ("BE-ri-ır", "something that blocks the way", "Language can be a <b>barrier</b> to communication."),
 "operate": ("O-pı-reyt", "to make work; to do surgery", "Do you know how to <b>operate</b> this machine?"),
 "passage": ("PE-sic", "a section of a text; a narrow way", "Read the following <b>passage</b> and answer."),
 "pupil": ("PYU-pıl", "a student at school; the dark centre of the eye", "Every <b>pupil</b> must wear a uniform."),
 "external": ("iks-TÖR-nıl", "on the outside", "Apply the cream to the <b>external</b> skin only."),
 "constant": ("KON-stınt", "happening all the time; not changing", "There was a <b>constant</b> noise from the road."),
 "parliament": ("PAR-lı-mınt", "the group that makes a country's laws", "The <b>parliament</b> passed a new law."),
 "split": ("SPLİT", "to divide into parts", "Let's <b>split</b> the bill."),
 "tear": ("TE-ır", "to pull apart; a drop from the eye", "Be careful not to <b>tear</b> the paper."),
 "combination": ("kom-bi-NEY-şın", "a mix of two or more things", "The dish is a <b>combination</b> of sweet and sour."),
 "permanent": ("PÖR-mı-nınt", "lasting for a very long time", "She found a <b>permanent</b> job."),
 "broad": ("BROD", "wide; covering a lot", "The river is very <b>broad</b> here."),
 "detect": ("di-TEKT", "to discover or notice", "The alarm can <b>detect</b> smoke."),
 "matching": ("ME-çing", "going well together; the same", "She wore a hat and <b>matching</b> gloves."),
 "institution": ("ins-ti-TYU-şın", "a large important organization", "A bank is a financial <b>institution</b>."),
 "soul": ("SOUL", "the spirit of a person", "Music touches the <b>soul</b>."),
 "criticism": ("KRİ-ti-si-zım", "the act of finding fault", "He couldn't accept the <b>criticism</b>."),
 "purchase": ("PÖR-çıs", "the act of buying; to buy", "Keep the receipt for your <b>purchase</b>."),
 "inform": ("in-FORM", "to tell someone about something", "Please <b>inform</b> me of any changes."),
 "significantly": ("sig-Nİ-fi-kınt-li", "in an important way; by a large amount", "Sales rose <b>significantly</b> this year."),
 "submit": ("sıb-MİT", "to give something for a decision", "You must <b>submit</b> the form by Friday."),
 "dramatic": ("drı-ME-tik", "sudden and noticeable; exciting", "There was a <b>dramatic</b> change in the weather."),
 "publication": ("pab-li-KEY-şın", "the act of publishing; a book or magazine", "The <b>publication</b> of her novel made her famous."),
 "prospect": ("PROS-pekt", "a chance that something will happen", "There is little <b>prospect</b> of rain."),
 "rapid": ("RE-pid", "very fast", "The city has seen <b>rapid</b> growth."),
 "rapidly": ("RE-pid-li", "very quickly", "The technology is changing <b>rapidly</b>."),
 "surgery": ("SÖR-cı-ri", "a medical operation; a doctor's office", "He needs <b>surgery</b> on his knee."),
 "organ": ("OR-gın", "a body part with a special job; a large instrument", "The heart is an important <b>organ</b>."),
 "interrupt": ("in-tı-RAPT", "to stop someone while they are speaking", "Please don't <b>interrupt</b> me."),
 "conscious": ("KON-şıs", "awake and aware", "The patient is now <b>conscious</b>."),
 "slip": ("SLİP", "to slide and lose balance; a small mistake", "Be careful not to <b>slip</b> on the ice."),
 "regard": ("ri-GARD", "to think of in a certain way; respect", "I <b>regard</b> her as a good friend."),
 "consistent": ("kın-SİS-tınt", "staying the same; steady", "She is a <b>consistent</b> worker."),
 "constantly": ("KON-stınt-li", "all the time; again and again", "He is <b>constantly</b> late."),
 "confidence": ("KON-fi-dıns", "belief in yourself; trust", "Speaking in public gives you <b>confidence</b>."),
 "unknown": ("an-NOUN", "not known", "The cause of the fire is still <b>unknown</b>."),
 "stream": ("STRİİM", "a small river; a flow", "The children played in the <b>stream</b>."),
 "perspective": ("pır-SPEK-tiv", "a way of thinking about something", "Try to see it from my <b>perspective</b>."),
 "saving": ("SEY-ving", "a reduction; money kept", "Buying in bulk is a big <b>saving</b>."),
 "conflict": ("KON-flikt", "a serious disagreement; a fight", "There was a <b>conflict</b> between the two groups."),
 "inch": ("İNÇ", "a unit of length (about 2.5 cm)", "The nail is one <b>inch</b> long."),
 "slave": ("SLEYV", "a person owned and forced to work", "In the past, many people were <b>slaves</b>."),
 "participant": ("par-Tİ-si-pınt", "a person who takes part", "Each <b>participant</b> received a medal."),
 "agenda": ("ı-CEN-dı", "a list of things to discuss", "The first item on the <b>agenda</b> is money."),
 "incident": ("İN-si-dınt", "an event, often unpleasant", "The police reported the <b>incident</b>."),
 "ultimately": ("AL-ti-mıt-li", "in the end; finally", "<b>Ultimately</b>, the choice is yours."),
 "dishonest": ("dis-O-nist", "not truthful", "It was <b>dishonest</b> of him to lie."),
 "bush": ("BUŞ", "a small low plant with many branches", "A bird hid in the <b>bush</b>."),
 "aircraft": ("E-ır-kraft", "a vehicle that flies, like a plane", "The <b>aircraft</b> landed safely."),
 "critic": ("KRİ-tik", "a person who judges books, films and so on", "The <b>critic</b> praised the new film."),
 "heaven": ("HE-vın", "the place where good people go after death", "They believe in <b>heaven</b>."),
 "increasingly": ("in-KRİİ-sing-li", "more and more", "It is becoming <b>increasingly</b> difficult to find work."),
 "resolve": ("ri-ZOLV", "to solve a problem; to decide firmly", "They tried to <b>resolve</b> the argument."),
 "strict": ("STRİKT", "expecting rules to be obeyed", "Our teacher is very <b>strict</b>."),
 "largely": ("LARC-li", "mostly", "The success was <b>largely</b> due to hard work."),
 "associate": ("ı-SOU-şi-eyt", "to connect in your mind; a work partner", "We <b>associate</b> summer with holidays."),
 "entirely": ("in-TA-yır-li", "completely", "I <b>entirely</b> agree with you."),
 "opposition": ("o-pı-Zİ-şın", "strong disagreement; the other side", "There was a lot of <b>opposition</b> to the plan."),
 "suspect": ("SAS-pekt", "to think someone is guilty; a person thought guilty", "The police <b>suspect</b> him of theft."),
 "mission": ("Mİ-şın", "an important task or journey", "Their <b>mission</b> was to find clean water."),
 "obligation": ("ob-li-GEY-şın", "something you must do", "You are under no <b>obligation</b> to buy."),
 "vision": ("Vİ-jın", "the ability to see; a plan for the future", "The leader had a clear <b>vision</b>."),
 "mineral": ("Mİ-nı-rıl", "a natural substance found in the ground", "Milk is rich in <b>minerals</b>."),
 "widely": ("UAYD-li", "by many people; over a large area", "The book is <b>widely</b> read."),
 "impressed": ("im-PREST", "feeling admiration", "I was very <b>impressed</b> by her speech."),
 "urge": ("ÖRC", "to strongly advise; a strong wish", "Doctors <b>urge</b> people to eat less sugar."),
 "mysterious": ("mis-Tİ-ri-ıs", "hard to explain or understand", "A <b>mysterious</b> light appeared in the sky."),
 "rub": ("RAB", "to move your hand over a surface with pressure", "She <b>rubbed</b> her tired eyes."),
 "advance": ("ıd-VANS", "to move forward; progress", "Science continues to <b>advance</b>."),
 "command": ("kı-MAND", "an order; to order", "The soldiers followed the <b>command</b>."),
 "lean": ("LİİN", "to bend or rest against; thin", "Don't <b>lean</b> on the door."),
 "wrap": ("REP", "to cover by folding paper or cloth around", "She <b>wrapped</b> the gift in blue paper."),
 "minor": ("MAY-nır", "small; not important", "It was only a <b>minor</b> problem."),
 "philosophy": ("fı-LO-sı-fi", "the study of ideas about life and knowledge", "He studied <b>philosophy</b> at university."),
 "executive": ("ig-ZEK-yu-tiv", "a senior manager", "She is a top <b>executive</b> at the company."),
 "pointed": ("POYN-tid", "having a sharp end", "The tool has a <b>pointed</b> tip."),
 "visual": ("Vİ-ju-ıl", "relating to seeing", "The film has amazing <b>visual</b> effects."),
 "shadow": ("ŞE-dou", "the dark shape made when light is blocked", "The tree cast a long <b>shadow</b>."),
 "wealthy": ("UEL-ti", "having a lot of money", "They are a <b>wealthy</b> family."),
 "draft": ("DRAFT", "an early version of a piece of writing", "This is only the first <b>draft</b> of my essay."),
 "threat": ("TRET", "a warning of harm; a danger", "Pollution is a <b>threat</b> to health."),
 "concept": ("KON-sept", "an idea", "Time is a difficult <b>concept</b> to explain."),
 "trust": ("TRAST", "belief that someone is honest; to believe in", "A good friendship is built on <b>trust</b>."),
 "wound": ("UUND", "an injury to the body", "The nurse cleaned the <b>wound</b>."),
 "contest": ("KON-test", "a competition", "She won the singing <b>contest</b>."),
 "approach": ("ıp-ROUÇ", "a way of doing something; to come near", "We need a new <b>approach</b> to the problem."),
 "scheme": ("SKİİM", "a plan; an organized system", "The government started a new housing <b>scheme</b>."),
 "phenomenon": ("fı-NO-mi-nın", "something that happens and can be seen", "Rainbows are a natural <b>phenomenon</b>."),
 "resident": ("RE-zi-dınt", "a person who lives in a place", "The <b>residents</b> complained about the noise."),
 "ensure": ("in-ŞOR", "to make certain", "Please <b>ensure</b> the door is locked."),
 "civil": ("Sİ-vıl", "relating to citizens; polite", "They fought for <b>civil</b> rights."),
 "labour": ("LEY-bır", "work, especially hard physical work", "The factory needs cheap <b>labour</b>."),
 "observe": ("ıb-ZÖRV", "to watch carefully; to notice", "Scientists <b>observe</b> the stars."),
 "approval": ("ıp-RU-vıl", "agreement that something is good", "The plan needs the manager's <b>approval</b>."),
}
