# -*- coding: utf-8 -*-
# Grup 26 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 26
DATA = {
 "moral": ("MO-rıl", "relating to right and wrong", "It's a <b>moral</b> question."),
 "investigation": ("in-ves-ti-GEY-şın", "the act of examining to find facts", "The police began an <b>investigation</b>."),
 "steady": ("STE-di", "firm; not changing", "Keep the ladder <b>steady</b>."),
 "rid": ("RİD", "to make free of something unwanted", "We must get <b>rid</b> of these old boxes."),
 "root": ("RUT", "the part of a plant under the ground; the cause", "The tree's <b>roots</b> are very deep."),
 "reserve": ("ri-ZÖRV", "to keep for later; to book", "I'd like to <b>reserve</b> a table for two."),
 "offensive": ("ı-FEN-siv", "rude or upsetting; attacking", "His joke was <b>offensive</b> to some people."),
 "loose": ("LUS", "not tight; free", "The screw is <b>loose</b>."),
 "dozen": ("DA-zın", "a group of twelve", "She bought a <b>dozen</b> eggs."),
 "elsewhere": ("els-UE-ır", "in or to another place", "If the shop is closed, we'll buy it <b>elsewhere</b>."),
 "wise": ("UAYZ", "having good judgement from experience", "It was a <b>wise</b> decision."),
 "construct": ("kın-STRAKT", "to build", "They will <b>construct</b> a bridge over the river."),
 "frequency": ("FRİİ-kuın-si", "how often something happens", "The <b>frequency</b> of storms has increased."),
 "edition": ("i-Dİ-şın", "a form of a book or magazine", "This is the latest <b>edition</b> of the dictionary."),
 "expose": ("iks-POUZ", "to leave without protection; to reveal", "Don't <b>expose</b> your skin to the sun for too long."),
 "therapy": ("TE-rı-pi", "treatment for an illness or problem", "She has <b>therapy</b> for her injured leg."),
 "criticize": ("KRİ-ti-sayz", "to say what is wrong with something", "Don't <b>criticize</b> him too harshly."),
 "elect": ("i-LEKT", "to choose by voting", "The people will <b>elect</b> a new leader."),
 "hollow": ("HO-lou", "empty inside", "The tree trunk was <b>hollow</b>."),
 "harm": ("HARM", "damage or injury; to hurt", "Too much sun can <b>harm</b> your skin."),
 "remark": ("ri-MARK", "something you say; a comment", "She made a kind <b>remark</b>."),
 "threaten": ("TRE-tın", "to say you will cause harm", "The dark clouds <b>threaten</b> rain."),
 "opponent": ("ı-POU-nınt", "a person you compete against", "He beat his <b>opponent</b> easily."),
 "distribution": ("dist-ri-BYU-şın", "the act of giving things out", "The <b>distribution</b> of food to the poor took days."),
 "critical": ("KRİ-ti-kıl", "finding fault; extremely important", "This is a <b>critical</b> moment."),
 "whisper": ("UİS-pır", "to speak very quietly", "She <b>whispered</b> the secret in my ear."),
 "concerned": ("kın-SÖRND", "worried; involved", "I'm <b>concerned</b> about his health."),
 "adopt": ("ı-DOPT", "to take as your own; to start using", "They decided to <b>adopt</b> a child."),
 "accuse": ("ı-KYUZ", "to say someone did something wrong", "Don't <b>accuse</b> me without proof."),
 "minister": ("Mİ-nis-tır", "a senior member of a government", "The <b>minister</b> announced new taxes."),
 "hell": ("HEL", "a place of punishment after death", "Some religions describe <b>hell</b> as full of fire."),
 "demand": ("di-MAND", "a firm request; a need for a product", "There is a high <b>demand</b> for houses."),
 "numerous": ("NYU-mı-rıs", "very many", "She has visited the city on <b>numerous</b> occasions."),
 "bacteria": ("bek-Tİ-ri-ı", "very small living things that can cause disease", "Soap kills many <b>bacteria</b>."),
 "proposal": ("prı-POU-zıl", "a plan or suggestion; an offer of marriage", "The committee accepted her <b>proposal</b>."),
 "generate": ("CE-nı-reyt", "to produce or create", "The wind farm <b>generates</b> electricity."),
 "afterwards": ("AF-tır-uıdz", "later; after that", "We had dinner and went for a walk <b>afterwards</b>."),
 "commission": ("kı-Mİ-şın", "money paid for selling; an official group", "The salesman earns a <b>commission</b> on each car."),
 "sweep": ("SUİİP", "to clean with a brush", "Please <b>sweep</b> the floor."),
 "relevant": ("RE-lı-vınt", "connected to the subject", "Is this information <b>relevant</b> to the case?"),
 "multiple": ("MAL-ti-pıl", "many; more than one", "The accident had <b>multiple</b> causes."),
 "scale": ("SKEYL", "the size or level; a tool for weighing", "The disaster happened on a large <b>scale</b>."),
 "permit": ("PÖR-mit", "an official document; to allow", "You need a <b>permit</b> to park here."),
 "contemporary": ("kın-TEMP-rı-ri", "modern; of the present time", "The gallery shows <b>contemporary</b> art."),
 "bet": ("BET", "to risk money on a result; to be sure", "I <b>bet</b> he will be late."),
 "significant": ("sig-Nİ-fi-kınt", "important; large enough to matter", "There was a <b>significant</b> rise in prices."),
 "unconscious": ("an-KON-şıs", "not awake; not aware", "The blow knocked him <b>unconscious</b>."),
 "cancel": ("KEN-sıl", "to stop a planned event", "We had to <b>cancel</b> the trip."),
 "plain": ("PLEYN", "simple; clear; a flat area of land", "She wore a <b>plain</b> white dress."),
 "popularity": ("pop-yu-LE-rı-ti", "the state of being liked by many", "The singer's <b>popularity</b> grew quickly."),
 "rubber": ("RA-bır", "a soft material used in tyres; an eraser", "The tyres are made of <b>rubber</b>."),
 "initial": ("i-Nİ-şıl", "first; at the beginning", "My <b>initial</b> reaction was surprise."),
 "ashamed": ("ı-ŞEYMD", "feeling guilt or embarrassment", "He was <b>ashamed</b> of his behaviour."),
 "recall": ("ri-KOL", "to remember; to call back", "I can't <b>recall</b> her name."),
 "consideration": ("kın-si-dı-REY-şın", "careful thought; a factor to think about", "After careful <b>consideration</b>, they said yes."),
 "tank": ("TENK", "a large container for liquid; a military vehicle", "The water <b>tank</b> is on the roof."),
 "internal": ("in-TÖR-nıl", "inside", "The car has an <b>internal</b> problem."),
 "outer": ("AU-tır", "on the outside", "Peel off the <b>outer</b> layer of the onion."),
 "concern": ("kın-SÖRN", "worry; to be about", "Her main <b>concern</b> is her children's safety."),
 "arise": ("ı-RAYZ", "to happen; to come up", "Problems may <b>arise</b> during the trip."),
 "enhance": ("in-HANS", "to improve or increase", "Good lighting can <b>enhance</b> a photo."),
 "protection": ("prı-TEK-şın", "keeping safe from harm", "Sun cream gives <b>protection</b> from the sun."),
 "nerve": ("NÖRV", "a body part that carries feelings; courage", "A <b>nerve</b> in his back was damaged."),
 "sequence": ("SİİK-uıns", "an ordered set of things", "Put the pictures in the right <b>sequence</b>."),
 "creation": ("kri-EY-şın", "the act of making something", "The <b>creation</b> of the park took two years."),
 "estimate": ("ES-ti-mıt", "a rough calculation; to guess an amount", "Can you <b>estimate</b> the cost?"),
 "adapt": ("ı-DEPT", "to change to fit a new situation", "Animals must <b>adapt</b> to survive."),
 "hesitate": ("HE-zi-teyt", "to pause before doing something", "Don't <b>hesitate</b> to ask for help."),
 "logical": ("LO-ci-kıl", "sensible; based on clear reasons", "That's a <b>logical</b> explanation."),
 "existence": ("ig-ZİS-tıns", "the state of existing", "The photo proves the animal's <b>existence</b>."),
 "sum": ("SAM", "a total; an amount of money", "The <b>sum</b> of two and three is five."),
 "justice": ("CAS-tis", "fair treatment; the law", "They demanded <b>justice</b> for the victim."),
 "proof": ("PRUF", "evidence that something is true", "Do you have any <b>proof</b>?"),
 "inner": ("İ-nır", "inside; central", "The <b>inner</b> part of the fruit is soft."),
 "nightmare": ("NAYT-me-ır", "a frightening dream; a very bad experience", "The child had a <b>nightmare</b>."),
 "agency": ("EY-cın-si", "a business that provides a service", "She found the job through an <b>agency</b>."),
 "owe": ("OU", "to have to pay back", "I <b>owe</b> you ten liras."),
 "beyond": ("bi-YOND", "on the far side of; more than", "The mountains lie <b>beyond</b> the river."),
 "delivery": ("di-Lİ-vı-ri", "the act of taking goods to a place", "The <b>delivery</b> arrived this morning."),
 "transfer": ("TRENS-för", "to move from one place to another", "She asked to <b>transfer</b> money to his account."),
 "declare": ("dik-LE-ır", "to state officially", "The government <b>declared</b> a holiday."),
 "demonstrate": ("DE-mınst-reyt", "to show clearly; to protest", "Let me <b>demonstrate</b> how it works."),
 "acknowledge": ("ık-NO-lic", "to accept that something is true", "He <b>acknowledged</b> his mistake."),
 "loan": ("LOUN", "money that is borrowed", "She took out a <b>loan</b> to buy a car."),
 "satisfied": ("SE-tis-fayd", "pleased because you got what you wanted", "The customers were <b>satisfied</b> with the service."),
 "emotional": ("i-MOU-şı-nıl", "relating to feelings; showing strong feelings", "It was an <b>emotional</b> goodbye."),
 "retain": ("ri-TEYN", "to keep", "The soil helps to <b>retain</b> water."),
 "complicated": ("KOMP-li-key-tid", "difficult to understand; complex", "The instructions are too <b>complicated</b>."),
 "deserve": ("di-ZÖRV", "to be worthy of", "You worked hard and <b>deserve</b> a rest."),
 "opening": ("OU-pı-ning", "a hole or gap; a beginning", "The cat went through an <b>opening</b> in the fence."),
 "procedure": ("prı-Sİİ-cır", "a set way of doing something", "Follow the correct <b>procedure</b>."),
 "enquiry": ("in-KUA-yı-ri", "a question or request for information", "I made an <b>enquiry</b> about the course."),
 "majority": ("mı-CO-rı-ti", "more than half", "The <b>majority</b> of people voted yes."),
 "imply": ("im-PLAY", "to suggest without saying directly", "Are you trying to <b>imply</b> that I'm wrong?"),
 "extend": ("iks-TEND", "to make longer or larger", "They plan to <b>extend</b> the road."),
 "commonly": ("KO-mın-li", "often; usually", "This plant is <b>commonly</b> found in gardens."),
 "silk": ("SİLK", "a soft, smooth cloth", "She wore a <b>silk</b> scarf."),
 "appropriate": ("ıp-ROU-pri-ıt", "suitable for the situation", "Wear <b>appropriate</b> clothes for the interview."),
 "cure": ("KYU-ır", "to make an illness go away; a remedy", "Doctors hope to <b>cure</b> the disease."),
 "relatively": ("RE-lı-tiv-li", "compared to others; fairly", "The exam was <b>relatively</b> easy."),
}
