# -*- coding: utf-8 -*-
# Grup 27 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 27
DATA = {
 "accompany": ("ı-KAM-pı-ni", "to go with someone", "A parent must <b>accompany</b> young children."),
 "expectation": ("eks-pek-TEY-şın", "a belief that something will happen", "The film met all my <b>expectations</b>."),
 "shallow": ("ŞE-lou", "not deep", "The pool is <b>shallow</b> at this end."),
 "outline": ("AUT-layn", "the main points; the outer shape", "She gave an <b>outline</b> of her plan."),
 "slight": ("SLAYT", "small; not important", "There was a <b>slight</b> delay."),
 "illustrate": ("İ-lıst-reyt", "to explain with examples or pictures", "Let me <b>illustrate</b> this with a story."),
 "dismiss": ("dis-MİS", "to remove from a job; to refuse to consider", "The boss <b>dismissed</b> two workers."),
 "resist": ("ri-ZİST", "to fight against; to not give in to", "I couldn't <b>resist</b> the chocolate cake."),
 "measurement": ("ME-jır-mınt", "a size found by measuring", "Take the <b>measurements</b> of the window."),
 "bitter": ("Bİ-tır", "having a sharp, sour taste; angry", "Black coffee tastes <b>bitter</b>."),
 "opposed": ("ı-POUZD", "against something", "She is <b>opposed</b> to the new plan."),
 "arms": ("ARMZ", "weapons", "The soldiers laid down their <b>arms</b>."),
 "aid": ("EYD", "help; to help", "The charity sends <b>aid</b> to poor countries."),
 "partly": ("PART-li", "in part; not completely", "The accident was <b>partly</b> my fault."),
 "appeal": ("ı-PİİL", "attraction; a serious request", "The idea has a strong <b>appeal</b>."),
 "selection": ("si-LEK-şın", "a choice; a group chosen", "The shop has a wide <b>selection</b> of shoes."),
 "closely": ("KLOUS-li", "carefully; nearly", "Watch the demonstration <b>closely</b>."),
 "initiative": ("i-Nİ-şı-tiv", "the ability to act first; a new plan", "She showed great <b>initiative</b> at work."),
 "industrial": ("in-DAST-ri-ıl", "relating to factories and making goods", "This is an <b>industrial</b> area."),
 "rush": ("RAŞ", "to hurry; a busy movement", "Don't <b>rush</b>; we have plenty of time."),
 "inspire": ("in-SPA-yır", "to give someone the desire to do something", "Her story <b>inspired</b> me to help others."),
 "tropical": ("TRO-pi-kıl", "relating to hot wet areas near the equator", "Bananas grow in <b>tropical</b> countries."),
 "budget": ("BA-cit", "a plan for spending money", "We must stay within our <b>budget</b>."),
 "assessment": ("ı-SES-mınt", "a judgement of the value or level of something", "The teacher wrote an <b>assessment</b> of each student."),
 "phase": ("FEYZ", "a stage in a process", "The project is in its final <b>phase</b>."),
 "pitch": ("PİÇ", "a sports field; how high or low a sound is", "The players ran onto the <b>pitch</b>."),
 "status": ("STEY-tıs", "a position or rank; the current state", "What is the <b>status</b> of your application?"),
 "melt": ("MELT", "to turn from solid to liquid", "The snow began to <b>melt</b> in the sun."),
 "freedom": ("FRİİ-dım", "the state of being free", "They fought for their <b>freedom</b>."),
 "regret": ("rig-RET", "to feel sorry about something", "I <b>regret</b> not studying harder."),
 "curve": ("KÖRV", "a smooth bend", "The road has a sharp <b>curve</b>."),
 "humour": ("HYU-mır", "the quality of being funny", "She has a good sense of <b>humour</b>."),
 "presence": ("PREZ-ıns", "the state of being present", "Your <b>presence</b> at the meeting is required."),
 "means": ("MİİNZ", "a method or way", "Email is a quick <b>means</b> of communication."),
 "associated": ("ı-SOU-şi-ey-tid", "connected or related", "Smoking is <b>associated</b> with heart disease."),
 "conservative": ("kın-SÖR-vı-tiv", "not liking change; traditional", "He has <b>conservative</b> views."),
 "investment": ("in-VEST-mınt", "money put into something to gain more", "A good education is a wise <b>investment</b>."),
 "unique": ("yu-NİİK", "being the only one of its kind", "Each snowflake is <b>unique</b>."),
 "wherever": ("ue-ır-E-vır", "in or to any place", "I'll follow you <b>wherever</b> you go."),
 "scream": ("SKRİİM", "to cry out loudly", "She <b>screamed</b> when she saw the spider."),
 "surround": ("sı-RAUND", "to be all around", "Trees <b>surround</b> the house."),
 "transform": ("trens-FORM", "to change completely", "The paint will <b>transform</b> the room."),
 "efficient": ("i-Fİ-şınt", "working well without wasting time or energy", "The new system is more <b>efficient</b>."),
 "stable": ("STEY-bıl", "steady; a building for horses", "The patient's condition is now <b>stable</b>."),
 "defeat": ("di-FİİT", "to beat someone; a loss", "Our team <b>defeated</b> theirs."),
 "actual": ("EK-çu-ıl", "real; existing in fact", "The <b>actual</b> cost was higher than expected."),
 "wind": ("UİND", "moving air; to turn or twist", "The <b>wind</b> blew the leaves away."),
 "enthusiasm": ("in-TYU-zi-ez-ım", "strong interest and excitement", "She spoke with great <b>enthusiasm</b>."),
 "minimum": ("Mİ-ni-mım", "the smallest possible amount", "You need a <b>minimum</b> of five points to pass."),
 "additional": ("ı-Dİ-şı-nıl", "extra; more", "There is an <b>additional</b> charge for baggage."),
 "satisfy": ("SE-tis-fay", "to make someone pleased", "Nothing seems to <b>satisfy</b> him."),
 "harmful": ("HARM-fıl", "causing harm", "Too much sugar is <b>harmful</b>."),
 "weakness": ("UİİK-nıs", "a lack of strength; a weak point", "His main <b>weakness</b> is impatience."),
 "anniversary": ("e-ni-VÖR-sı-ri", "the yearly date of an event", "They celebrated their wedding <b>anniversary</b>."),
 "tune": ("TYUN", "a series of musical notes; a melody", "She hummed a happy <b>tune</b>."),
 "calculate": ("KEL-kyu-leyt", "to work out an amount using numbers", "Please <b>calculate</b> the total cost."),
 "income": ("İN-kım", "the money you earn", "Their monthly <b>income</b> is quite low."),
 "pose": ("POUZ", "to sit for a photo; to present a problem", "The change may <b>pose</b> a problem."),
 "construction": ("kın-STRAK-şın", "the act of building", "The <b>construction</b> of the bridge took a year."),
 "downwards": ("DAUN-uıdz", "towards a lower place", "The path led <b>downwards</b> to the beach."),
 "tear": ("TE-ır", "to pull apart; a drop from the eye", "A <b>tear</b> ran down her cheek."),
 "decrease": ("Dİİ-kriis", "to become smaller; a fall", "There was a <b>decrease</b> in sales."),
 "panel": ("PE-nıl", "a flat board; a group of experts", "A <b>panel</b> of judges chose the winner."),
 "annual": ("EN-yu-ıl", "happening once a year", "The <b>annual</b> festival is in June."),
 "intended": ("in-TEN-did", "planned; meant", "This book is <b>intended</b> for children."),
 "debate": ("di-BEYT", "a formal discussion of different views", "There was a lively <b>debate</b> about the plan."),
 "temporary": ("TEMP-rı-ri", "lasting only a short time", "She has a <b>temporary</b> job for the summer."),
 "administration": ("ıd-mi-nis-TREY-şın", "the running of a business or government", "The company's <b>administration</b> is efficient."),
 "modify": ("MO-di-fay", "to change slightly", "We had to <b>modify</b> the design."),
 "delay": ("di-LEY", "to make late; a wait", "Bad weather caused a long <b>delay</b>."),
 "joy": ("COY", "a feeling of great happiness", "The birth of the baby brought great <b>joy</b>."),
 "transition": ("tren-Zİ-şın", "a change from one state to another", "The <b>transition</b> to the new system was smooth."),
 "vital": ("VAY-tıl", "extremely important", "Water is <b>vital</b> for life."),
 "whereas": ("ue-ır-EZ", "while by contrast", "He likes tea, <b>whereas</b> she prefers coffee."),
 "outcome": ("AUT-kam", "a result", "We are waiting for the <b>outcome</b> of the test."),
 "offence": ("ı-FENS", "a crime; hurt feelings", "Stealing is a serious <b>offence</b>."),
 "upwards": ("AP-uıdz", "towards a higher place", "The smoke rose <b>upwards</b>."),
 "delight": ("di-LAYT", "great pleasure; to please greatly", "The children screamed with <b>delight</b>."),
 "mixed": ("MİKST", "made of different things", "I have <b>mixed</b> feelings about the news."),
 "crew": ("KRU", "the people who work on a ship or plane", "The <b>crew</b> welcomed the passengers."),
 "exploration": ("eks-plı-REY-şın", "the act of exploring", "Space <b>exploration</b> is expensive."),
 "long-term": ("long-TÖRM", "lasting a long time", "This is a <b>long-term</b> project."),
 "otherwise": ("A-dır-uayz", "if not; in other ways", "Hurry up, <b>otherwise</b> we'll be late."),
 "reputation": ("rep-yu-TEY-şın", "the opinion people have of someone", "The restaurant has a good <b>reputation</b>."),
 "artificial": ("ar-ti-Fİ-şıl", "made by people, not natural", "The drink contains <b>artificial</b> colours."),
 "chief": ("ÇİİF", "most important; a leader", "The <b>chief</b> reason for the delay was rain."),
 "impatient": ("im-PEY-şınt", "not able to wait calmly", "The children grew <b>impatient</b>."),
 "lively": ("LAYV-li", "full of energy; active", "It was a <b>lively</b> party."),
 "folding": ("FOUL-ding", "able to be folded up", "We took two <b>folding</b> chairs to the beach."),
 "accurate": ("EK-yu-rıt", "correct and exact", "The clock keeps <b>accurate</b> time."),
 "offend": ("ı-FEND", "to upset or hurt someone", "I didn't mean to <b>offend</b> you."),
 "flash": ("FLEŞ", "a sudden bright light", "There was a <b>flash</b> of lightning."),
 "criterion": ("kray-Tİ-ri-ın", "a standard used to judge something", "Price is the main <b>criterion</b>."),
 "psychologist": ("say-KO-lı-cist", "a person who studies the mind", "The <b>psychologist</b> helped her deal with stress."),
 "convert": ("kın-VÖRT", "to change into another form", "They <b>converted</b> the barn into a house."),
 "witness": ("UİT-nıs", "a person who sees an event", "A <b>witness</b> described the accident."),
 "vitamin": ("Vİ-tı-min", "a natural substance in food that keeps you healthy", "Oranges are full of <b>vitamin</b> C."),
 "county": ("KAUN-ti", "a region of a country", "They live in a small village in the <b>county</b>."),
 "obey": ("ı-BEY", "to do what you are told", "Drivers must <b>obey</b> the speed limit."),
 "steep": ("STİİP", "rising or falling sharply", "The hill was too <b>steep</b> to climb."),
}
