# -*- coding: utf-8 -*-
# Grup 28 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 28
DATA = {
 "comfort": ("KAM-fırt", "a pleasant, easy feeling; to make someone feel better", "The chair gives great <b>comfort</b>."),
 "volume": ("VOL-yum", "the amount of space; how loud a sound is", "Please turn down the <b>volume</b>."),
 "stock": ("STOK", "a supply of goods for sale", "The shop has a large <b>stock</b> of shoes."),
 "tone": ("TOUN", "the quality of a sound or voice", "She spoke in a friendly <b>tone</b>."),
 "obtain": ("ıb-TEYN", "to get something", "You can <b>obtain</b> a form at the office."),
 "household": ("HAUS-hould", "all the people living in one home", "The whole <b>household</b> helps with the cleaning."),
 "crash": ("KREŞ", "a violent accident; a loud noise", "The car <b>crash</b> blocked the road."),
 "reasonable": ("Rİİ-zı-nı-bıl", "fair and sensible; not too expensive", "The price seems <b>reasonable</b>."),
 "extent": ("iks-TENT", "how large or serious something is", "I don't know the full <b>extent</b> of the damage."),
 "emerge": ("i-MÖRC", "to come out or appear", "The sun <b>emerged</b> from behind the clouds."),
 "drag": ("DREG", "to pull something heavy along", "He <b>dragged</b> the box across the floor."),
 "defend": ("di-FEND", "to protect from attack", "The soldiers <b>defended</b> the city."),
 "apparently": ("ı-PE-rınt-li", "based on what seems to be true", "<b>Apparently</b>, she has moved abroad."),
 "detailed": ("Dİİ-teyld", "having many small facts", "She wrote a <b>detailed</b> report."),
 "angle": ("ENG-gıl", "the space between two lines that meet", "Draw a line at a right <b>angle</b>."),
 "reduction": ("ri-DAK-şın", "the act of making something smaller", "There was a <b>reduction</b> in prices."),
 "deliberately": ("di-Lİ-bı-rıt-li", "on purpose", "He <b>deliberately</b> broke the glass."),
 "classic": ("KLE-sik", "of high quality and lasting value", "It is a <b>classic</b> film."),
 "feather": ("FE-dır", "one of the light soft parts covering a bird", "A white <b>feather</b> floated down."),
 "monitor": ("MO-ni-tır", "to watch and check; a screen", "Nurses <b>monitor</b> the patient's heart."),
 "basically": ("BEY-sik-li", "in the most important ways; simply", "<b>Basically</b>, the plan is very simple."),
 "extraordinary": ("iks-TROR-di-nı-ri", "very unusual or special", "She has an <b>extraordinary</b> talent."),
 "shot": ("ŞOT", "the firing of a gun; an attempt", "We heard a <b>shot</b> in the distance."),
 "wildlife": ("UAYLD-layf", "wild animals and plants", "The park protects local <b>wildlife</b>."),
 "thus": ("DAS", "in this way; therefore", "He was ill and <b>thus</b> stayed at home."),
 "limited": ("Lİ-mi-tid", "small in amount; restricted", "We have a <b>limited</b> amount of time."),
 "core": ("KOR", "the central part", "The <b>core</b> of the apple is not eaten."),
 "pile": ("PAYL", "a number of things on top of each other", "There was a <b>pile</b> of books on the desk."),
 "landscape": ("LEND-skeyp", "the appearance of an area of land", "The <b>landscape</b> here is beautiful."),
 "neat": ("NİİT", "tidy and in order", "Her handwriting is very <b>neat</b>."),
 "reward": ("ri-UORD", "something given for good work; to give a prize", "He got a <b>reward</b> for his honesty."),
 "furthermore": ("FÖR-dır-mor", "in addition; also", "The house is small; <b>furthermore</b>, it is far away."),
 "venue": ("VEN-yu", "the place where an event happens", "The <b>venue</b> for the concert has changed."),
 "observation": ("ob-zır-VEY-şın", "the act of watching carefully; a remark", "Careful <b>observation</b> is important in science."),
 "emphasize": ("EM-fı-sayz", "to give special importance to", "I must <b>emphasize</b> the need for care."),
 "humorous": ("HYU-mı-rıs", "funny; making people laugh", "He told a <b>humorous</b> story."),
 "settle": ("SE-tıl", "to end an argument; to make a home somewhere", "They <b>settled</b> the dispute peacefully."),
 "species": ("SPİİ-şiiz", "a group of similar living things", "This bird is a rare <b>species</b>."),
 "lung": ("LANG", "one of the two organs used for breathing", "Smoking damages your <b>lungs</b>."),
 "entire": ("in-TA-yır", "whole; complete", "She read the <b>entire</b> book in one day."),
 "leadership": ("Lİİ-dır-şip", "the state of being a leader", "The team improved under her <b>leadership</b>."),
 "display": ("dis-PLEY", "to show; a public show", "The paintings are on <b>display</b> in the hall."),
 "crop": ("KROP", "a plant grown for food", "The <b>crop</b> of wheat was good this year."),
 "shooting": ("ŞU-ting", "the act of firing a gun; filming", "The <b>shooting</b> of the film took months."),
 "artistic": ("ar-TİS-tik", "relating to art; skilled in art", "She has great <b>artistic</b> ability."),
 "characteristic": ("ke-rık-tı-RİS-tik", "a typical quality of someone or something", "Kindness is his main <b>characteristic</b>."),
 "mass": ("MES", "a large amount; the main part", "A <b>mass</b> of people filled the square."),
 "shock": ("ŞOK", "a sudden upsetting surprise", "The news came as a great <b>shock</b>."),
 "swear": ("SUE-ır", "to promise seriously; to use rude words", "I <b>swear</b> I am telling the truth."),
 "pursue": ("pır-SYU", "to follow; to try to achieve", "She wants to <b>pursue</b> a career in music."),
 "oppose": ("ı-POUZ", "to be against", "Many people <b>oppose</b> the new road."),
 "holy": ("HOU-li", "connected with God or religion", "They visited a <b>holy</b> place."),
 "motor": ("MOU-tır", "a machine that makes something move", "The <b>motor</b> of the boat stopped."),
 "faith": ("FEYT", "strong belief or trust", "She has great <b>faith</b> in her doctor."),
 "bear (deal with)": ("BE-ır", "to accept or deal with something hard", "I can't <b>bear</b> the noise any longer."),
 "violence": ("VA-yı-lıns", "behaviour that hurts people", "The film contains too much <b>violence</b>."),
 "insurance": ("in-ŞU-rıns", "protection you pay for against loss", "Do you have travel <b>insurance</b>?"),
 "grand": ("GREND", "large and impressive", "They live in a <b>grand</b> old house."),
 "broadcast": ("BROD-kast", "to send out on radio or TV; a programme", "The match was <b>broadcast</b> live."),
 "sector": ("SEK-tır", "a part of an economy or area", "She works in the health <b>sector</b>."),
 "sensitive": ("SEN-si-tiv", "easily hurt or affected; understanding", "He is very <b>sensitive</b> to criticism."),
 "cell": ("SEL", "a small room; the smallest part of a body", "The prisoner sat alone in his <b>cell</b>."),
 "solar": ("SOU-lır", "relating to the sun", "They use <b>solar</b> panels for energy."),
 "self": ("SELF", "your own person or nature", "After the holiday she felt like her old <b>self</b>."),
 "engage": ("in-GEYC", "to attract and hold; to take part", "The story <b>engages</b> the reader at once."),
 "enable": ("i-NEY-bıl", "to make something possible", "The money will <b>enable</b> us to travel."),
 "priority": ("pray-O-rı-ti", "something that is most important", "Safety is our top <b>priority</b>."),
 "found": ("FAUND", "to start an organization", "They <b>founded</b> the school in 1900."),
 "depth": ("DEPT", "the distance from top to bottom", "What is the <b>depth</b> of the pool?"),
 "anger": ("ENG-gır", "a strong feeling of being upset", "His face was red with <b>anger</b>."),
 "session": ("SE-şın", "a period of time for an activity", "The training <b>session</b> lasts an hour."),
 "convinced": ("kın-VİNST", "completely sure", "I am <b>convinced</b> that he is right."),
 "possess": ("pı-ZES", "to have or own", "She <b>possesses</b> great courage."),
 "initially": ("i-Nİ-şı-li", "at the beginning", "<b>Initially</b>, the plan seemed good."),
 "realistic": ("ri-ı-LİS-tik", "sensible about what is possible; lifelike", "Be <b>realistic</b> about your goals."),
 "register": ("RE-cis-tır", "to put your name on an official list", "You must <b>register</b> before the class."),
 "resort": ("ri-ZORT", "a holiday place; to turn to for help", "We stayed at a beach <b>resort</b>."),
 "shame": ("ŞEYM", "a bad feeling about doing wrong; a pity", "It's a <b>shame</b> you can't come."),
 "pregnant": ("PREG-nınt", "having a baby growing inside", "She is six months <b>pregnant</b>."),
 "emphasis": ("EM-fı-sis", "special importance given to something", "The school puts <b>emphasis</b> on reading."),
 "stretch": ("STREÇ", "to make longer; to reach out", "<b>Stretch</b> your arms above your head."),
 "whom": ("HUM", "used as the object for 'who'", "The man to <b>whom</b> I spoke was kind."),
 "shelter": ("ŞEL-tır", "a place giving protection; to protect", "They found <b>shelter</b> from the rain."),
 "district": ("DİST-rikt", "an area of a town or country", "She lives in a quiet <b>district</b>."),
 "preserve": ("pri-ZÖRV", "to keep safe; to keep from decay", "Salt helps to <b>preserve</b> food."),
 "spiritual": ("SPİ-ri-çu-ıl", "relating to the soul or religion", "Music has a <b>spiritual</b> meaning for her."),
 "fee": ("Fİİ", "money paid for a service", "The entrance <b>fee</b> is ten liras."),
 "tunnel": ("TA-nıl", "a passage under the ground", "The train went through a long <b>tunnel</b>."),
 "gain": ("GEYN", "to get or win; an increase", "You will <b>gain</b> experience from this job."),
 "master": ("MAS-tır", "to learn fully; a skilled person", "It takes years to <b>master</b> a language."),
 "insist": ("in-SİST", "to say firmly and repeatedly", "She <b>insisted</b> on paying the bill."),
 "institute": ("İNS-ti-tyut", "an organization for study or work", "He studied at a science <b>institute</b>."),
 "tale": ("TEYL", "a story", "Grandma told us a <b>tale</b> about a dragon."),
 "occasionally": ("ı-KEY-jı-nı-li", "sometimes; not often", "We <b>occasionally</b> eat out."),
 "decline": ("dik-LAYN", "to become weaker; to refuse politely", "Sales began to <b>decline</b>."),
 "absolute": ("EB-sı-lut", "complete; total", "I have <b>absolute</b> trust in her."),
 "stiff": ("STİF", "hard to bend; not easy to move", "My neck feels <b>stiff</b> this morning."),
 "guarantee": ("ge-rın-Tİİ", "a firm promise; to promise", "The watch has a two-year <b>guarantee</b>."),
 "distribute": ("dis-TRİB-yut", "to give out to many people", "They <b>distribute</b> free books to children."),
 "prime": ("PRAYM", "main; of the best quality", "Health is of <b>prime</b> importance."),
}
