# -*- coding: utf-8 -*-
# Grup 29 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 29
DATA = {
 "satellite": ("SE-tı-layt", "an object sent into space to circle the earth", "The signal comes from a <b>satellite</b>."),
 "debt": ("DET", "money that you owe", "He worked hard to pay off his <b>debt</b>."),
 "armed": ("ARMD", "carrying a weapon", "The <b>armed</b> guards stood at the gate."),
 "cable": ("KEY-bıl", "a thick wire; a strong rope", "The bridge is held up by steel <b>cables</b>."),
 "origin": ("O-ri-cin", "the point where something begins", "The <b>origin</b> of the word is Latin."),
 "truly": ("TRU-li", "really; honestly", "I am <b>truly</b> sorry for the mistake."),
 "interpret": ("in-TÖR-prit", "to explain the meaning; to translate", "How do you <b>interpret</b> this poem?"),
 "concentration": ("kon-sın-TREY-şın", "the ability to give full attention", "The noise broke my <b>concentration</b>."),
 "encounter": ("in-KAUN-tır", "to meet by chance; a meeting", "We <b>encountered</b> some problems on the way."),
 "capacity": ("kı-PE-sı-ti", "the amount something can hold; ability", "The hall has a <b>capacity</b> of 500 people."),
 "pure": ("PYU-ır", "not mixed with anything else; clean", "The ring is made of <b>pure</b> gold."),
 "firm": ("FÖRM", "solid and strong; a company", "Press the clay into a <b>firm</b> shape."),
 "courage": ("KA-ric", "the ability to face danger or pain", "It took great <b>courage</b> to speak out."),
 "fortune": ("FOR-çun", "a large amount of money; luck", "He made a <b>fortune</b> in business."),
 "fundamental": ("fan-dı-MEN-tıl", "basic and very important", "Reading is a <b>fundamental</b> skill."),
 "upper": ("A-pır", "higher in position", "Her office is on the <b>upper</b> floor."),
 "curved": ("KÖRVD", "bent in a smooth line", "The road followed a <b>curved</b> path."),
 "nevertheless": ("ne-vır-dı-LES", "in spite of that; however", "It was raining; <b>nevertheless</b>, we went out."),
 "handle": ("HEN-dıl", "to deal with; a part you hold", "She can <b>handle</b> difficult customers."),
 "defence": ("di-FENS", "protection against attack", "The team played a strong <b>defence</b>."),
 "objective": ("ıb-CEK-tiv", "an aim; based on facts not feelings", "Our main <b>objective</b> is to help others."),
 "rescue": ("RES-kyu", "to save from danger; a saving", "The firemen <b>rescued</b> the child."),
 "chairman": ("ÇE-ır-mın", "the person in charge of a meeting", "The <b>chairman</b> opened the meeting."),
 "lower": ("LOU-ır", "to move down; further down", "Please <b>lower</b> your voice."),
 "bond": ("BOND", "a close connection; to join", "There is a strong <b>bond</b> between the sisters."),
 "revolution": ("re-vı-LU-şın", "a great change; the overthrow of a government", "The <b>revolution</b> changed the country forever."),
 "blame": ("BLEYM", "to say someone is at fault", "Don't <b>blame</b> me for the delay."),
 "contract": ("KON-trekt", "a written legal agreement", "She signed a two-year <b>contract</b>."),
 "attempt": ("ı-TEMPT", "an effort to do something; to try", "This is his second <b>attempt</b> at the exam."),
 "ethical": ("E-ti-kıl", "relating to right and wrong", "It is not <b>ethical</b> to lie to customers."),
 "rank": ("RENK", "a position in a group; to place in order", "He holds a high <b>rank</b> in the army."),
 "acquire": ("ık-UA-yır", "to get or gain", "She hopes to <b>acquire</b> new skills."),
 "impress": ("im-PRES", "to make someone admire you", "He tried to <b>impress</b> his boss."),
 "deny": ("di-NAY", "to say something is not true", "He continued to <b>deny</b> the charge."),
 "circumstance": ("SÖR-kım-stıns", "a fact or condition affecting a situation", "Under the <b>circumstances</b>, we did our best."),
 "notion": ("NOU-şın", "an idea or belief", "I have no <b>notion</b> of what he means."),
 "council": ("KAUN-sıl", "a group that manages a town or area", "The town <b>council</b> built a new park."),
 "potential": ("pı-TEN-şıl", "the ability to develop in the future", "She has great <b>potential</b> as a singer."),
 "strike": ("STRAYK", "to hit; to stop work in protest", "The workers went on <b>strike</b> for more pay."),
 "licence": ("LAY-sıns", "an official document giving permission", "You need a <b>licence</b> to drive a car."),
 "affair": ("ı-FE-ır", "an event or matter; a business", "The wedding was a grand <b>affair</b>."),
 "brief": ("BRİİF", "lasting a short time; short", "She gave a <b>brief</b> reply."),
 "funding": ("FAN-ding", "money provided for a purpose", "The project needs more <b>funding</b>."),
 "multiply": ("MAL-tip-lay", "to increase; to add a number to itself", "Rabbits <b>multiply</b> very quickly."),
 "failure": ("FEYL-yır", "a lack of success; a breakdown", "The plan ended in <b>failure</b>."),
 "senior": ("Sİİ-ni-ır", "higher in rank; older", "She is a <b>senior</b> manager."),
 "bunch": ("BANÇ", "a group of things joined together", "He gave her a <b>bunch</b> of flowers."),
 "struggle": ("STRA-gıl", "to try hard against difficulty; a hard effort", "They <b>struggled</b> to reach the top."),
 "crucial": ("KRU-şıl", "extremely important", "This is a <b>crucial</b> moment in the game."),
 "confusing": ("kın-FYU-zing", "hard to understand", "The instructions were <b>confusing</b>."),
 "stare": ("STE-ır", "to look for a long time", "It is rude to <b>stare</b> at people."),
 "zone": ("ZOUN", "an area with a special use", "This is a no-parking <b>zone</b>."),
 "slope": ("SLOUP", "a surface that goes up or down", "We skied down the <b>slope</b>."),
 "league": ("LİİG", "a group of sports teams that compete", "Our team is top of the <b>league</b>."),
 "grab": ("GREB", "to take suddenly", "He <b>grabbed</b> my arm."),
 "overall": ("ou-vır-OL", "in general; including everything", "<b>Overall</b>, the trip was a success."),
 "launch": ("LONÇ", "to start something; to send off", "They will <b>launch</b> the new phone next week."),
 "edit": ("E-dit", "to correct and prepare a text", "She had to <b>edit</b> the article before printing."),
 "somewhat": ("SAM-uot", "a little; to some degree", "I was <b>somewhat</b> surprised by the news."),
 "component": ("kım-POU-nınt", "a part of a larger thing", "Each <b>component</b> of the engine was checked."),
 "apparent": ("ı-PE-rınt", "easily seen; seeming to be true", "It soon became <b>apparent</b> that he was lying."),
 "examination": ("ig-ze-mi-NEY-şın", "a careful look; a test", "The doctor gave him a full <b>examination</b>."),
 "flexible": ("FLEK-sı-bıl", "able to bend or change easily", "Our plans are quite <b>flexible</b>."),
 "illustration": ("i-lıst-REY-şın", "a picture in a book; an example", "The book has colourful <b>illustrations</b>."),
 "regulation": ("reg-yu-LEY-şın", "an official rule", "Safety <b>regulations</b> must be obeyed."),
 "massive": ("ME-siv", "extremely large", "A <b>massive</b> wave hit the boat."),
 "abandon": ("ı-BEN-dın", "to leave completely; to give up", "They had to <b>abandon</b> the car in the snow."),
 "propose": ("prı-POUZ", "to suggest; to offer marriage", "I <b>propose</b> that we meet on Monday."),
 "hearing": ("Hİ-ı-ring", "the ability to hear; a legal meeting", "His <b>hearing</b> is not as good as it was."),
 "steel": ("STİİL", "a strong metal made from iron", "The building has a frame of <b>steel</b>."),
 "estate": ("is-TEYT", "a large area of land; property left after death", "They own a country <b>estate</b>."),
 "pension": ("PEN-şın", "money paid to a person after they retire", "He lives on a small <b>pension</b>."),
 "blind": ("BLAYND", "not able to see", "The old man is nearly <b>blind</b>."),
 "desperate": ("DES-pı-rıt", "feeling great need; done with little hope", "They were <b>desperate</b> for food and water."),
 "crisis": ("KRAY-sis", "a time of great danger or difficulty", "The country faces an economic <b>crisis</b>."),
 "depressing": ("dip-RE-sing", "making you feel very sad", "The grey weather is <b>depressing</b>."),
 "association": ("ı-sou-si-EY-şın", "an organized group; a connection", "She joined the local sports <b>association</b>."),
 "finding": ("FAYN-ding", "a result of research or a study", "The <b>findings</b> of the study were surprising."),
 "aggressive": ("ıg-RE-siv", "angry and ready to attack", "The dog became <b>aggressive</b>."),
 "impose": ("im-POUZ", "to force something on someone", "They will <b>impose</b> a new tax."),
 "victory": ("VİK-tı-ri", "a win", "The team celebrated their <b>victory</b>."),
 "silence": ("SAY-lıns", "the absence of sound", "There was a long <b>silence</b> in the room."),
 "establish": ("is-TEB-liş", "to set up; to prove", "They want to <b>establish</b> a new school."),
 "maximum": ("MEK-si-mım", "the largest possible amount", "The <b>maximum</b> speed is 100."),
 "deeply": ("DİİP-li", "very much; to a great degree", "She was <b>deeply</b> moved by the story."),
 "genre": ("JAN-rı", "a type of art, music or writing", "My favourite <b>genre</b> is science fiction."),
 "mount": ("MAUNT", "to climb up; to fix in place", "Tension began to <b>mount</b> before the game."),
 "evil": ("İİ-vıl", "very bad; morally wrong", "The story is about the fight against <b>evil</b>."),
 "dig": ("DİG", "to make a hole in the ground", "The dog likes to <b>dig</b> in the garden."),
 "sticky": ("STİ-ki", "able to stick to things", "My hands are <b>sticky</b> from the honey."),
 "vary": ("VE-ri", "to be different; to change", "Prices <b>vary</b> from shop to shop."),
 "being": ("Bİİ-ing", "a living creature; existence", "Every human <b>being</b> deserves respect."),
 "military": ("Mİ-li-tı-ri", "relating to soldiers and the army", "He had a long <b>military</b> career."),
 "desire": ("di-ZA-yır", "a strong wish", "She had a strong <b>desire</b> to travel."),
 "discipline": ("Dİ-sip-lin", "controlled behaviour; training", "The school has strict <b>discipline</b>."),
 "evaluate": ("i-VEL-yu-eyt", "to judge the value of something", "Teachers <b>evaluate</b> the students' work."),
 "domestic": ("dı-MES-tik", "relating to the home; of one country", "Cats are <b>domestic</b> animals."),
 "former": ("FOR-mır", "of an earlier time; previous", "The <b>former</b> teacher visited the school."),
 "assume": ("ı-SYUM", "to think something is true without proof", "I <b>assume</b> you have read the book."),
 "shocked": ("ŞOKT", "very surprised and upset", "We were <b>shocked</b> by the sad news."),
}
