# -*- coding: utf-8 -*-
# Grup 3 (A1) — okunuş / İngilizce açıklama / örnek cümle
# Okunuş: heceler tireli, vurgulu hece BÜYÜK, yalnız Türkçe harfler.
GRUP_NO = 3
DATA = {
 "yeah": ("YEE", "an informal way to say yes", "<b>Yeah</b>, I agree with you."),
 "road": ("ROUD", "a hard surface for cars to travel on", "This <b>road</b> goes to the city centre."),
 "everything": ("EV-ri-ting", "all things", "<b>Everything</b> is ready for the party."),
 "artist": ("AR-tist", "a person who makes art, like paintings", "The <b>artist</b> painted a beautiful picture."),
 "dangerous": ("DEYN-cı-rıs", "able to hurt or harm you", "Swimming here is <b>dangerous</b>."),
 "TV": ("ti-Vİİ", "television", "We don't watch much <b>TV</b>."),
 "problem": ("PROB-lım", "something difficult that needs an answer", "There is a <b>problem</b> with my computer."),
 "cousin": ("KA-zın", "the child of your aunt or uncle", "My <b>cousin</b> lives in İzmir."),
 "their": ("DE-ır", "belonging to them", "The students opened <b>their</b> books."),
 "glass": ("GLAS", "a hard clear material; a cup made of it", "Be careful, the <b>glass</b> is broken."),
 "east": ("İİST", "the direction where the sun rises", "The sun rises in the <b>east</b>."),
 "salad": ("SE-lıd", "a cold dish of vegetables", "I had a chicken <b>salad</b> for lunch."),
 "never": ("NE-vır", "not at any time", "I have <b>never</b> been to Paris."),
 "put": ("PUT", "to place something somewhere", "<b>Put</b> the milk in the fridge, please."),
 "useful": ("YUS-fıl", "helping you do or get something", "This app is very <b>useful</b> for learning."),
 "interview": ("İN-tır-vyu", "a meeting with questions, e.g. for a job", "She has a job <b>interview</b> tomorrow."),
 "forget": ("fır-GET", "to not remember something", "Don't <b>forget</b> your umbrella!"),
 "band": ("BEND", "a group of musicians", "My favourite <b>band</b> is giving a concert."),
 "team": ("TİİM", "a group of people who play or work together", "Our <b>team</b> won the match."),
 "form": ("FORM", "a shape or type; a paper with questions", "Please fill in this <b>form</b>."),
 "famous": ("FEY-mıs", "known by many people", "İstanbul is <b>famous</b> for its history."),
 "daughter": ("DO-tır", "a female child", "Their <b>daughter</b> is studying medicine."),
 "December": ("di-SEM-bır", "the twelfth month of the year", "It usually snows in <b>December</b>."),
 "not": ("NOT", "used to make a sentence negative", "I'm <b>not</b> hungry right now."),
 "us": ("AS", "me and other people", "Come with <b>us</b> to the cinema!"),
 "sixteen": ("siks-TİİN", "the number 16", "My brother is <b>sixteen</b> years old."),
 "yesterday": ("YES-tır-dey", "the day before today", "I saw her <b>yesterday</b> at school."),
 "few": ("FYU", "a small number of", "Only a <b>few</b> people came to the meeting."),
 "decide": ("di-SAYD", "to choose after thinking", "We need to <b>decide</b> where to go."),
 "Monday": ("MAN-dey", "the first day of the working week", "The course starts on <b>Monday</b>."),
 "send": ("SEND", "to make something go to another place", "I'll <b>send</b> you the photos tonight."),
 "take": ("TEYK", "to carry or move something; to get", "<b>Take</b> your coat, it's cold outside."),
 "nice": ("NAYS", "pleasant; kind", "Have a <b>nice</b> weekend!"),
 "I": ("AY", "the person speaking (yourself)", "<b>I</b> am from Turkey."),
 "climb": ("KLAYM", "to go up something like a mountain or stairs", "They want to <b>climb</b> that mountain."),
 "who": ("HU", "which person", "<b>Who</b> is that man at the door?"),
 "farmer": ("FAR-mır", "a person who grows food or keeps animals", "The <b>farmer</b> gets up very early."),
 "result": ("ri-ZALT", "what happens because of something; a score", "The exam <b>results</b> come out on Friday."),
 "activity": ("ek-Tİ-vı-ti", "something you do, especially for fun", "Swimming is my favourite <b>activity</b>."),
 "cup": ("KAP", "a small container for drinking; a prize", "Would you like a <b>cup</b> of coffee?"),
 "close": ("KLOUZ", "to shut something; near", "Please <b>close</b> the window."),
 "make": ("MEYK", "to create or produce something", "I'll <b>make</b> dinner tonight."),
 "eight": ("EYT", "the number 8", "The shop opens at <b>eight</b>."),
 "interest": ("İN-trest", "the feeling of wanting to know more", "He shows great <b>interest</b> in science."),
 "grow": ("GROU", "to become bigger; to plant and care for", "These trees <b>grow</b> very fast."),
 "dollar": ("DO-lır", "the money used in the USA", "The book costs ten <b>dollars</b>."),
 "short": ("ŞORT", "not long; not tall", "It's only a <b>short</b> walk from here."),
 "world": ("UÖRLD", "the Earth and everything on it", "She wants to travel around the <b>world</b>."),
 "phone": ("FOUN", "a device you use to call people", "My <b>phone</b> battery is dead."),
 "can": ("KEN", "to be able to do something; a metal container", "You <b>can</b> swim very well."),
 "chicken": ("Çİ-kin", "a farm bird; its meat", "We had <b>chicken</b> and rice for dinner."),
 "blog": ("BLOG", "a website where someone writes regularly", "She writes a <b>blog</b> about travel."),
 "wash": ("UOŞ", "to clean something with water", "<b>Wash</b> your hands before dinner."),
 "ride": ("RAYD", "to travel on a bicycle, horse or bus", "I <b>ride</b> my bike to school."),
 "age": ("EYC", "how old someone or something is", "Children of all <b>ages</b> love this game."),
 "join": ("COYN", "to become a member; to connect", "Why don't you <b>join</b> our team?"),
 "big": ("BİG", "large in size", "They have a <b>big</b> garden."),
 "four": ("FOR", "the number 4", "The lesson lasts <b>four</b> hours."),
 "north": ("NORT", "the direction that is up on a map", "Trabzon is in the <b>north</b> of Turkey."),
 "style": ("STAYL", "a way of doing or making something", "I like your <b>style</b> of dressing."),
 "outside": ("aut-SAYD", "not inside a building", "The children are playing <b>outside</b>."),
 "article": ("AR-ti-kıl", "a piece of writing in a newspaper or magazine", "I read an interesting <b>article</b> today."),
 "village": ("Vİ-liç", "a very small town in the countryside", "My grandparents live in a <b>village</b>."),
 "geography": ("ci-YOG-rı-fi", "the study of countries, mountains and seas", "<b>Geography</b> is my favourite subject."),
 "child": ("ÇAYLD", "a young person; a son or daughter", "Every <b>child</b> needs love and care."),
 "game": ("GEYM", "an activity you play with rules", "Let's play a <b>game</b> after dinner."),
 "like (similar)": ("LAYK", "similar to; in the same way as", "She looks <b>like</b> her mother."),
 "arrive": ("ı-RAYV", "to get to a place", "The train will <b>arrive</b> at six."),
 "thank": ("TENK", "to tell someone you are grateful", "I want to <b>thank</b> you for your help."),
 "chocolate": ("ÇOK-lit", "a sweet brown food", "He gave her a box of <b>chocolates</b>."),
 "shopping": ("ŞO-ping", "buying things from shops", "We go <b>shopping</b> on Saturdays."),
 "red": ("RED", "the colour of blood", "She was wearing a <b>red</b> dress."),
 "house": ("HAUS", "a building where people live", "They bought a new <b>house</b> last year."),
 "negative": ("NE-gı-tiv", "bad or harmful; saying no", "Don't be so <b>negative</b> about the future."),
 "carry": ("KE-ri", "to hold something and take it somewhere", "Let me <b>carry</b> that bag for you."),
 "chair": ("ÇE-ır", "a seat for one person", "Please sit on this <b>chair</b>."),
 "sea": ("Sİİ", "the large area of salt water", "The hotel has a view of the <b>sea</b>."),
 "green": ("GRİİN", "the colour of grass", "The fields are <b>green</b> in spring."),
 "picture": ("PİK-çır", "a drawing, painting or photo", "There is a <b>picture</b> of my family on the wall."),
 "yellow": ("YE-lou", "the colour of the sun or lemons", "She painted the kitchen <b>yellow</b>."),
 "star": ("STAR", "a bright light in the night sky; a famous person", "You can see every <b>star</b> tonight."),
 "mouth": ("MAUT", "the part of your face used for eating and speaking", "Don't talk with your <b>mouth</b> full."),
 "eye": ("AY", "the part of your body you see with", "She has beautiful green <b>eyes</b>."),
 "grandfather": ("GREN-fa-dır", "the father of your mother or father", "My <b>grandfather</b> tells great stories."),
 "computer": ("kım-PYU-tır", "a machine for working with information", "I use my <b>computer</b> for work and games."),
 "often": ("OF-tın", "many times", "We <b>often</b> eat out at weekends."),
 "floor": ("FLOR", "the surface you walk on inside; a level of a building", "The toys are all over the <b>floor</b>."),
 "before": ("bi-FOR", "earlier than something", "Brush your teeth <b>before</b> bed."),
 "Friday": ("FRAY-dey", "the day after Thursday", "We're meeting on <b>Friday</b> evening."),
 "perfect": ("PÖR-fikt", "completely right; without mistakes", "The weather was <b>perfect</b> for a picnic."),
 "light": ("LAYT", "brightness from the sun or a lamp; not heavy", "Turn on the <b>light</b>, please."),
 "ticket": ("Tİ-kit", "a piece of paper that lets you travel or enter", "I bought two <b>tickets</b> for the concert."),
 "young": ("YANG", "not old", "She is too <b>young</b> to drive."),
 "email": ("İİ-meyl", "a message sent by computer or phone", "Send me an <b>email</b> with the details."),
 "fantastic": ("fen-TES-tik", "extremely good", "The view from the top was <b>fantastic</b>!"),
 "map": ("MEP", "a drawing of an area showing roads and places", "Look at the <b>map</b> to find the museum."),
 "swim": ("SUİM", "to move through water using your body", "The children <b>swim</b> in the pool every day."),
 "theatre": ("Tİ-yı-tır", "a building where you watch plays", "We went to the <b>theatre</b> last night."),
 "ball": ("BOL", "a round object used in games", "Throw the <b>ball</b> to me!"),
 "plan": ("PLEN", "an idea about what to do and how", "What are your <b>plans</b> for the summer?"),
}
