# -*- coding: utf-8 -*-
# Grup 30 (B2) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 30
DATA = {
 "gang": ("GENG", "a group of people, often criminals", "A <b>gang</b> of youths hung around the corner."),
 "principle": ("PRİN-si-pıl", "a basic rule or belief", "She refused on a matter of <b>principle</b>."),
 "load": ("LOUD", "things that are carried; to put on", "The truck carried a heavy <b>load</b>."),
 "facility": ("fı-Sİ-lı-ti", "a place or service for a purpose", "The hotel has a sports <b>facility</b>."),
 "instance": ("İNS-tıns", "an example of something", "This is a clear <b>instance</b> of bad planning."),
 "commitment": ("kı-MİT-mınt", "a promise; hard work you give to something", "Marriage is a serious <b>commitment</b>."),
 "decent": ("Dİİ-sınt", "good enough; honest and kind", "He earns a <b>decent</b> salary."),
 "rural": ("RU-rıl", "relating to the countryside", "They moved to a <b>rural</b> area."),
 "fault": ("FOLT", "responsibility for a mistake; a weakness", "The accident was my <b>fault</b>."),
 "maintain": ("meyn-TEYN", "to keep in good condition; to keep going", "It is hard to <b>maintain</b> an old house."),
 "heel": ("HİİL", "the back part of the foot", "My new shoes hurt my <b>heel</b>."),
 "trial": ("TRA-yıl", "a test; a legal process in court", "The new drug is still on <b>trial</b>."),
 "dominate": ("DO-mi-neyt", "to control or be the strongest", "One team <b>dominated</b> the match."),
 "assess": ("ı-SES", "to judge the value or quality of", "The teacher will <b>assess</b> your work."),
 "hunting": ("HAN-ting", "the act of chasing animals to kill them", "<b>Hunting</b> foxes is now banned."),
 "alter": ("OL-tır", "to change slightly", "The tailor will <b>alter</b> the dress."),
 "flame": ("FLEYM", "the bright part of a fire", "The candle's <b>flame</b> flickered."),
 "committee": ("kı-Mİ-ti", "a group chosen to do a job", "The <b>committee</b> meets every month."),
 "anxious": ("ENK-şıs", "worried and nervous", "She felt <b>anxious</b> before the exam."),
 "gradually": ("GRE-cu-ı-li", "slowly, over a period of time", "The sky <b>gradually</b> grew dark."),
 "lord": ("LORD", "a man of high rank; a title", "The <b>lord</b> lived in a grand castle."),
 "regional": ("Rİİ-cı-nıl", "relating to a particular area", "The paper covers <b>regional</b> news."),
 "aspect": ("ES-pekt", "a part or feature of something", "We discussed every <b>aspect</b> of the plan."),
 "cite": ("SAYT", "to mention as an example or proof", "She <b>cited</b> three reasons for her choice."),
 "relief": ("ri-LİİF", "the feeling when worry or pain ends", "It was a <b>relief</b> to hear she was safe."),
 "slide": ("SLAYD", "to move smoothly over a surface", "The children love to <b>slide</b> on the ice."),
 "specialist": ("SPE-şı-list", "an expert in one subject", "She saw a heart <b>specialist</b>."),
 "imagination": ("i-me-ci-NEY-şın", "the ability to form ideas in the mind", "Children have a lively <b>imagination</b>."),
 "preparation": ("pre-pı-REY-şın", "the act of getting ready", "Good <b>preparation</b> is the key to success."),
 "wage": ("UEYC", "money paid for work, often weekly", "Their weekly <b>wage</b> is quite low."),
 "secure": ("si-KYU-ır", "safe; firmly fixed", "Make sure the door is <b>secure</b>."),
 "creature": ("KRİİ-çır", "a living thing, especially an animal", "The forest is full of small <b>creatures</b>."),
 "rely": ("ri-LAY", "to trust or depend on", "You can <b>rely</b> on me to help."),
 "tough": ("TAF", "strong; difficult", "The meat was too <b>tough</b> to eat."),
 "justify": ("CAS-ti-fay", "to give a good reason for", "How can you <b>justify</b> spending so much?"),
 "disc": ("DİSK", "a thin flat round object", "She saved the file onto a <b>disc</b>."),
 "urban": ("ÖR-bın", "relating to a town or city", "<b>Urban</b> areas are often crowded."),
 "capable": ("KEY-pı-bıl", "having the ability to do something", "She is <b>capable</b> of great things."),
 "decoration": ("de-kı-REY-şın", "something added to make a place pretty", "They put up <b>decorations</b> for the party."),
 "housing": ("HAU-zing", "buildings where people live", "The city needs more cheap <b>housing</b>."),
 "wealth": ("UELT", "a large amount of money and possessions", "The family's <b>wealth</b> grew over time."),
 "fellow": ("FE-lou", "a man; belonging to the same group", "He helped his <b>fellow</b> workers."),
 "contribution": ("kont-ri-BYU-şın", "something you give to help", "Everyone made a <b>contribution</b> to the gift."),
 "raw": ("RO", "not cooked; in a natural state", "The fish was served <b>raw</b>."),
 "enthusiastic": ("in-tyu-zi-ES-tik", "showing great interest and excitement", "The fans were very <b>enthusiastic</b>."),
 "universe": ("YU-ni-vörs", "all of space and everything in it", "The <b>universe</b> is vast and full of stars."),
 "forgive": ("fır-GİV", "to stop being angry about a wrong", "Please <b>forgive</b> me for being late."),
 "cancer": ("KEN-sır", "a serious disease that grows in the body", "Doctors work hard to cure <b>cancer</b>."),
 "rhythm": ("Rİ-dım", "a regular pattern of sounds or beats", "She danced to the <b>rhythm</b> of the drums."),
 "infection": ("in-FEK-şın", "an illness caused by germs", "The cut caused an <b>infection</b>."),
 "insight": ("İN-sayt", "a clear, deep understanding", "The book gives an <b>insight</b> into village life."),
 "float": ("FLOUT", "to stay on the surface of a liquid", "Wood will <b>float</b> on water."),
 "approve": ("ıp-RUV", "to agree that something is good", "Her parents <b>approve</b> of the marriage."),
 "install": ("ins-TOL", "to put equipment in place ready to use", "They will <b>install</b> the new heater tomorrow."),
 "select": ("si-LEKT", "to choose", "Please <b>select</b> one answer."),
 "via": ("VA-yı", "by way of; through", "We flew to Rome <b>via</b> Paris."),
 "privacy": ("PRAY-vı-si", "the state of being alone and unwatched", "Everyone has a right to <b>privacy</b>."),
 "acceptable": ("ık-SEP-tı-bıl", "good enough to be allowed", "Your work is of an <b>acceptable</b> standard."),
 "unexpected": ("an-iks-PEK-tid", "not expected; surprising", "We had an <b>unexpected</b> visitor."),
 "cast": ("KAST", "the actors in a play; to throw", "The whole <b>cast</b> took a bow."),
 "division": ("di-Vİ-jın", "the act of dividing; a part", "The <b>division</b> of the money was fair."),
 "fully": ("FU-li", "completely", "I <b>fully</b> understand your worry."),
 "depressed": ("dip-REST", "very sad and without hope", "He felt <b>depressed</b> after losing his job."),
 "citizen": ("Sİ-ti-zın", "a person who belongs to a country", "She is a British <b>citizen</b>."),
 "honour": ("O-nır", "great respect; to show respect", "It is an <b>honour</b> to meet you."),
 "expense": ("iks-PENS", "the cost of something", "The trip was worth the <b>expense</b>."),
 "excuse": ("iks-KYUS", "a reason given to explain a fault", "That is no <b>excuse</b> for being rude."),
 "conduct": ("KON-dakt", "behaviour; to organize or lead", "His <b>conduct</b> at school was excellent."),
 "breast": ("BREST", "the front upper part of the body", "The bird has a red <b>breast</b>."),
 "junior": ("CU-ni-ır", "younger; lower in rank", "He is a <b>junior</b> member of staff."),
 "recover": ("ri-KA-vır", "to get better after illness; to get back", "It took weeks to <b>recover</b> from the flu."),
 "intense": ("in-TENS", "very strong or extreme", "The <b>intense</b> heat made us tired."),
 "requirement": ("ri-KUA-yır-mınt", "something that is needed", "A degree is a <b>requirement</b> for this job."),
 "reveal": ("ri-VİİL", "to make known; to show", "She refused to <b>reveal</b> the secret."),
 "pace": ("PEYS", "the speed of movement", "He walked at a fast <b>pace</b>."),
 "surrounding": ("sı-RAUN-ding", "all around a place", "We admired the <b>surrounding</b> hills."),
 "finance": ("FAY-nens", "the management of money", "She works in <b>finance</b>."),
 "psychology": ("say-KO-lı-ci", "the study of the mind and behaviour", "She has a degree in <b>psychology</b>."),
 "vast": ("VAST", "extremely large", "A <b>vast</b> desert stretched before them."),
 "corporate": ("KOR-pı-rıt", "relating to a large company", "The company held a <b>corporate</b> meeting."),
 "govern": ("GA-vırn", "to rule or control a country", "A new party will <b>govern</b> the country."),
 "collapse": ("kı-LEPS", "to fall down suddenly; to fail", "The old bridge began to <b>collapse</b>."),
 "judgement": ("CAC-mınt", "the ability to make good decisions; a decision", "I trust her <b>judgement</b>."),
 "virtual": ("VÖR-çu-ıl", "almost real; made by a computer", "They met in a <b>virtual</b> world online."),
 "deliberate": ("di-Lİ-bı-rıt", "done on purpose", "It was a <b>deliberate</b> act of kindness."),
 "delighted": ("di-LAY-tid", "very pleased", "We were <b>delighted</b> to see them again."),
 "bent": ("BENT", "not straight; curved", "The nail was <b>bent</b>."),
 "capture": ("KEP-çır", "to catch a person or animal", "The soldiers tried to <b>capture</b> the fort."),
 "sincere": ("sin-Sİ-ır", "honest and true in feeling", "Please accept my <b>sincere</b> thanks."),
 "praise": ("PREYZ", "words that show approval; to approve", "The teacher gave her <b>praise</b>."),
 "bullet": ("BU-lit", "a small metal piece fired from a gun", "The <b>bullet</b> missed him by inches."),
 "contribute": ("kın-TRİB-yut", "to give money or help", "Everyone should <b>contribute</b> to the fund."),
 "severe": ("si-Vİ-ır", "very bad or serious; strict", "The area suffered a <b>severe</b> storm."),
 "grant": ("GRANT", "money given for a purpose; to allow", "She won a <b>grant</b> to study abroad."),
 "beg": ("BEG", "to ask for something urgently", "The child began to <b>beg</b> for food."),
 "elderly": ("EL-dır-li", "old", "The <b>elderly</b> man walked slowly."),
 "minority": ("may-NO-rı-ti", "the smaller part of a group", "Only a <b>minority</b> voted against the plan."),
 "representative": ("rep-ri-ZEN-tı-tiv", "a person who acts for others", "She is our class <b>representative</b>."),
 "shade": ("ŞEYD", "an area out of the sun; a degree of colour", "We sat in the <b>shade</b> of a tree."),
 "seek": ("SİİK", "to try to find or get", "Many people <b>seek</b> work in the city."),
}
