# -*- coding: utf-8 -*-
# Grup 4 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 4
DATA = {
 "stay": ("STEY", "to remain in a place", "We will <b>stay</b> at a hotel near the beach."),
 "career": ("kı-Rİ-ır", "the job or series of jobs you do in your life", "She wants a <b>career</b> in medicine."),
 "jeans": ("CİİNZ", "trousers made of strong cotton", "He wears blue <b>jeans</b> every day."),
 "second": ("SE-kınd", "a short unit of time; coming after the first", "Wait a <b>second</b>, please."),
 "project": ("PRO-cekt", "a planned piece of work", "We finished the school <b>project</b> together."),
 "upstairs": ("ap-STE-ırz", "on or to a higher floor", "The bedrooms are <b>upstairs</b>."),
 "flower": ("FLA-uır", "the colourful part of a plant", "She gave me a red <b>flower</b>."),
 "dog": ("DOG", "a common animal kept as a pet", "The <b>dog</b> is playing in the garden."),
 "type": ("TAYP", "a kind or sort; to write with a keyboard", "What <b>type</b> of music do you like?"),
 "arm": ("ARM", "the part of your body from shoulder to hand", "He broke his <b>arm</b>."),
 "rich": ("RİÇ", "having a lot of money", "They live in a <b>rich</b> part of the city."),
 "carrot": ("KE-rıt", "a long orange vegetable", "Rabbits love to eat <b>carrots</b>."),
 "always": ("OL-ueyz", "every time; at all times", "She <b>always</b> arrives early."),
 "policeman": ("pı-LİİS-mın", "a male police officer", "The <b>policeman</b> showed us the way."),
 "quite": ("KUAYT", "a little more than usual; fairly", "It's <b>quite</b> cold today."),
 "breakfast": ("BREK-fıst", "the first meal of the day", "I have eggs for <b>breakfast</b>."),
 "cafe": ("KE-fey", "a small place that sells drinks and light food", "We met at a <b>cafe</b>."),
 "here": ("Hİ-ır", "in this place", "Come <b>here</b>, please."),
 "cannot": ("KE-not", "to not be able to do something", "I <b>cannot</b> swim very well."),
 "aunt": ("ANT", "the sister of your mother or father", "My <b>aunt</b> lives in Ankara."),
 "country": ("KAN-tri", "a land with its own government; the countryside", "Türkiye is a beautiful <b>country</b>."),
 "man": ("MEN", "an adult male person", "That <b>man</b> is my teacher."),
 "family": ("FE-mı-li", "parents and their children", "I love my <b>family</b>."),
 "classroom": ("KLAS-rum", "a room where students have lessons", "Our <b>classroom</b> is on the second floor."),
 "as": ("EZ", "used to compare; while; because", "She works <b>as</b> a nurse."),
 "blue": ("BLU", "the colour of a clear sky", "He has <b>blue</b> eyes."),
 "same": ("SEYM", "not different; alike", "We go to the <b>same</b> school."),
 "if": ("İF", "used to talk about a possible situation", "Call me <b>if</b> you need help."),
 "nobody": ("NOU-bı-di", "no person", "<b>Nobody</b> was at home."),
 "grandmother": ("GREN-ma-dır", "the mother of your parent", "My <b>grandmother</b> makes great food."),
 "police": ("pı-LİİS", "the people who keep public order", "Someone called the <b>police</b>."),
 "twelve": ("TUELV", "the number 12", "There are <b>twelve</b> months in a year."),
 "conversation": ("kon-vır-SEY-şın", "a talk between people", "We had a long <b>conversation</b>."),
 "imagine": ("i-ME-cin", "to form a picture in your mind", "<b>Imagine</b> living by the sea."),
 "twice": ("TUAYS", "two times", "I brush my teeth <b>twice</b> a day."),
 "hot": ("HOT", "having a high temperature", "The soup is very <b>hot</b>."),
 "mean": ("MİİN", "to have as a meaning; unkind", "What does this word <b>mean</b>?"),
 "text": ("TEKST", "written words; a short message", "Send me a <b>text</b> when you arrive."),
 "college": ("KO-liç", "a place for study after school", "My sister studies at a <b>college</b>."),
 "like (find sb/sth pleasant)": ("LAYK", "to enjoy or be fond of something", "I <b>like</b> playing football."),
 "fifty": ("FİF-ti", "the number 50", "The book has <b>fifty</b> pages."),
 "dirty": ("DÖR-ti", "not clean", "Your shoes are <b>dirty</b>."),
 "cold": ("KOULD", "having a low temperature", "The water is too <b>cold</b>."),
 "object": ("OB-cekt", "a thing you can see or touch", "What is that strange <b>object</b>?"),
 "fun": ("FAN", "enjoyment or pleasure", "The party was great <b>fun</b>."),
 "would": ("UUD", "used for polite offers or requests", "<b>Would</b> you like some tea?"),
 "science": ("SA-yıns", "the study of the natural world", "<b>Science</b> is my favourite subject."),
 "photo": ("FOU-tou", "a picture made with a camera", "Let's take a <b>photo</b> together."),
 "holiday": ("HO-lı-dey", "a time of rest away from work", "We went to Antalya on <b>holiday</b>."),
 "oh": ("OU", "used to show surprise or emotion", "<b>Oh</b>, I forgot my keys!"),
 "kilometre": ("Kİ-lı-mii-tır", "a unit of distance (1000 metres)", "The town is ten <b>kilometres</b> away."),
 "mile": ("MAYL", "a unit of distance (about 1.6 km)", "We walked for a <b>mile</b>."),
 "final": ("FAY-nıl", "last; coming at the end", "This is the <b>final</b> question."),
 "club": ("KLAB", "a group of people with a shared interest", "He joined the chess <b>club</b>."),
 "dinner": ("Dİ-nır", "the main meal of the evening", "We have <b>dinner</b> at seven."),
 "today": ("tı-DEY", "on this day", "<b>Today</b> is Monday."),
 "other": ("A-dır", "different; the second of two", "Where is my <b>other</b> shoe?"),
 "maybe": ("MEY-bi", "perhaps; possibly", "<b>Maybe</b> we'll go to the beach."),
 "repeat": ("ri-PİİT", "to say or do again", "Can you <b>repeat</b> the question?"),
 "face": ("FEYS", "the front of your head; to deal with", "She has a friendly <b>face</b>."),
 "coffee": ("KO-fi", "a hot drink made from beans", "I drink <b>coffee</b> every morning."),
 "because": ("bi-KOZ", "for the reason that", "I'm tired <b>because</b> I worked all day."),
 "gym": ("CİM", "a place for exercise and sport", "He goes to the <b>gym</b> after work."),
 "plane": ("PLEYN", "a vehicle that flies", "Our <b>plane</b> leaves at noon."),
 "train": ("TREYN", "a line of railway cars; to practise", "We took the <b>train</b> to İzmir."),
 "its": ("İTS", "belonging to it", "The dog wagged <b>its</b> tail."),
 "hair": ("HE-ır", "what grows on your head", "She has long black <b>hair</b>."),
 "lion": ("LA-yın", "a large wild cat", "The <b>lion</b> is a strong animal."),
 "milk": ("MİLK", "a white drink that comes from cows", "Add some <b>milk</b> to my tea."),
 "prepare": ("pri-PE-ır", "to get something ready", "I need to <b>prepare</b> for the exam."),
 "potato": ("pı-TEY-tou", "a round vegetable that grows underground", "We had <b>potatoes</b> for dinner."),
 "happen": ("HE-pın", "to take place; to occur", "What will <b>happen</b> next?"),
 "homework": ("HOUM-uörk", "school work done at home", "Have you done your <b>homework</b>?"),
 "with": ("UİT", "together; using something", "Come <b>with</b> me to the shop."),
 "feeling": ("Fİİ-ling", "an emotion", "I have a good <b>feeling</b> about this."),
 "far": ("FAR", "a long distance away", "The station is not <b>far</b> from here."),
 "snow": ("SNOU", "soft white pieces of frozen water", "The children play in the <b>snow</b>."),
 "vacation": ("vı-KEY-şın", "a holiday", "They are on <b>vacation</b> in Bodrum."),
 "read": ("RİİD", "to look at and understand words", "I <b>read</b> a book every week."),
 "need": ("NİİD", "to require something", "I <b>need</b> some help with this."),
 "centre": ("SEN-tır", "the middle of something", "The shop is in the town <b>centre</b>."),
 "boy": ("BOY", "a young male person", "The <b>boy</b> is playing with a ball."),
 "fly": ("FLAY", "to move through the air; an insect", "Birds <b>fly</b> south in winter."),
 "desk": ("DESK", "a table for writing or working", "Put your books on the <b>desk</b>."),
 "only": ("OUN-li", "no more than; just", "I have <b>only</b> one brother."),
 "fall": ("FOL", "to drop down; autumn", "Be careful not to <b>fall</b>."),
 "friendly": ("FREND-li", "kind and pleasant", "Our neighbours are very <b>friendly</b>."),
 "woman": ("UU-mın", "an adult female person", "That <b>woman</b> is a doctor."),
 "compare": ("kım-PE-ır", "to look at how things are similar or different", "<b>Compare</b> these two photos."),
 "true": ("TRU", "correct; real", "Is this story <b>true</b>?"),
 "create": ("kri-EYT", "to make something new", "Artists <b>create</b> beautiful things."),
 "personal": ("PÖR-sı-nıl", "belonging to one person; private", "This is my <b>personal</b> opinion."),
 "sorry": ("SO-ri", "feeling sad; used to apologise", "I'm <b>sorry</b> I'm late."),
 "let": ("LET", "to allow", "<b>Let</b> me help you."),
 "leg": ("LEG", "the part of the body you walk on", "My <b>legs</b> hurt after the run."),
 "office": ("O-fis", "a place where people work at desks", "She works in an <b>office</b>."),
 "food": ("FUD", "things people and animals eat", "Turkish <b>food</b> is delicious."),
 "local": ("LOU-kıl", "belonging to a nearby area", "We shop at the <b>local</b> market."),
 "change": ("ÇEYNC", "to make or become different", "Let's <b>change</b> the plan."),
 "sit": ("SİT", "to rest on a seat", "Please <b>sit</b> down."),
}
