# -*- coding: utf-8 -*-
# Grup 5 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 5
DATA = {
 "afternoon": ("af-tır-NUN", "the time between noon and evening", "We play football in the <b>afternoon</b>."),
 "shop": ("ŞOP", "a place where you buy things", "I bought bread at the <b>shop</b>."),
 "water": ("UO-tır", "the clear liquid we drink", "Please give me a glass of <b>water</b>."),
 "son": ("SAN", "someone's male child", "Their <b>son</b> is five years old."),
 "pound": ("PAUND", "the money used in Britain", "The book costs ten <b>pounds</b>."),
 "fact": ("FEKT", "something that is true", "It is a <b>fact</b> that the sun is a star."),
 "goodbye": ("gud-BAY", "what you say when you leave", "She waved and said <b>goodbye</b>."),
 "late": ("LEYT", "after the usual time", "Sorry, I'm <b>late</b>."),
 "just": ("CAST", "only; a moment ago", "I <b>just</b> finished my work."),
 "internet": ("İN-tır-net", "the global computer network", "I found the recipe on the <b>internet</b>."),
 "April": ("EYP-rıl", "the fourth month of the year", "It often rains in <b>April</b>."),
 "terrible": ("TE-rı-bıl", "very bad", "The weather was <b>terrible</b> yesterday."),
 "plant": ("PLANT", "a living thing that grows in soil; to put in the ground", "Water the <b>plant</b> every day."),
 "different": ("DİF-rınt", "not the same", "These two bags are <b>different</b>."),
 "boyfriend": ("BOY-frend", "a male romantic partner", "Her <b>boyfriend</b> is very kind."),
 "guess": ("GES", "to give an answer you are not sure of", "Can you <b>guess</b> my age?"),
 "sport": ("SPORT", "a game with physical activity", "Football is a popular <b>sport</b>."),
 "skirt": ("SKÖRT", "clothing worn from the waist down", "She wore a long <b>skirt</b>."),
 "cake": ("KEYK", "a sweet baked food", "We ate a chocolate <b>cake</b>."),
 "member": ("MEM-bır", "a person who belongs to a group", "He is a <b>member</b> of the team."),
 "radio": ("REY-di-ou", "a device that plays sound from stations", "I listen to the <b>radio</b> in the car."),
 "something": ("SAM-ting", "a thing that is not named", "I want <b>something</b> to eat."),
 "customer": ("KAS-tı-mır", "a person who buys things", "The shop has many <b>customers</b>."),
 "sandwich": ("SEN-uiç", "food between two pieces of bread", "I made a cheese <b>sandwich</b>."),
 "land": ("LEND", "the ground; to come down", "The plane will <b>land</b> soon."),
 "on": ("ON", "touching the top of; working", "The book is <b>on</b> the table."),
 "by": ("BAY", "near; using; done through", "The letter was written <b>by</b> hand."),
 "paper": ("PEY-pır", "thin material for writing; a newspaper", "Write your name on the <b>paper</b>."),
 "three": ("TRİİ", "the number 3", "I have <b>three</b> cats."),
 "description": ("dis-KRİP-şın", "words that tell what something is like", "Give a short <b>description</b> of your house."),
 "quiet": ("KUA-yıt", "with little or no noise", "Please be <b>quiet</b> in the library."),
 "hey": ("HEY", "used to get someone's attention", "<b>Hey</b>, wait for me!"),
 "January": ("CEN-yu-ı-ri", "the first month of the year", "The new year starts in <b>January</b>."),
 "twenty": ("TUEN-ti", "the number 20", "There are <b>twenty</b> students in the class."),
 "check": ("ÇEK", "to look at something to make sure", "<b>Check</b> your answers before you finish."),
 "spelling": ("SPE-ling", "the way a word is written", "Her <b>spelling</b> is very good."),
 "number": ("NAM-bır", "a word or sign like 1, 2, 3", "What is your phone <b>number</b>?"),
 "how": ("HAU", "in what way", "<b>How</b> do you make tea?"),
 "hand": ("HEND", "the part of your arm with fingers", "Raise your <b>hand</b> to answer."),
 "player": ("PLEY-ır", "a person who plays a game", "He is the best <b>player</b> on the team."),
 "do": ("DU", "to perform an action", "What do you <b>do</b> at weekends?"),
 "it": ("İT", "the thing already mentioned", "I like this song; <b>it</b> is beautiful."),
 "natural": ("NE-çı-rıl", "made by nature, not by people", "Honey is a <b>natural</b> food."),
 "however": ("hau-E-vır", "but; in spite of that", "It was raining; <b>however</b>, we went out."),
 "bored": ("BORD", "tired because something is not interesting", "The children were <b>bored</b> at home."),
 "afraid": ("ı-FREYD", "feeling fear", "She is <b>afraid</b> of spiders."),
 "doctor": ("DOK-tır", "a person who treats sick people", "You should see a <b>doctor</b>."),
 "boot": ("BUT", "a strong shoe that covers the ankle", "Wear your <b>boots</b> in the snow."),
 "kind (type)": ("KAYND", "a type or sort", "What <b>kind</b> of food do you like?"),
 "July": ("cu-LAY", "the seventh month of the year", "It is very hot in <b>July</b>."),
 "own": ("OUN", "belonging to yourself; to have", "She has her <b>own</b> room."),
 "little": ("Lİ-tıl", "small; a small amount", "There is a <b>little</b> milk left."),
 "capital": ("KE-pi-tıl", "the main city of a country", "Ankara is the <b>capital</b> of Türkiye."),
 "bike": ("BAYK", "a bicycle", "I ride my <b>bike</b> to school."),
 "ice cream": ("ays-KRİİM", "a sweet frozen food", "Let's have some <b>ice cream</b>."),
 "future": ("FYU-çır", "the time that will come", "In the <b>future</b> I want to travel."),
 "night": ("NAYT", "the dark part of the day", "I sleep eight hours at <b>night</b>."),
 "lose": ("LUZ", "to not be able to find; to not win", "Don't <b>lose</b> your keys."),
 "tell": ("TEL", "to say something to someone", "<b>Tell</b> me about your day."),
 "finish": ("Fİ-niş", "to complete something", "I will <b>finish</b> the book tonight."),
 "until": ("ın-TİL", "up to a certain time", "Wait here <b>until</b> I come back."),
 "dad": ("DED", "father (informal)", "My <b>dad</b> works in a bank."),
 "speak": ("SPİİK", "to say words; to talk", "Do you <b>speak</b> English?"),
 "half": ("HAF", "one of two equal parts", "I ate <b>half</b> of the cake."),
 "vegetable": ("VEC-tı-bıl", "a plant used as food, like carrots", "Eat more <b>vegetables</b>."),
 "have to": ("HEF-tu", "to must do something", "I <b>have to</b> go now."),
 "bus": ("BAS", "a large vehicle that carries many people", "I take the <b>bus</b> to work."),
 "dancer": ("DAN-sır", "a person who dances", "She is a talented <b>dancer</b>."),
 "menu": ("MEN-yu", "a list of food in a restaurant", "Can I see the <b>menu</b>, please?"),
 "airport": ("E-ır-port", "a place where planes take off and land", "We arrived at the <b>airport</b> early."),
 "list": ("LİST", "words or things written one under another", "Make a shopping <b>list</b>."),
 "journey": ("CÖR-ni", "a trip from one place to another", "The <b>journey</b> took five hours."),
 "married": ("ME-rid", "having a husband or wife", "They are <b>married</b> and have two children."),
 "dark": ("DARK", "with little or no light; deep in colour", "It gets <b>dark</b> early in winter."),
 "come": ("KAM", "to move towards a place", "<b>Come</b> to my house tonight."),
 "topic": ("TO-pik", "the subject of a talk or text", "Today's <b>topic</b> is health."),
 "sentence": ("SEN-tıns", "a group of words that makes sense; a punishment", "Write a <b>sentence</b> with this word."),
 "way": ("UEY", "a road or path; a method", "Which <b>way</b> is the station?"),
 "student": ("STU-dınt", "a person who studies", "She is a good <b>student</b>."),
 "movie": ("MU-vi", "a film", "Let's watch a <b>movie</b> tonight."),
 "foot": ("FUT", "the part of your body you stand on", "My <b>foot</b> hurts."),
 "day": ("DEY", "24 hours; the time when it is light", "Have a nice <b>day</b>!"),
 "left": ("LEFT", "the opposite of right; remaining", "Turn <b>left</b> at the corner."),
 "agree": ("ı-GRİİ", "to have the same opinion", "I <b>agree</b> with you."),
 "fifth": ("FİFT", "coming after the fourth", "This is my <b>fifth</b> cup of tea."),
 "between": ("bit-UİİN", "in the space separating two things", "The bank is <b>between</b> the shop and the cafe."),
 "section": ("SEK-şın", "one part of something", "This <b>section</b> of the book is about animals."),
 "healthy": ("HEL-ti", "good for your body; not ill", "Fruit is a <b>healthy</b> snack."),
 "magazine": ("me-gı-ZİİN", "a thin book with articles and pictures", "She reads a fashion <b>magazine</b>."),
 "modern": ("MO-dın", "of the present time; new in style", "They live in a <b>modern</b> flat."),
 "around": ("ı-RAUND", "on all sides; about", "There are trees <b>around</b> the house."),
 "this": ("DİS", "the one here", "<b>This</b> is my favourite book."),
 "action": ("EK-şın", "the process of doing something", "We need to take <b>action</b> now."),
 "fire": ("FA-yır", "the flames and heat when something burns", "They sat by the <b>fire</b>."),
 "shirt": ("ŞÖRT", "clothing for the top of the body", "He wore a white <b>shirt</b>."),
 "high": ("HAY", "tall; far above the ground", "The mountain is very <b>high</b>."),
 "film": ("FİLM", "a movie", "We watched a funny <b>film</b>."),
 "early": ("ÖR-li", "before the usual time", "I woke up <b>early</b> today."),
 "trip": ("TRİP", "a short journey", "We went on a <b>trip</b> to the mountains."),
 "part": ("PART", "a piece of something", "This is the best <b>part</b> of the film."),
}
