# -*- coding: utf-8 -*-
# Grup 6 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 6
DATA = {
 "waiter": ("UEY-tır", "a person who serves food in a restaurant", "The <b>waiter</b> brought our food."),
 "go": ("GOU", "to move to another place", "Let's <b>go</b> to the park."),
 "bedroom": ("BED-rum", "a room for sleeping", "My <b>bedroom</b> is very small."),
 "success": ("sık-SES", "the good result you hoped for", "The party was a big <b>success</b>."),
 "pool": ("PUL", "a place filled with water for swimming", "The children swam in the <b>pool</b>."),
 "about": ("ı-BAUT", "on the subject of; nearly", "This book is <b>about</b> animals."),
 "also": ("OL-sou", "in addition; too", "She sings and <b>also</b> plays the piano."),
 "tall": ("TOL", "high from top to bottom", "He is very <b>tall</b>."),
 "laugh": ("LAF", "to make sounds because something is funny", "The joke made everyone <b>laugh</b>."),
 "share": ("ŞE-ır", "to give a part to others", "Let's <b>share</b> the pizza."),
 "give": ("GİV", "to hand something to someone", "Please <b>give</b> me the salt."),
 "warm": ("UORM", "a little hot; pleasant", "The water is nice and <b>warm</b>."),
 "bad": ("BED", "not good", "Smoking is <b>bad</b> for you."),
 "strong": ("STRONG", "having power; not weak", "He is <b>strong</b> enough to lift the box."),
 "slow": ("SLOU", "not fast", "The bus was very <b>slow</b> today."),
 "nose": ("NOUZ", "the part of your face used for smelling", "The rabbit has a small <b>nose</b>."),
 "discuss": ("dis-KAS", "to talk about something with others", "Let's <b>discuss</b> the plan."),
 "head": ("HED", "the top part of your body", "He hurt his <b>head</b>."),
 "down": ("DAUN", "towards a lower place", "The ball rolled <b>down</b> the hill."),
 "first": ("FÖRST", "coming before all others", "January is the <b>first</b> month."),
 "fifteen": ("fif-TİİN", "the number 15", "She is <b>fifteen</b> years old."),
 "we": ("Uİİ", "I and other people", "<b>We</b> are going to the cinema."),
 "busy": ("Bİ-zi", "having a lot to do", "I'm very <b>busy</b> this week."),
 "camera": ("KEM-rı", "a device for taking photos", "She bought a new <b>camera</b>."),
 "wait": ("UEYT", "to stay until something happens", "Please <b>wait</b> here."),
 "cheese": ("ÇİİZ", "a food made from milk", "I like <b>cheese</b> on my bread."),
 "building": ("BİL-ding", "a structure with walls and a roof", "That <b>building</b> is very old."),
 "fourth": ("FORT", "coming after the third", "April is the <b>fourth</b> month."),
 "add": ("ED", "to put one thing with another", "<b>Add</b> some sugar to the tea."),
 "friend": ("FREND", "a person you like and know well", "She is my best <b>friend</b>."),
 "the": ("Dİİ", "used before a known noun", "Please close <b>the</b> door."),
 "passport": ("PAS-port", "a document for foreign travel", "Don't forget your <b>passport</b>."),
 "flat": ("FLET", "a set of rooms to live in; level", "They live in a small <b>flat</b>."),
 "hundred": ("HAND-rıd", "the number 100", "There are a <b>hundred</b> people here."),
 "together": ("tı-GE-dır", "with each other", "We study <b>together</b> after school."),
 "street": ("STRİİT", "a road in a town with houses", "Cross the <b>street</b> carefully."),
 "her": ("HÖR", "belonging to a female; the female", "I gave <b>her</b> a gift."),
 "sure": ("ŞOR", "certain; without doubt", "Are you <b>sure</b> about the answer?"),
 "television": ("TE-li-vij-ın", "a device for watching programmes", "Turn off the <b>television</b>."),
 "nineteen": ("nayn-TİİN", "the number 19", "My brother is <b>nineteen</b>."),
 "you": ("YU", "the person being spoken to", "<b>You</b> are a good friend."),
 "better": ("BE-tır", "of higher quality", "This pen is <b>better</b> than that one."),
 "bring": ("BRİNG", "to carry something to a place", "<b>Bring</b> your books tomorrow."),
 "than": ("DEN", "used to compare two things", "She is taller <b>than</b> me."),
 "address": ("ıd-RES", "where a person lives", "Write your <b>address</b> here."),
 "best": ("BEST", "better than all others", "This is the <b>best</b> day of my life."),
 "out": ("AUT", "away from inside", "Let's go <b>out</b> for dinner."),
 "meat": ("MİİT", "the flesh of animals eaten as food", "I don't eat <b>meat</b>."),
 "free": ("FRİİ", "able to do what you want; costing nothing", "The tickets are <b>free</b>."),
 "chart": ("ÇART", "a drawing that shows information", "Look at the <b>chart</b> on the wall."),
 "thanks": ("TENKS", "a way to say thank you", "<b>Thanks</b> for your help!"),
 "sound": ("SAUND", "something you hear", "I heard a strange <b>sound</b>."),
 "event": ("i-VENT", "something that happens", "The concert was a big <b>event</b>."),
 "pepper": ("PE-pır", "a spice; a vegetable", "Add salt and <b>pepper</b> to the soup."),
 "dish": ("DİŞ", "a type of food; a plate", "This <b>dish</b> is very tasty."),
 "farm": ("FARM", "land for growing crops and keeping animals", "They live on a <b>farm</b>."),
 "third": ("TÖRD", "coming after the second", "March is the <b>third</b> month."),
 "of": ("OV", "belonging to; part of", "The colour <b>of</b> the sky is blue."),
 "white": ("UAYT", "the colour of snow", "She wore a <b>white</b> dress."),
 "black": ("BLEK", "the darkest colour", "He has <b>black</b> hair."),
 "art": ("ART", "paintings, drawings and other creative work", "I love modern <b>art</b>."),
 "tennis": ("TE-nis", "a sport played with rackets and a ball", "They play <b>tennis</b> on Sundays."),
 "car": ("KAR", "a vehicle with four wheels", "My father has a red <b>car</b>."),
 "key": ("Kİİ", "a metal thing that opens locks; a button", "I lost my house <b>key</b>."),
 "enough": ("i-NAF", "as much as needed", "We have <b>enough</b> food for everyone."),
 "room": ("RUM", "a space inside a building; space", "There is no <b>room</b> in the car."),
 "similar": ("Sİ-mı-lır", "almost the same", "Our ideas are <b>similar</b>."),
 "dear": ("Dİ-ır", "loved; used to start a letter", "<b>Dear</b> Ali, how are you?"),
 "birthday": ("BÖRT-dey", "the day you were born", "Happy <b>birthday</b>!"),
 "no": ("NOU", "used to refuse or deny", "<b>No</b>, thank you."),
 "people": ("PİİP-ıl", "more than one person", "Many <b>people</b> came to the party."),
 "spend": ("SPEND", "to use money or time", "I <b>spend</b> too much money on books."),
 "so": ("SOU", "for that reason; very", "It was late, <b>so</b> we went home."),
 "next to": ("NEKST-tu", "beside", "The bank is <b>next to</b> the school."),
 "more": ("MOR", "a larger amount", "Would you like <b>more</b> tea?"),
 "post": ("POUST", "the mail system; to send; a pole", "I'll <b>post</b> the letter today."),
 "bath": ("BAT", "washing your whole body in a tub", "She takes a <b>bath</b> every evening."),
 "get": ("GET", "to receive or obtain; to become", "I want to <b>get</b> a new phone."),
 "quick": ("KUİK", "fast; taking little time", "Let's have a <b>quick</b> lunch."),
 "our": ("A-uır", "belonging to us", "This is <b>our</b> house."),
 "stop": ("STOP", "to end movement or action", "The car <b>stopped</b> at the light."),
 "during": ("DYU-ring", "all through a period of time", "Don't talk <b>during</b> the film."),
 "forty": ("FOR-ti", "the number 40", "My teacher is <b>forty</b> years old."),
 "programme": ("PROU-grem", "a show on TV or radio; a plan", "This TV <b>programme</b> is funny."),
 "common": ("KO-mın", "happening often; shared", "Rain is <b>common</b> in spring."),
 "mum": ("MAM", "mother (informal)", "My <b>mum</b> cooks dinner."),
 "partner": ("PART-nır", "a person you do something with", "Choose a <b>partner</b> for the game."),
 "rain": ("REYN", "water that falls from clouds", "Take an umbrella; it might <b>rain</b>."),
 "flight": ("FLAYT", "a journey by plane", "Our <b>flight</b> was two hours long."),
 "meal": ("MİİL", "the food eaten at one time", "Dinner is my favourite <b>meal</b>."),
 "shoe": ("ŞU", "something you wear on your foot", "I need a new pair of <b>shoes</b>."),
 "island": ("AY-lınd", "land with water all around it", "They live on a small <b>island</b>."),
 "above": ("ı-BAV", "higher than; over", "The lamp hangs <b>above</b> the table."),
 "title": ("TAY-tıl", "the name of a book or film", "What is the <b>title</b> of this song?"),
 "correct": ("kı-REKT", "right; without mistakes", "Your answer is <b>correct</b>."),
 "Wednesday": ("UENZ-dey", "the day after Tuesday", "We have a meeting on <b>Wednesday</b>."),
 "think": ("TİNK", "to use your mind", "I <b>think</b> it will rain."),
 "dress": ("DRES", "a piece of women's clothing; to put on clothes", "She bought a new <b>dress</b>."),
 "mountain": ("MAUN-tın", "a very high hill", "We climbed the <b>mountain</b>."),
 "return": ("ri-TÖRN", "to come back; to give back", "I will <b>return</b> the book tomorrow."),
}
