# -*- coding: utf-8 -*-
# Grup 7 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 7
DATA = {
 "really": ("Rİ-ı-li", "in fact; very much", "I <b>really</b> like this song."),
 "could": ("KUD", "was able to; used for polite requests", "<b>Could</b> you help me, please?"),
 "even": ("İİ-vın", "used to show something surprising", "He didn't <b>even</b> say hello."),
 "wonderful": ("UAN-dır-fıl", "very good; excellent", "We had a <b>wonderful</b> holiday."),
 "again": ("ı-GEYN", "one more time", "Please say it <b>again</b>."),
 "order": ("O-dır", "a request for goods; a command; neat arrangement", "May I take your <b>order</b>?"),
 "back": ("BEK", "the rear part; returning", "My <b>back</b> hurts a little."),
 "quickly": ("KUİK-li", "in a fast way", "She ran <b>quickly</b> to the bus."),
 "pair": ("PE-ır", "two things that go together", "I bought a <b>pair</b> of shoes."),
 "main": ("MEYN", "most important", "The <b>main</b> road is very busy."),
 "bicycle": ("BAY-si-kıl", "a two-wheeled vehicle you pedal", "He rides his <b>bicycle</b> to work."),
 "expensive": ("iks-PEN-siv", "costing a lot of money", "This watch is very <b>expensive</b>."),
 "to": ("TU", "in the direction of", "We are going <b>to</b> the shop."),
 "time": ("TAYM", "what clocks measure; an occasion", "What <b>time</b> is it?"),
 "date": ("DEYT", "a day of the month; a meeting", "What is the <b>date</b> today?"),
 "sun": ("SAN", "the star that gives us light and heat", "The <b>sun</b> is very bright today."),
 "city": ("Sİ-ti", "a large town", "İstanbul is a huge <b>city</b>."),
 "where": ("UE-ır", "in or to what place", "<b>Where</b> do you live?"),
 "station": ("STEY-şın", "a place where trains or buses stop", "I'll meet you at the <b>station</b>."),
 "real": ("Rİ-ıl", "true; not fake", "Is that a <b>real</b> diamond?"),
 "university": ("yu-ni-VÖR-sı-ti", "a place of higher education", "She studies at a <b>university</b>."),
 "exercise": ("EK-sır-sayz", "physical activity; a practice task", "Do this <b>exercise</b> every morning."),
 "butter": ("BA-tır", "a yellow food made from milk", "Spread some <b>butter</b> on the bread."),
 "hate": ("HEYT", "to dislike very strongly", "I <b>hate</b> getting up early."),
 "keep": ("KİİP", "to have and not give away; to continue", "You can <b>keep</b> the book."),
 "beautiful": ("BYU-ti-fıl", "very pretty; lovely", "What a <b>beautiful</b> garden!"),
 "break": ("BREYK", "to make into pieces; a short rest", "Don't <b>break</b> the glass."),
 "banana": ("bı-NA-nı", "a long yellow fruit", "Monkeys love <b>bananas</b>."),
 "million": ("MİL-yın", "the number 1,000,000", "The city has a <b>million</b> people."),
 "large": ("LARC", "big in size", "They have a <b>large</b> house."),
 "she": ("Şİİ", "the female already mentioned", "<b>She</b> is my sister."),
 "him": ("HİM", "the male already mentioned (object)", "I saw <b>him</b> at the park."),
 "listen": ("Lİ-sın", "to pay attention to sound", "<b>Listen</b> to the teacher."),
 "wall": ("UOL", "the side of a room or building", "There is a picture on the <b>wall</b>."),
 "box": ("BOKS", "a container with straight sides", "Put the toys in the <b>box</b>."),
 "describe": ("dis-KRAYB", "to say what something is like", "Can you <b>describe</b> your teacher?"),
 "kitchen": ("Kİ-çin", "the room where you cook", "She is cooking in the <b>kitchen</b>."),
 "relax": ("ri-LEKS", "to rest and feel calm", "I <b>relax</b> by reading books."),
 "everyone": ("EV-ri-uan", "every person", "<b>Everyone</b> enjoyed the film."),
 "moment": ("MOU-mınt", "a very short time", "Wait a <b>moment</b>, please."),
 "pink": ("PİNK", "a light red colour", "She likes <b>pink</b> flowers."),
 "photograph": ("FOU-tı-graf", "a picture made with a camera", "This <b>photograph</b> is very old."),
 "cheap": ("ÇİİP", "not expensive", "These shoes are very <b>cheap</b>."),
 "weekend": ("uik-END", "Saturday and Sunday", "What did you do at the <b>weekend</b>?"),
 "drink": ("DRİNK", "to take liquid into your body; a liquid", "<b>Drink</b> more water."),
 "sing": ("SİNG", "to make music with your voice", "She likes to <b>sing</b> in the shower."),
 "fine": ("FAYN", "good; well; a money punishment", "I'm <b>fine</b>, thank you."),
 "evening": ("İİV-ning", "the time after the afternoon", "We watch TV in the <b>evening</b>."),
 "note": ("NOUT", "a short written message", "She left a <b>note</b> on the table."),
 "start": ("START", "to begin", "The film will <b>start</b> soon."),
 "guitar": ("gi-TAR", "a musical instrument with strings", "He plays the <b>guitar</b> well."),
 "thirsty": ("TÖRS-ti", "needing to drink", "I'm very <b>thirsty</b>."),
 "begin": ("bi-GİN", "to start", "Let's <b>begin</b> the lesson."),
 "thirteen": ("tör-TİİN", "the number 13", "My cousin is <b>thirteen</b>."),
 "be": ("Bİİ", "to exist; used to describe things", "I want to <b>be</b> a doctor."),
 "rice": ("RAYS", "small white grains eaten as food", "We had chicken and <b>rice</b>."),
 "believe": ("bi-LİİV", "to think something is true", "I <b>believe</b> you."),
 "actress": ("EKT-rıs", "a woman who acts in films or plays", "She is a famous <b>actress</b>."),
 "which": ("UİÇ", "what one of a group", "<b>Which</b> book do you want?"),
 "say": ("SEY", "to speak words", "What did you <b>say</b>?"),
 "eleven": ("i-LE-vın", "the number 11", "The shop opens at <b>eleven</b>."),
 "park": ("PARK", "a public green area; to leave a car", "We walked in the <b>park</b>."),
 "poor": ("PU-ır", "having little money; unlucky", "The <b>poor</b> man had no home."),
 "all": ("OL", "every one; the whole", "<b>All</b> the students passed."),
 "hat": ("HET", "clothing for your head", "He wears a <b>hat</b> in the sun."),
 "sugar": ("ŞU-gır", "a sweet white food", "I take <b>sugar</b> in my coffee."),
 "egg": ("EG", "an oval food from a hen", "I eat an <b>egg</b> for breakfast."),
 "exciting": ("ik-SAY-ting", "making you feel happy and interested", "The match was very <b>exciting</b>."),
 "card": ("KARD", "a small piece of stiff paper or plastic", "I sent her a birthday <b>card</b>."),
 "May": ("MEY", "the fifth month of the year", "Flowers bloom in <b>May</b>."),
 "now": ("NAU", "at this moment", "Let's start <b>now</b>."),
 "lot": ("LOT", "a large amount or number", "There is a <b>lot</b> of work to do."),
 "someone": ("SAM-uan", "a person you do not name", "<b>Someone</b> is at the door."),
 "wife": ("UAYF", "a married woman", "His <b>wife</b> is a teacher."),
 "writer": ("RAY-tır", "a person who writes books", "She is a famous <b>writer</b>."),
 "garden": ("GAR-dın", "an area with plants near a house", "We grow tomatoes in the <b>garden</b>."),
 "difficult": ("Dİ-fi-kılt", "hard to do", "This question is <b>difficult</b>."),
 "some": ("SAM", "an amount of; a few", "I need <b>some</b> help."),
 "there": ("DE-ır", "in that place", "Put the box over <b>there</b>."),
 "lie": ("LAY", "to rest your body flat; to say something untrue", "I like to <b>lie</b> on the grass."),
 "purple": ("PÖR-pıl", "a colour between red and blue", "She painted the wall <b>purple</b>."),
 "OK": ("ou-KEY", "used to agree; fine", "<b>OK</b>, let's go."),
 "test": ("TEST", "a set of questions to check knowledge", "We have an English <b>test</b> today."),
 "cost": ("KOST", "the price; to have a price", "How much does it <b>cost</b>?"),
 "painting": ("PEYN-ting", "a picture made with paint", "This <b>painting</b> is beautiful."),
 "money": ("MA-ni", "coins and notes used to buy things", "I don't have much <b>money</b>."),
 "seven": ("SE-vın", "the number 7", "There are <b>seven</b> days in a week."),
 "century": ("SEN-çı-ri", "a period of 100 years", "This castle is a <b>century</b> old."),
 "CD": ("si-Dİİ", "a disc that stores music or data", "She bought a new <b>CD</b>."),
 "onion": ("AN-yın", "a round vegetable with a strong taste", "Cut the <b>onion</b> into small pieces."),
 "beginning": ("bi-Gİ-ning", "the first part; the start", "The film was quiet at the <b>beginning</b>."),
 "much": ("MAÇ", "a large amount", "Thank you very <b>much</b>."),
 "boat": ("BOUT", "a small vehicle for travelling on water", "We crossed the lake by <b>boat</b>."),
 "usually": ("YU-jı-li", "most of the time", "I <b>usually</b> get up at seven."),
 "then": ("DEN", "after that; at that time", "We had lunch and <b>then</b> went home."),
 "every": ("EV-ri", "each one", "She calls me <b>every</b> day."),
 "bathroom": ("BAT-rum", "the room with a toilet and bath", "The <b>bathroom</b> is upstairs."),
 "ever": ("E-vır", "at any time", "Have you <b>ever</b> been to Paris?"),
 "full": ("FUL", "holding as much as possible", "The glass is <b>full</b> of water."),
 "hospital": ("HOS-pi-tıl", "a place where sick people are treated", "He is in <b>hospital</b> after the accident."),
}
