# -*- coding: utf-8 -*-
# Grup 8 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 8
DATA = {
 "stand": ("STEND", "to be on your feet; to bear", "Please <b>stand</b> up."),
 "air": ("E-ır", "what we breathe", "The mountain <b>air</b> is fresh."),
 "music": ("MYU-zik", "sounds made by instruments or voices", "I listen to <b>music</b> every day."),
 "grandparent": ("GREN-pe-rınt", "a parent of your parent", "My <b>grandparent</b> tells great stories."),
 "present": ("PREZ-ınt", "a gift; the current time; to give", "She gave me a birthday <b>present</b>."),
 "a, an": ("ı / EN", "used before a noun to mean one", "I have <b>a</b> pen and an apple."),
 "once": ("UANS", "one time; in the past", "I visit my aunt <b>once</b> a month."),
 "orange": ("O-rinc", "a round citrus fruit; a colour", "I drink <b>orange</b> juice."),
 "cook": ("KUK", "to make food with heat; a person who cooks", "My mother can <b>cook</b> well."),
 "ice": ("AYS", "frozen water", "Put some <b>ice</b> in my drink."),
 "sweater": ("SUE-tır", "a warm knitted top", "Wear a <b>sweater</b>; it's cold."),
 "win": ("UİN", "to be first in a game or race", "I hope we <b>win</b> the match."),
 "too": ("TU", "also; more than needed", "This coffee is <b>too</b> hot."),
 "town": ("TAUN", "a place with houses and shops, smaller than a city", "We live in a small <b>town</b>."),
 "yourself": ("yır-SELF", "your own person", "Look after <b>yourself</b>."),
 "fourteen": ("for-TİİN", "the number 14", "She is <b>fourteen</b> years old."),
 "remember": ("ri-MEM-bır", "to keep in your mind; to not forget", "I can't <b>remember</b> his name."),
 "business": ("BİZ-nıs", "buying and selling; a company", "He runs a small <b>business</b>."),
 "ninety": ("NAYN-ti", "the number 90", "My grandfather is <b>ninety</b>."),
 "dance": ("DANS", "to move your body to music", "They love to <b>dance</b> at parties."),
 "newspaper": ("NUZ-pey-pır", "printed sheets with news", "He reads the <b>newspaper</b> every morning."),
 "ten": ("TEN", "the number 10", "I have <b>ten</b> fingers."),
 "across": ("ık-ROS", "from one side to the other", "We walked <b>across</b> the bridge."),
 "T-shirt": ("Tİİ-şört", "a short-sleeved cotton top", "He wore a blue <b>T-shirt</b>."),
 "complete": ("kım-PLİİT", "to finish; whole", "Please <b>complete</b> the form."),
 "long": ("LONG", "measuring a lot from end to end", "She has <b>long</b> hair."),
 "use": ("YUS", "to do something with a tool or thing", "Can I <b>use</b> your pen?"),
 "your": ("YOR", "belonging to you", "Is this <b>your</b> bag?"),
 "weather": ("UE-dır", "the state of the sky (rain, sun...)", "The <b>weather</b> is nice today."),
 "sad": ("SED", "unhappy", "She felt <b>sad</b> when her friend left."),
 "traffic": ("TRE-fik", "vehicles moving on roads", "There is a lot of <b>traffic</b> in the morning."),
 "very": ("VE-ri", "to a high degree", "It is <b>very</b> cold outside."),
 "sixty": ("SİKS-ti", "the number 60", "There are <b>sixty</b> minutes in an hour."),
 "call": ("KOL", "to telephone; to say loudly; to name", "I'll <b>call</b> you tonight."),
 "toilet": ("TOY-lıt", "a bowl for waste; a small room with it", "Where is the <b>toilet</b>?"),
 "advice": ("ıd-VAYS", "ideas about what someone should do", "She gave me good <b>advice</b>."),
 "parent": ("PE-rınt", "a mother or father", "Each <b>parent</b> loves their child."),
 "extra": ("EKS-trı", "more than usual; additional", "Do you want an <b>extra</b> blanket?"),
 "old": ("OULD", "having lived a long time; not new", "My grandmother is very <b>old</b>."),
 "minute": ("Mİ-nit", "a unit of time (60 seconds)", "Wait a <b>minute</b>, please."),
 "summer": ("SA-mır", "the warmest season", "We go swimming in <b>summer</b>."),
 "include": ("in-KLUD", "to have as a part", "Does the price <b>include</b> breakfast?"),
 "interesting": ("İN-tres-ting", "making you want to know more", "This is an <b>interesting</b> book."),
 "bed": ("BED", "furniture you sleep on", "I go to <b>bed</b> at eleven."),
 "practise": ("PREK-tis", "to do something often to get better", "You must <b>practise</b> the piano."),
 "website": ("UEB-sayt", "a place on the internet", "Visit our <b>website</b> for more information."),
 "six": ("SİKS", "the number 6", "I woke up at <b>six</b> o'clock."),
 "week": ("UİİK", "a period of seven days", "I work five days a <b>week</b>."),
 "report": ("ri-PORT", "a written or spoken account; to tell about", "She wrote a <b>report</b> about the trip."),
 "colour": ("KA-lır", "red, blue, green, and so on", "What is your favourite <b>colour</b>?"),
 "buy": ("BAY", "to get something by paying", "I want to <b>buy</b> a new coat."),
 "autumn": ("O-tım", "the season after summer", "Leaves fall in <b>autumn</b>."),
 "born": ("BORN", "brought into life", "She was <b>born</b> in İzmir."),
 "near": ("Nİ-ır", "close to", "The shop is <b>near</b> my house."),
 "no one": ("NOU-uan", "not any person", "<b>No one</b> answered the phone."),
 "choose": ("ÇUZ", "to pick one thing from many", "You can <b>choose</b> any cake you like."),
 "through": ("TRU", "from one side to the other; by way of", "The train went <b>through</b> a tunnel."),
 "up": ("AP", "towards a higher place", "Look <b>up</b> at the sky."),
 "juice": ("CUS", "the liquid from fruit", "I drink apple <b>juice</b>."),
 "please": ("PLİİZ", "used to be polite when asking; to make happy", "Can I have some water, <b>please</b>?"),
 "line": ("LAYN", "a long thin mark; a row", "Draw a straight <b>line</b>."),
 "point": ("POYNT", "a dot; a place; to show with a finger", "That's a good <b>point</b>."),
 "fast": ("FAST", "moving quickly", "He is a <b>fast</b> runner."),
 "or": ("OR", "used between choices", "Would you like tea <b>or</b> coffee?"),
 "window": ("UİN-dou", "an opening with glass in a wall", "Open the <b>window</b>, please."),
 "telephone": ("TE-li-foun", "a device for talking to people far away", "The <b>telephone</b> is ringing."),
 "excited": ("ik-SAY-tid", "very happy and interested", "The kids are <b>excited</b> about the trip."),
 "year": ("Yİ-ır", "a period of twelve months", "I visit them every <b>year</b>."),
 "father": ("FA-dır", "a male parent", "My <b>father</b> is a teacher."),
 "clean": ("KLİİN", "not dirty; to remove dirt", "Keep your room <b>clean</b>."),
 "meet": ("MİİT", "to come together with someone", "Let's <b>meet</b> at the cafe."),
 "salt": ("SOLT", "a white substance that makes food tasty", "Add a little <b>salt</b> to the soup."),
 "job": ("COB", "the work a person does for money", "She has a good <b>job</b>."),
 "news": ("NUZ", "information about recent events", "Did you hear the <b>news</b>?"),
 "sell": ("SEL", "to give something for money", "They <b>sell</b> fruit at the market."),
 "draw": ("DRO", "to make a picture with a pen; to end equal", "Children love to <b>draw</b>."),
 "girl": ("GÖRL", "a young female person", "The <b>girl</b> is reading a book."),
 "story": ("STO-ri", "a tale; a floor of a building", "Grandma told us a <b>story</b>."),
 "person": ("PÖR-sın", "a human being", "He is a kind <b>person</b>."),
 "downstairs": ("daun-STE-ırz", "on or to a lower floor", "The kitchen is <b>downstairs</b>."),
 "beer": ("Bİ-ır", "an alcoholic drink made from grain", "He drank a glass of <b>beer</b>."),
 "feel": ("FİİL", "to have an emotion or sense", "I <b>feel</b> happy today."),
 "June": ("CUN", "the sixth month of the year", "School ends in <b>June</b>."),
 "girlfriend": ("GÖRL-frend", "a female romantic partner", "His <b>girlfriend</b> is a nurse."),
 "work": ("UÖRK", "to do a job; the job itself", "I <b>work</b> in a hospital."),
 "elephant": ("E-li-fınt", "a very large grey animal with a trunk", "The <b>elephant</b> is the biggest land animal."),
 "bank (money)": ("BENK", "a place that keeps people's money", "I need to go to the <b>bank</b>."),
 "thirty": ("TÖR-ti", "the number 30", "There are <b>thirty</b> days in June."),
 "great": ("GREYT", "very good; very big", "We had a <b>great</b> time."),
 "sleep": ("SLİİP", "to rest with your eyes closed", "Babies <b>sleep</b> a lot."),
 "each": ("İİÇ", "every one of two or more", "<b>Each</b> student has a book."),
 "party": ("PAR-ti", "a fun social event", "We are having a <b>party</b> on Saturday."),
 "snake": ("SNEYK", "a long animal with no legs", "A <b>snake</b> moved through the grass."),
 "run": ("RAN", "to move fast on foot; to manage", "I <b>run</b> in the park every morning."),
 "festival": ("FES-ti-vıl", "a special time of celebration", "The music <b>festival</b> lasts three days."),
 "improve": ("im-PRUV", "to make or become better", "I want to <b>improve</b> my English."),
 "message": ("ME-sic", "written or spoken information you send", "I sent her a <b>message</b>."),
 "cool": ("KUL", "a little cold; fashionable", "The evening air was <b>cool</b>."),
 "yes": ("YES", "used to agree or say something is true", "<b>Yes</b>, I would love to come."),
 "Sunday": ("SAN-dey", "the day after Saturday", "We rest on <b>Sunday</b>."),
}
