# -*- coding: utf-8 -*-
# Grup 9 (A1) — okunuş / İngilizce açıklama / örnek cümle
GRUP_NO = 9
DATA = {
 "online": ("on-LAYN", "connected to the internet", "I bought the tickets <b>online</b>."),
 "cream": ("KRİİM", "the thick part of milk", "I like <b>cream</b> on my cake."),
 "try": ("TRAY", "to attempt; to test", "<b>Try</b> to finish before lunch."),
 "quarter": ("KUO-tır", "one of four equal parts", "It's a <b>quarter</b> past three."),
 "below": ("bi-LOU", "in a lower place", "The sun went <b>below</b> the hills."),
 "school": ("SKUL", "a place where children learn", "My children go to <b>school</b> by bus."),
 "skill": ("SKİL", "the ability to do something well", "Cooking is a useful <b>skill</b>."),
 "why": ("UAY", "for what reason", "<b>Why</b> are you late?"),
 "February": ("FEB-ru-ı-ri", "the second month of the year", "<b>February</b> is a short month."),
 "should": ("ŞUD", "used to give advice", "You <b>should</b> drink more water."),
 "door": ("DOR", "the part you open to enter a room", "Please close the <b>door</b>."),
 "his": ("HİZ", "belonging to a male", "This is <b>his</b> bicycle."),
 "hungry": ("HANG-ri", "wanting to eat", "I'm very <b>hungry</b>."),
 "cooking": ("KU-king", "the activity of making food", "She enjoys <b>cooking</b> for friends."),
 "hotel": ("hou-TEL", "a place where you pay to stay", "We stayed in a nice <b>hotel</b>."),
 "river": ("Rİ-vır", "a large natural stream of water", "Children swam in the <b>river</b>."),
 "me": ("Mİİ", "the person speaking (object)", "Give the book to <b>me</b>."),
 "wear": ("UE-ır", "to have clothes on your body", "I <b>wear</b> a coat in winter."),
 "want": ("UONT", "to wish for something", "I <b>want</b> a cup of tea."),
 "brother": ("BRA-dır", "a male sibling", "My <b>brother</b> is older than me."),
 "without": ("uid-AUT", "not having; not with", "I can't see <b>without</b> my glasses."),
 "bird": ("BÖRD", "an animal with feathers and wings", "A <b>bird</b> was singing in the tree."),
 "follow": ("FO-lou", "to go after; to do as told", "<b>Follow</b> me to the exit."),
 "Thursday": ("TÖRZ-dey", "the day after Wednesday", "The class is on <b>Thursday</b>."),
 "eighty": ("EY-ti", "the number 80", "My grandmother is <b>eighty</b>."),
 "seventy": ("SE-vın-ti", "the number 70", "The trip costs <b>seventy</b> liras."),
 "August": ("O-gıst", "the eighth month of the year", "We go on holiday in <b>August</b>."),
 "behind": ("bi-HAYND", "at the back of", "The garden is <b>behind</b> the house."),
 "special": ("SPE-şıl", "not ordinary; important", "Today is a <b>special</b> day."),
 "design": ("di-ZAYN", "a plan or drawing; to create", "I like the <b>design</b> of this car."),
 "place": ("PLEYS", "a location; to put", "This is a quiet <b>place</b>."),
 "horse": ("HORS", "a large animal you can ride", "She rides a <b>horse</b> every weekend."),
 "reading": ("RİİD-ing", "the activity of looking at words", "<b>Reading</b> is my favourite hobby."),
 "restaurant": ("RES-tı-ront", "a place where you buy and eat meals", "We ate at an Italian <b>restaurant</b>."),
 "for": ("FOR", "meant to be given to; because of", "This gift is <b>for</b> you."),
 "paragraph": ("PE-rı-graf", "a group of sentences about one idea", "Write a short <b>paragraph</b> about your day."),
 "bill": ("BİL", "a paper showing money you must pay", "Can we have the <b>bill</b>, please?"),
 "important": ("im-POR-tınt", "mattering a lot", "Sleep is <b>important</b> for health."),
 "cat": ("KET", "a small animal often kept as a pet", "The <b>cat</b> is sleeping on the sofa."),
 "opinion": ("ı-PİN-yın", "what you think about something", "In my <b>opinion</b>, the film was boring."),
 "meeting": ("MİİT-ing", "when people come together to talk", "The <b>meeting</b> starts at nine."),
 "supermarket": ("SU-pır-mar-kit", "a large shop selling food and goods", "I buy milk at the <b>supermarket</b>."),
 "ask": ("ASK", "to say a question; to request", "May I <b>ask</b> a question?"),
 "uncle": ("ANK-ıl", "the brother of your mother or father", "My <b>uncle</b> lives abroad."),
 "fat": ("FET", "having a large body; a food substance", "Too much sugar can make you <b>fat</b>."),
 "product": ("PRO-dakt", "something made or grown to sell", "This <b>product</b> is very popular."),
 "health": ("HELT", "the condition of your body", "Exercise is good for your <b>health</b>."),
 "home": ("HOUM", "the place where you live", "I stay at <b>home</b> on Sundays."),
 "bread": ("BRED", "a food made from flour and baked", "I bought fresh <b>bread</b>."),
 "in": ("İN", "inside", "The keys are <b>in</b> my bag."),
 "both": ("BOUT", "the two together", "<b>Both</b> answers are correct."),
 "wrong": ("RONG", "not correct; not right", "You have the <b>wrong</b> number."),
 "happy": ("HE-pi", "feeling pleased", "She was <b>happy</b> to see her friends."),
 "thing": ("TİNG", "an object or matter", "What is that <b>thing</b> on the table?"),
 "drive": ("DRAYV", "to control a car", "He learned to <b>drive</b> last year."),
 "company": ("KAM-pı-ni", "a business; being with others", "She works for a big <b>company</b>."),
 "what": ("UOT", "used to ask about something", "<b>What</b> is your name?"),
 "have": ("HEV", "to own or hold", "I <b>have</b> two sisters."),
 "worker": ("UÖR-kır", "a person who works", "The factory has many <b>workers</b>."),
 "soon": ("SUN", "in a short time", "I will call you <b>soon</b>."),
 "concert": ("KON-sırt", "a live music show", "We went to a rock <b>concert</b>."),
 "umbrella": ("am-BRE-lı", "a thing that keeps rain off you", "Take an <b>umbrella</b>; it's raining."),
 "them": ("DEM", "those people or things (object)", "I gave <b>them</b> the money."),
 "actor": ("EK-tır", "a person who acts in films or plays", "He is a famous <b>actor</b>."),
 "understand": ("an-dır-STEND", "to know what something means", "I don't <b>understand</b> this word."),
 "find": ("FAYND", "to discover or locate", "I can't <b>find</b> my keys."),
 "popular": ("PO-pyu-lır", "liked by many people", "This song is very <b>popular</b>."),
 "market": ("MAR-kit", "a place to buy and sell goods", "We buy vegetables at the <b>market</b>."),
 "ear": ("İ-ır", "the part of the body you hear with", "The loud music hurt my <b>ears</b>."),
 "lesson": ("LE-sın", "a period of teaching", "The English <b>lesson</b> was fun."),
 "write": ("RAYT", "to make letters or words", "Please <b>write</b> your name here."),
 "south": ("SAUT", "the direction opposite north", "Birds fly <b>south</b> in winter."),
 "scientist": ("SA-yın-tist", "a person who studies science", "The <b>scientist</b> did an experiment."),
 "still": ("STİL", "up to now; even so", "Are you <b>still</b> at work?"),
 "difference": ("DİF-rıns", "the way things are not the same", "What is the <b>difference</b> between these two?"),
 "pen": ("PEN", "a tool for writing with ink", "Can I borrow your <b>pen</b>?"),
 "animal": ("E-ni-mıl", "a living thing that can move", "The lion is a wild <b>animal</b>."),
 "probably": ("PRO-bıb-li", "very likely", "It will <b>probably</b> rain tomorrow."),
 "nine": ("NAYN", "the number 9", "The shop closes at <b>nine</b>."),
 "end": ("END", "the last part; to finish", "We left before the <b>end</b> of the film."),
 "DVD": ("di-vi-Dİİ", "a disc that stores films", "We watched a film on <b>DVD</b>."),
 "bottle": ("BO-tıl", "a container for liquids", "She drank a <b>bottle</b> of water."),
 "any": ("E-ni", "some; even one", "Is there <b>any</b> milk left?"),
 "anything": ("E-ni-ting", "a thing of any kind", "Is there <b>anything</b> to eat?"),
 "library": ("LAYB-ri", "a place with many books to borrow", "I study at the <b>library</b>."),
 "positive": ("PO-zı-tiv", "good; hopeful; sure", "Try to stay <b>positive</b>."),
 "book": ("BUK", "pages with words to read; to reserve", "I read a good <b>book</b> last week."),
 "over": ("OU-vır", "above; finished; across", "The plane flew <b>over</b> the city."),
 "teach": ("TİİÇ", "to help someone learn", "She will <b>teach</b> us French."),
 "singer": ("SİN-gır", "a person who sings", "My favourite <b>singer</b> has a concert tonight."),
 "brown": ("BRAUN", "the colour of chocolate", "He has <b>brown</b> eyes."),
 "talk": ("TOK", "to speak; a conversation", "Let's <b>talk</b> about your plans."),
 "cinema": ("Sİ-nı-ma", "a place where you watch films", "We went to the <b>cinema</b> last night."),
 "easy": ("İİ-zi", "not difficult", "This exercise is very <b>easy</b>."),
 "exam": ("ig-ZEM", "an important test", "I passed my driving <b>exam</b>."),
 "fill": ("FİL", "to make something full", "<b>Fill</b> the glass with water."),
 "teacher": ("TİİÇ-ır", "a person who teaches", "Our <b>teacher</b> is very kind."),
 "and": ("END", "used to join words", "I like tea <b>and</b> coffee."),
 "bye": ("BAY", "a short way to say goodbye", "<b>Bye</b>, see you tomorrow!"),
 "rule": ("RUL", "an instruction about what you can do; to govern", "Follow the <b>rules</b> of the game."),
}
