# -*- coding: utf-8 -*-
"""Çok anlamlı kelimeler için her anlama bir örnek cümle.

Anahtar: (grup_no, kelime)  →  [cümle, ...]  (her cümlede <b>kelime</b>).
build_all.apply_multi_examples bunu tüm gruplara uygular (100-kelime kısıtı yok;
Grup 1/10 gibi enrich'siz gruplar da dahil). Sıra = tr alanındaki anlam sırası.
"""

EX = {
 # ——— Grup 1 (A1) ———
 (1, "live"): ["They <b>live</b> in a small village.", "The concert was shown <b>live</b> on TV."],
 (1, "will"): ["I <b>will</b> call you tomorrow.", "She has a strong <b>will</b> to win."],
 (1, "opposite"): ["'Hot' is the <b>opposite</b> of 'cold'.", "The bank is <b>opposite</b> the school."],
 (1, "course"): ["I'm taking an English <b>course</b>.", "The ship changed its <b>course</b>.", "The main <b>course</b> was chicken."],
 (1, "off"): ["Please turn <b>off</b> the light.", "The island is far <b>off</b> the coast."],
 (1, "shower"): ["I take a <b>shower</b> every morning.", "We got caught in a <b>shower</b> of rain."],
 (1, "introduce"): ["Let me <b>introduce</b> my friend Ali.", "The school will <b>introduce</b> a new rule."],
 (1, "when"): ["<b>When</b> does the film start?", "Call me <b>when</b> you arrive."],
 (1, "open"): ["The shop is <b>open</b> until nine.", "Please <b>open</b> the window."],
 (1, "match"): ["We watched the football <b>match</b>.", "He lit a <b>match</b> to start the fire.", "Your socks don't <b>match</b>."],
 (1, "space"): ["There isn't much <b>space</b> in my room.", "Astronauts travel in <b>space</b>."],
 (1, "paint"): ["The <b>paint</b> is still wet.", "They will <b>paint</b> the wall blue."],
 (1, "play"): ["The children <b>play</b> in the park.", "We saw a <b>play</b> at the theatre."],
 (1, "love"): ["I <b>love</b> Italian food.", "Their <b>love</b> lasted a lifetime."],
 (1, "show"): ["Can you <b>show</b> me the way?", "We watched a TV <b>show</b>."],
 (1, "second"): ["Wait a <b>second</b>, please.", "She came <b>second</b> in the race."],
 (1, "subject"): ["My favourite <b>subject</b> is maths.", "In this sentence, 'dog' is the <b>subject</b>.", "The plan is <b>subject</b> to change."],
 (1, "right"): ["You gave the <b>right</b> answer.", "Turn <b>right</b> at the corner.", "Everyone has the <b>right</b> to vote."],
 (1, "welcome"): ["<b>Welcome</b> to our home!", "They came out to <b>welcome</b> the guests."],
 (1, "spring"): ["Flowers bloom in <b>spring</b>.", "The <b>spring</b> in the pen is broken.", "Fresh water flowed from the <b>spring</b>."],

 # ——— Grup 2 (A1) ———
 (2, "leave"): ["We <b>leave</b> home at eight every morning.", "Please <b>leave</b> the door open."],
 (2, "table"): ["The keys are on the <b>table</b>.", "Look at the <b>table</b> of results on page five."],
 (2, "pretty"): ["What a <b>pretty</b> dress!", "The film was <b>pretty</b> good."],
 (2, "spell"): ["How do you <b>spell</b> your name?", "The witch cast a magic <b>spell</b>."],
 (2, "writing"): ["He is good at <b>writing</b> essays.", "I can't read your <b>writing</b>."],
 (2, "letter"): ["I wrote a <b>letter</b> to my grandmother.", "The word 'cat' has three <b>letters</b>."],
 (2, "watch"): ["We <b>watch</b> TV in the evening.", "He looked at his <b>watch</b>."],
 (2, "that"): ["Whose is <b>that</b> car?", "She said <b>that</b> she was tired."],
 (2, "turn"): ["<b>Turn</b> left at the bank.", "It's your <b>turn</b> to play."],
 (2, "diet"): ["A healthy <b>diet</b> is important.", "She is on a <b>diet</b> to lose weight."],
 (2, "period"): ["The Ottoman <b>period</b> lasted for centuries.", "We lived there for a short <b>period</b>.", "Put a <b>period</b> at the end of the sentence."],
 (2, "move"): ["Can you help me <b>move</b> this table?", "They will <b>move</b> to a new house."],
 (2, "look"): ["<b>Look</b> at this photo!", "You <b>look</b> tired today."],
 (2, "hard"): ["The exam was very <b>hard</b>.", "The bed was too <b>hard</b> to sleep on."],
 (2, "past"): ["Forget the <b>past</b> and look forward.", "We drove <b>past</b> the school."],
 (2, "miss"): ["I <b>miss</b> my old friends.", "Hurry, or we'll <b>miss</b> the bus."],
 (2, "study"): ["I <b>study</b> English every evening.", "A new <b>study</b> shows that coffee is healthy."],
 (2, "class"): ["My <b>class</b> has twenty students.", "I have an English <b>class</b> now."],
 (2, "well"): ["She speaks English very <b>well</b>.", "They got water from the <b>well</b>."],

 # ——— Grup 3 (A1) ———
 (3, "glass"): ["The window is made of <b>glass</b>.", "She drank a <b>glass</b> of water."],
 (3, "form"): ["Water can take the <b>form</b> of ice.", "Please fill in this <b>form</b>."],
 (3, "cup"): ["Would you like a <b>cup</b> of coffee?", "Our team won the <b>cup</b>."],
 (3, "close"): ["Please <b>close</b> the window.", "The shop is <b>close</b> to my house."],
 (3, "interest"): ["He shows great <b>interest</b> in science.", "The bank pays <b>interest</b> on savings."],
 (3, "grow"): ["Children <b>grow</b> quickly.", "They <b>grow</b> vegetables in the garden."],
 (3, "can"): ["You <b>can</b> swim very well.", "She opened a <b>can</b> of beans."],
 (3, "join"): ["Why don't you <b>join</b> our team?", "<b>Join</b> the two ropes together."],
 (3, "article"): ["I read an interesting <b>article</b> today.", "'The' is a definite <b>article</b>."],
 (3, "game"): ["Let's play a <b>game</b> after dinner.", "The football <b>game</b> starts at eight."],
 (3, "floor"): ["The toys are all over the <b>floor</b>.", "My office is on the third <b>floor</b>."],
 (3, "light"): ["Turn on the <b>light</b>, please.", "The bag is very <b>light</b>."],

 # ——— Grup 4 (A1) ———
 (4, "second"): ["Wait a <b>second</b>, please.", "She came <b>second</b> in the race."],
 (4, "type"): ["What <b>type</b> of music do you like?", "Please <b>type</b> your name here."],
 (4, "country"): ["Türkiye is a beautiful <b>country</b>.", "They live in the <b>country</b>, far from the city."],
 (4, "as"): ["She works <b>as</b> a nurse.", "<b>As</b> it was raining, we stayed home.", "She is <b>as</b> clever as her sister."],
 (4, "mean"): ["What does this word <b>mean</b>?", "Don't be so <b>mean</b> with your money."],
 (4, "object"): ["What is that strange <b>object</b>?", "Many people <b>object</b> to the new law."],
 (4, "final"): ["This is the <b>final</b> question.", "Our team reached the <b>final</b>."],
 (4, "face"): ["She has a friendly <b>face</b>.", "We must <b>face</b> the problem."],
 (4, "train"): ["We took the <b>train</b> to İzmir.", "They <b>train</b> dogs to help people."],
 (4, "fly"): ["Birds <b>fly</b> south in winter.", "A <b>fly</b> landed on the food."],
 (4, "fall"): ["Be careful not to <b>fall</b>.", "Leaves turn brown in the <b>fall</b>."],
 (4, "change"): ["Let's <b>change</b> the plan.", "There has been a big <b>change</b> in the weather."],

 # ——— Grup 5 (A1) ———
 (5, "just"): ["I want <b>just</b> a little sugar.", "She <b>just</b> left the office."],
 (5, "plant"): ["Water the <b>plant</b> every day.", "He works at a car <b>plant</b>.", "We will <b>plant</b> trees in the garden."],
 (5, "land"): ["They own a large piece of <b>land</b>.", "The plane will <b>land</b> soon."],
 (5, "on"): ["The book is <b>on</b> the table.", "The lights are <b>on</b>."],
 (5, "by"): ["The book was written <b>by</b> a famous author.", "She sat <b>by</b> the window.", "We travelled <b>by</b> train."],
 (5, "paper"): ["Write your name on the <b>paper</b>.", "I read the news in the <b>paper</b>."],
 (5, "own"): ["She has her <b>own</b> room.", "They <b>own</b> two cars."],
 (5, "little"): ["A <b>little</b> girl was crying.", "There is a <b>little</b> milk left."],
 (5, "capital"): ["Ankara is the <b>capital</b> of Türkiye.", "You need <b>capital</b> to start a business."],
 (5, "dark"): ["It gets <b>dark</b> early in winter.", "She wore a <b>dark</b> blue coat."],
 (5, "sentence"): ["Write a <b>sentence</b> with this word.", "The judge gave him a long <b>sentence</b>."],
 (5, "way"): ["Which <b>way</b> is the station?", "This is the best <b>way</b> to learn."],
 (5, "left"): ["Turn <b>left</b> at the corner.", "There is no food <b>left</b>."],
 (5, "around"): ["There are trees <b>around</b> the house.", "It costs <b>around</b> fifty liras."],

 # ——— Grup 6 (A1) ———
 (6, "about"): ["This book is <b>about</b> animals.", "It's <b>about</b> three o'clock."],
 (6, "share"): ["Let's <b>share</b> the pizza.", "She owns a <b>share</b> in the company."],
 (6, "flat"): ["They live in a small <b>flat</b>.", "The land is very <b>flat</b>."],
 (6, "free"): ["The birds are <b>free</b> to fly away.", "The tickets are <b>free</b>."],
 (6, "dish"): ["This <b>dish</b> is very tasty.", "She washed every <b>dish</b>."],
 (6, "key"): ["I lost my house <b>key</b>.", "Press the 'enter' <b>key</b>."],
 (6, "room"): ["My <b>room</b> is upstairs.", "There is no <b>room</b> in the car."],
 (6, "dear"): ["<b>Dear</b> Ali, how are you?", "That coat is too <b>dear</b> for me."],
 (6, "no"): ["<b>No</b>, thank you.", "There is <b>no</b> milk in the fridge."],
 (6, "spend"): ["I <b>spend</b> too much money on books.", "We <b>spend</b> summers by the sea."],
 (6, "so"): ["It was late, <b>so</b> we went home.", "I am <b>so</b> happy today.", "I think <b>so</b>."],
 (6, "post"): ["I'll <b>post</b> the letter today.", "She read my <b>post</b> online.", "The fence has a wooden <b>post</b>."],
 (6, "get"): ["I want to <b>get</b> a new phone.", "It's starting to <b>get</b> cold."],
 (6, "common"): ["Rain is <b>common</b> in spring.", "We have a lot in <b>common</b>."],
 (6, "partner"): ["He is my business <b>partner</b>.", "Choose a <b>partner</b> for the game."],
 (6, "title"): ["What is the <b>title</b> of this song?", "She won the world <b>title</b>."],
 (6, "correct"): ["Your answer is <b>correct</b>.", "The teacher will <b>correct</b> our mistakes."],
 (6, "dress"): ["She bought a new <b>dress</b>.", "He got <b>dressed</b> quickly."],
 (6, "return"): ["They will <b>return</b> from holiday on Sunday.", "I will <b>return</b> the book tomorrow."],

 # ——— Grup 7 (A1) ———
 (7, "even"): ["He didn't <b>even</b> say hello.", "Cut the cake into <b>even</b> pieces."],
 (7, "order"): ["May I take your <b>order</b>?", "The captain gave an <b>order</b>.", "Put the books in <b>order</b>."],
 (7, "back"): ["My <b>back</b> hurts a little.", "Please come <b>back</b> soon."],
 (7, "to"): ["We are going <b>to</b> the shop.", "I want <b>to</b> learn English."],
 (7, "time"): ["What <b>time</b> is it?", "I have seen that film three <b>times</b>."],
 (7, "date"): ["What is the <b>date</b> today?", "They went on a <b>date</b> last night."],
 (7, "exercise"): ["<b>Exercise</b> keeps you healthy.", "Do this grammar <b>exercise</b>."],
 (7, "break"): ["Don't <b>break</b> the glass.", "Let's take a short <b>break</b>."],
 (7, "drink"): ["<b>Drink</b> more water.", "Would you like a cold <b>drink</b>?"],
 (7, "fine"): ["I'm <b>fine</b>, thank you.", "He had to pay a <b>fine</b>."],
 (7, "start"): ["The film will <b>start</b> soon.", "It was a good <b>start</b>."],
 (7, "park"): ["We walked in the <b>park</b>.", "You can't <b>park</b> here."],
 (7, "poor"): ["The <b>poor</b> man had no home.", "The <b>poor</b> cat was lost in the rain."],
 (7, "cost"): ["The <b>cost</b> of living is rising.", "How much does it <b>cost</b>?"],
 (7, "then"): ["We had lunch and <b>then</b> went home.", "Back <b>then</b>, life was simpler."],
 (7, "full"): ["The glass is <b>full</b> of water.", "I waited a <b>full</b> hour."],

 # ——— Grup 8 (A1) ———
 (8, "stand"): ["Please <b>stand</b> up.", "I can't <b>stand</b> the noise."],
 (8, "present"): ["We must think about the <b>present</b>, not the past.", "She will <b>present</b> the award.", "She gave me a birthday <b>present</b>."],
 (8, "once"): ["I visit my aunt <b>once</b> a month.", "<b>Once</b>, there was a king."],
 (8, "orange"): ["I drink <b>orange</b> juice.", "She wore an <b>orange</b> hat."],
 (8, "cook"): ["My mother can <b>cook</b> well.", "He works as a <b>cook</b> in a hotel."],
 (8, "too"): ["This coffee is <b>too</b> hot.", "I want to come <b>too</b>."],
 (8, "complete"): ["Please <b>complete</b> the form.", "This is a <b>complete</b> waste of time."],
 (8, "call"): ["I'll <b>call</b> you tonight.", "Please <b>call</b> the waiter."],
 (8, "old"): ["My grandmother is very <b>old</b>.", "He drives an <b>old</b> car."],
 (8, "report"): ["She wrote a <b>report</b> about the trip.", "You must <b>report</b> the accident to the police."],
 (8, "please"): ["Can I have some water, <b>please</b>?", "It's hard to <b>please</b> everyone."],
 (8, "line"): ["Draw a straight <b>line</b>.", "We waited in a long <b>line</b>."],
 (8, "point"): ["That's a good <b>point</b>.", "Don't <b>point</b> at people."],
 (8, "clean"): ["Keep your room <b>clean</b>.", "I <b>clean</b> the kitchen every day."],
 (8, "draw"): ["Children love to <b>draw</b>.", "The match ended in a <b>draw</b>."],
 (8, "story"): ["Grandma told us a <b>story</b>.", "The building has ten <b>stories</b>."],
 (8, "work"): ["I <b>work</b> in a hospital.", "She has a lot of <b>work</b> to do."],
 (8, "great"): ["We had a <b>great</b> time.", "A <b>great</b> wall surrounds the city."],
 (8, "run"): ["I <b>run</b> in the park every morning.", "They <b>run</b> a small restaurant."],
 (8, "cool"): ["The evening air was <b>cool</b>.", "Those are really <b>cool</b> shoes."],

 # ——— Grup 9 (A1) ———
 (9, "ask"): ["May I <b>ask</b> a question?", "She <b>asked</b> for help."],
 (9, "fat"): ["Too much sugar can make you <b>fat</b>.", "This meat has a lot of <b>fat</b>."],
 (9, "company"): ["She works for a big <b>company</b>.", "I enjoy your <b>company</b>."],
 (9, "still"): ["Are you <b>still</b> at work?", "It was raining; <b>still</b>, we went out.", "The lake was calm and <b>still</b>."],
 (9, "end"): ["We left before the <b>end</b> of the film.", "The show will <b>end</b> at ten."],
 (9, "book"): ["I read a good <b>book</b> last week.", "I'd like to <b>book</b> a table."],
 (9, "over"): ["The plane flew <b>over</b> the city.", "The game is <b>over</b>."],
 (9, "rule"): ["Follow the <b>rules</b> of the game.", "The king <b>ruled</b> for forty years."],
}
