# -*- coding: utf-8 -*-
"""Çok anlamlı kelimeler için her anlama bir örnek cümle.

Anahtar: (grup_no, kelime)  →  [cümle, ...]  (her cümlede <b>kelime</b>).
build_all.apply_multi_examples bunu tüm gruplara uygular (100-kelime kısıtı yok;
Grup 1/10 gibi enrich'siz gruplar da dahil). Sıra = tr alanındaki anlam sırası.
"""

EX = {
 # ——— Grup 1 (A1) ———
 (1, "live"): ["They <b>live</b> in a small village.", "The concert was shown <b>live</b> on TV."],
 (1, "will"): ["I <b>will</b> call you tomorrow.", "She has a strong <b>will</b> to win."],
 (1, "opposite"): ["'Hot' is the <b>opposite</b> of 'cold'.", "The bank is <b>opposite</b> the school."],
 (1, "course"): ["I'm taking an English <b>course</b>.", "The ship changed its <b>course</b>.", "The main <b>course</b> was chicken."],
 (1, "off"): ["Please turn <b>off</b> the light.", "The island is far <b>off</b> the coast."],
 (1, "shower"): ["I take a <b>shower</b> every morning.", "We got caught in a <b>shower</b> of rain."],
 (1, "introduce"): ["Let me <b>introduce</b> my friend Ali.", "The school will <b>introduce</b> a new rule."],
 (1, "when"): ["<b>When</b> does the film start?", "Call me <b>when</b> you arrive."],
 (1, "open"): ["The shop is <b>open</b> until nine.", "Please <b>open</b> the window."],
 (1, "match"): ["We watched the football <b>match</b>.", "He lit a <b>match</b> to start the fire.", "Your socks don't <b>match</b>."],
 (1, "space"): ["There isn't much <b>space</b> in my room.", "Astronauts travel in <b>space</b>."],
 (1, "paint"): ["The <b>paint</b> is still wet.", "They will <b>paint</b> the wall blue."],
 (1, "play"): ["The children <b>play</b> in the park.", "We saw a <b>play</b> at the theatre."],
 (1, "love"): ["I <b>love</b> Italian food.", "Their <b>love</b> lasted a lifetime."],
 (1, "show"): ["Can you <b>show</b> me the way?", "We watched a TV <b>show</b>."],
 (1, "second"): ["Wait a <b>second</b>, please.", "She came <b>second</b> in the race."],
 (1, "subject"): ["My favourite <b>subject</b> is maths.", "In this sentence, 'dog' is the <b>subject</b>.", "The plan is <b>subject</b> to change."],
 (1, "right"): ["You gave the <b>right</b> answer.", "Turn <b>right</b> at the corner.", "Everyone has the <b>right</b> to vote."],
 (1, "welcome"): ["<b>Welcome</b> to our home!", "They came out to <b>welcome</b> the guests."],
 (1, "spring"): ["Flowers bloom in <b>spring</b>.", "The <b>spring</b> in the pen is broken.", "Fresh water flowed from the <b>spring</b>."],

 # ——— Grup 2 (A1) ———
 (2, "leave"): ["We <b>leave</b> home at eight every morning.", "Please <b>leave</b> the door open."],
 (2, "table"): ["The keys are on the <b>table</b>.", "Look at the <b>table</b> of results on page five."],
 (2, "pretty"): ["What a <b>pretty</b> dress!", "The film was <b>pretty</b> good."],
 (2, "spell"): ["How do you <b>spell</b> your name?", "The witch cast a magic <b>spell</b>."],
 (2, "writing"): ["He is good at <b>writing</b> essays.", "I can't read your <b>writing</b>."],
 (2, "letter"): ["I wrote a <b>letter</b> to my grandmother.", "The word 'cat' has three <b>letters</b>."],
 (2, "watch"): ["We <b>watch</b> TV in the evening.", "He looked at his <b>watch</b>."],
 (2, "that"): ["Whose is <b>that</b> car?", "She said <b>that</b> she was tired."],
 (2, "turn"): ["<b>Turn</b> left at the bank.", "It's your <b>turn</b> to play."],
 (2, "diet"): ["A healthy <b>diet</b> is important.", "She is on a <b>diet</b> to lose weight."],
 (2, "period"): ["The Ottoman <b>period</b> lasted for centuries.", "We lived there for a short <b>period</b>.", "Put a <b>period</b> at the end of the sentence."],
 (2, "move"): ["Can you help me <b>move</b> this table?", "They will <b>move</b> to a new house."],
 (2, "look"): ["<b>Look</b> at this photo!", "You <b>look</b> tired today."],
 (2, "hard"): ["The exam was very <b>hard</b>.", "The bed was too <b>hard</b> to sleep on."],
 (2, "past"): ["Forget the <b>past</b> and look forward.", "We drove <b>past</b> the school."],
 (2, "miss"): ["I <b>miss</b> my old friends.", "Hurry, or we'll <b>miss</b> the bus."],
 (2, "study"): ["I <b>study</b> English every evening.", "A new <b>study</b> shows that coffee is healthy."],
 (2, "class"): ["My <b>class</b> has twenty students.", "I have an English <b>class</b> now."],
 (2, "well"): ["She speaks English very <b>well</b>.", "They got water from the <b>well</b>."],

 # ——— Grup 3 (A1) ———
 (3, "glass"): ["The window is made of <b>glass</b>.", "She drank a <b>glass</b> of water."],
 (3, "form"): ["Water can take the <b>form</b> of ice.", "Please fill in this <b>form</b>."],
 (3, "cup"): ["Would you like a <b>cup</b> of coffee?", "Our team won the <b>cup</b>."],
 (3, "close"): ["Please <b>close</b> the window.", "The shop is <b>close</b> to my house."],
 (3, "interest"): ["He shows great <b>interest</b> in science.", "The bank pays <b>interest</b> on savings."],
 (3, "grow"): ["Children <b>grow</b> quickly.", "They <b>grow</b> vegetables in the garden."],
 (3, "can"): ["You <b>can</b> swim very well.", "She opened a <b>can</b> of beans."],
 (3, "join"): ["Why don't you <b>join</b> our team?", "<b>Join</b> the two ropes together."],
 (3, "article"): ["I read an interesting <b>article</b> today.", "'The' is a definite <b>article</b>."],
 (3, "game"): ["Let's play a <b>game</b> after dinner.", "The football <b>game</b> starts at eight."],
 (3, "floor"): ["The toys are all over the <b>floor</b>.", "My office is on the third <b>floor</b>."],
 (3, "light"): ["Turn on the <b>light</b>, please.", "The bag is very <b>light</b>."],

 # ——— Grup 4 (A1) ———
 (4, "second"): ["Wait a <b>second</b>, please.", "She came <b>second</b> in the race."],
 (4, "type"): ["What <b>type</b> of music do you like?", "Please <b>type</b> your name here."],
 (4, "country"): ["Türkiye is a beautiful <b>country</b>.", "They live in the <b>country</b>, far from the city."],
 (4, "as"): ["She works <b>as</b> a nurse.", "<b>As</b> it was raining, we stayed home.", "She is <b>as</b> clever as her sister."],
 (4, "mean"): ["What does this word <b>mean</b>?", "Don't be so <b>mean</b> with your money."],
 (4, "object"): ["What is that strange <b>object</b>?", "Many people <b>object</b> to the new law."],
 (4, "final"): ["This is the <b>final</b> question.", "Our team reached the <b>final</b>."],
 (4, "face"): ["She has a friendly <b>face</b>.", "We must <b>face</b> the problem."],
 (4, "train"): ["We took the <b>train</b> to İzmir.", "They <b>train</b> dogs to help people."],
 (4, "fly"): ["Birds <b>fly</b> south in winter.", "A <b>fly</b> landed on the food."],
 (4, "fall"): ["Be careful not to <b>fall</b>.", "Leaves turn brown in the <b>fall</b>."],
 (4, "change"): ["Let's <b>change</b> the plan.", "There has been a big <b>change</b> in the weather."],

 # ——— Grup 5 (A1) ———
 (5, "just"): ["I want <b>just</b> a little sugar.", "She <b>just</b> left the office."],
 (5, "plant"): ["Water the <b>plant</b> every day.", "He works at a car <b>plant</b>.", "We will <b>plant</b> trees in the garden."],
 (5, "land"): ["They own a large piece of <b>land</b>.", "The plane will <b>land</b> soon."],
 (5, "on"): ["The book is <b>on</b> the table.", "The lights are <b>on</b>."],
 (5, "by"): ["The book was written <b>by</b> a famous author.", "She sat <b>by</b> the window.", "We travelled <b>by</b> train."],
 (5, "paper"): ["Write your name on the <b>paper</b>.", "I read the news in the <b>paper</b>."],
 (5, "own"): ["She has her <b>own</b> room.", "They <b>own</b> two cars."],
 (5, "little"): ["A <b>little</b> girl was crying.", "There is a <b>little</b> milk left."],
 (5, "capital"): ["Ankara is the <b>capital</b> of Türkiye.", "You need <b>capital</b> to start a business."],
 (5, "dark"): ["It gets <b>dark</b> early in winter.", "She wore a <b>dark</b> blue coat."],
 (5, "sentence"): ["Write a <b>sentence</b> with this word.", "The judge gave him a long <b>sentence</b>."],
 (5, "way"): ["Which <b>way</b> is the station?", "This is the best <b>way</b> to learn."],
 (5, "left"): ["Turn <b>left</b> at the corner.", "There is no food <b>left</b>."],
 (5, "around"): ["There are trees <b>around</b> the house.", "It costs <b>around</b> fifty liras."],

 # ——— Grup 6 (A1) ———
 (6, "about"): ["This book is <b>about</b> animals.", "It's <b>about</b> three o'clock."],
 (6, "share"): ["Let's <b>share</b> the pizza.", "She owns a <b>share</b> in the company."],
 (6, "flat"): ["They live in a small <b>flat</b>.", "The land is very <b>flat</b>."],
 (6, "free"): ["The birds are <b>free</b> to fly away.", "The tickets are <b>free</b>."],
 (6, "dish"): ["This <b>dish</b> is very tasty.", "She washed every <b>dish</b>."],
 (6, "key"): ["I lost my house <b>key</b>.", "Press the 'enter' <b>key</b>."],
 (6, "room"): ["My <b>room</b> is upstairs.", "There is no <b>room</b> in the car."],
 (6, "dear"): ["<b>Dear</b> Ali, how are you?", "That coat is too <b>dear</b> for me."],
 (6, "no"): ["<b>No</b>, thank you.", "There is <b>no</b> milk in the fridge."],
 (6, "spend"): ["I <b>spend</b> too much money on books.", "We <b>spend</b> summers by the sea."],
 (6, "so"): ["It was late, <b>so</b> we went home.", "I am <b>so</b> happy today.", "I think <b>so</b>."],
 (6, "post"): ["I'll <b>post</b> the letter today.", "She read my <b>post</b> online.", "The fence has a wooden <b>post</b>."],
 (6, "get"): ["I want to <b>get</b> a new phone.", "It's starting to <b>get</b> cold."],
 (6, "common"): ["Rain is <b>common</b> in spring.", "We have a lot in <b>common</b>."],
 (6, "partner"): ["He is my business <b>partner</b>.", "Choose a <b>partner</b> for the game."],
 (6, "title"): ["What is the <b>title</b> of this song?", "She won the world <b>title</b>."],
 (6, "correct"): ["Your answer is <b>correct</b>.", "The teacher will <b>correct</b> our mistakes."],
 (6, "dress"): ["She bought a new <b>dress</b>.", "He got <b>dressed</b> quickly."],
 (6, "return"): ["They will <b>return</b> from holiday on Sunday.", "I will <b>return</b> the book tomorrow."],

 # ——— Grup 7 (A1) ———
 (7, "even"): ["He didn't <b>even</b> say hello.", "Cut the cake into <b>even</b> pieces."],
 (7, "order"): ["May I take your <b>order</b>?", "The captain gave an <b>order</b>.", "Put the books in <b>order</b>."],
 (7, "back"): ["My <b>back</b> hurts a little.", "Please come <b>back</b> soon."],
 (7, "to"): ["We are going <b>to</b> the shop.", "I want <b>to</b> learn English."],
 (7, "time"): ["What <b>time</b> is it?", "I have seen that film three <b>times</b>."],
 (7, "date"): ["What is the <b>date</b> today?", "They went on a <b>date</b> last night."],
 (7, "exercise"): ["<b>Exercise</b> keeps you healthy.", "Do this grammar <b>exercise</b>."],
 (7, "break"): ["Don't <b>break</b> the glass.", "Let's take a short <b>break</b>."],
 (7, "drink"): ["<b>Drink</b> more water.", "Would you like a cold <b>drink</b>?"],
 (7, "fine"): ["I'm <b>fine</b>, thank you.", "He had to pay a <b>fine</b>."],
 (7, "start"): ["The film will <b>start</b> soon.", "It was a good <b>start</b>."],
 (7, "park"): ["We walked in the <b>park</b>.", "You can't <b>park</b> here."],
 (7, "poor"): ["The <b>poor</b> man had no home.", "The <b>poor</b> cat was lost in the rain."],
 (7, "cost"): ["The <b>cost</b> of living is rising.", "How much does it <b>cost</b>?"],
 (7, "then"): ["We had lunch and <b>then</b> went home.", "Back <b>then</b>, life was simpler."],
 (7, "full"): ["The glass is <b>full</b> of water.", "I waited a <b>full</b> hour."],

 # ——— Grup 8 (A1) ———
 (8, "stand"): ["Please <b>stand</b> up.", "I can't <b>stand</b> the noise."],
 (8, "present"): ["We must think about the <b>present</b>, not the past.", "She will <b>present</b> the award.", "She gave me a birthday <b>present</b>."],
 (8, "once"): ["I visit my aunt <b>once</b> a month.", "<b>Once</b>, there was a king."],
 (8, "orange"): ["I drink <b>orange</b> juice.", "She wore an <b>orange</b> hat."],
 (8, "cook"): ["My mother can <b>cook</b> well.", "He works as a <b>cook</b> in a hotel."],
 (8, "too"): ["This coffee is <b>too</b> hot.", "I want to come <b>too</b>."],
 (8, "complete"): ["Please <b>complete</b> the form.", "This is a <b>complete</b> waste of time."],
 (8, "call"): ["I'll <b>call</b> you tonight.", "Please <b>call</b> the waiter."],
 (8, "old"): ["My grandmother is very <b>old</b>.", "He drives an <b>old</b> car."],
 (8, "report"): ["She wrote a <b>report</b> about the trip.", "You must <b>report</b> the accident to the police."],
 (8, "please"): ["Can I have some water, <b>please</b>?", "It's hard to <b>please</b> everyone."],
 (8, "line"): ["Draw a straight <b>line</b>.", "We waited in a long <b>line</b>."],
 (8, "point"): ["That's a good <b>point</b>.", "Don't <b>point</b> at people."],
 (8, "clean"): ["Keep your room <b>clean</b>.", "I <b>clean</b> the kitchen every day."],
 (8, "draw"): ["Children love to <b>draw</b>.", "The match ended in a <b>draw</b>."],
 (8, "story"): ["Grandma told us a <b>story</b>.", "The building has ten <b>stories</b>."],
 (8, "work"): ["I <b>work</b> in a hospital.", "She has a lot of <b>work</b> to do."],
 (8, "great"): ["We had a <b>great</b> time.", "A <b>great</b> wall surrounds the city."],
 (8, "run"): ["I <b>run</b> in the park every morning.", "They <b>run</b> a small restaurant."],
 (8, "cool"): ["The evening air was <b>cool</b>.", "Those are really <b>cool</b> shoes."],

 # ——— Grup 9 (A1) ———
 (9, "ask"): ["May I <b>ask</b> a question?", "She <b>asked</b> for help."],
 (9, "fat"): ["Too much sugar can make you <b>fat</b>.", "This meat has a lot of <b>fat</b>."],
 (9, "company"): ["She works for a big <b>company</b>.", "I enjoy your <b>company</b>."],
 (9, "still"): ["Are you <b>still</b> at work?", "It was raining; <b>still</b>, we went out.", "The lake was calm and <b>still</b>."],
 (9, "end"): ["We left before the <b>end</b> of the film.", "The show will <b>end</b> at ten."],
 (9, "book"): ["I read a good <b>book</b> last week.", "I'd like to <b>book</b> a table."],
 (9, "over"): ["The plane flew <b>over</b> the city.", "The game is <b>over</b>."],
 (9, "rule"): ["Follow the <b>rules</b> of the game.", "The king <b>ruled</b> for forty years."],

 # ——— Grup 10 (A2) ———
 (10, "tie"): ["He wore a blue <b>tie</b> to work.", "Please <b>tie</b> your shoelaces."],
 (10, "dream"): ["I had a strange <b>dream</b> last night.", "Her <b>dream</b> is to become a doctor."],
 (10, "public"): ["The <b>public</b> has a right to know.", "This is a <b>public</b> park, so everyone can enter."],
 (10, "medicine"): ["Take this <b>medicine</b> twice a day.", "She is studying <b>medicine</b> at university."],
 (10, "director"): ["The film's <b>director</b> won an award.", "She is the <b>director</b> of a big company."],
 (10, "realize"): ["I didn't <b>realize</b> it was so late.", "She worked hard to <b>realize</b> her dream."],
 (10, "service"): ["The <b>service</b> at the hotel was excellent.", "The bus <b>service</b> is very good here."],
 (10, "chance"): ["This is your last <b>chance</b>.", "There is a good <b>chance</b> of rain today."],
 (10, "chip"): ["Would you like some fish and <b>chips</b>?", "A tiny <b>chip</b> controls the phone."],
 (10, "quality"): ["This shirt is of very high <b>quality</b>.", "Kindness is her best <b>quality</b>."],
 (10, "lift"): ["Can you <b>lift</b> this box for me?", "Take the <b>lift</b> to the fifth floor."],
 (10, "smoke"): ["I could smell <b>smoke</b> from the fire.", "You must not <b>smoke</b> here."],
 (10, "fan"): ["He is a big <b>fan</b> of the team.", "Turn on the <b>fan</b>; it's hot."],
 (10, "stamp"): ["I put a <b>stamp</b> on the envelope.", "The officer put a <b>stamp</b> in my passport."],
 (10, "review"): ["The manager gave a <b>review</b> of the year.", "I read a good <b>review</b> of the restaurant."],
 (10, "straight"): ["Draw a <b>straight</b> line here.", "Go <b>straight</b> home after school."],
 (10, "appear"): ["She <b>appears</b> to be happy.", "A rainbow began to <b>appear</b> in the sky."],
 (10, "offer"): ["They accepted my <b>offer</b>.", "They <b>offered</b> me a new job."],
 (10, "wish"): ["Make a <b>wish</b> and blow the candles.", "I <b>wish</b> you a happy birthday."],

 # ——— Grup 11 (A2) ———
 (11, "case"): ["In that <b>case</b>, we should leave early.", "The <b>case</b> went to court.", "She keeps her glasses in a <b>case</b>."],
 (11, "blow"): ["<b>Blow</b> out the candles!", "The <b>blow</b> to his head hurt a lot."],
 (11, "mind"): ["A clever <b>mind</b> solves problems fast.", "Would you <b>mind</b> closing the window?"],
 (11, "rather"): ["I would <b>rather</b> stay at home tonight.", "The film was <b>rather</b> long."],
 (11, "musical"): ["He comes from a <b>musical</b> family.", "We saw a <b>musical</b> in London."],
 (11, "position"): ["Put the chair in that <b>position</b>.", "She applied for a <b>position</b> at the bank."],
 (11, "tablet"): ["She reads books on her <b>tablet</b>.", "Take one <b>tablet</b> after meals."],
 (11, "figure"): ["The sales <b>figures</b> went up this year.", "A dark <b>figure</b> stood at the door."],
 (11, "fix"): ["Can you <b>fix</b> my computer?", "<b>Fix</b> the shelf to the wall."],
 (11, "manage"): ["She <b>manages</b> a big team.", "He <b>managed</b> to finish on time."],
 (11, "couple"): ["A young <b>couple</b> moved in next door.", "I'll be back in a <b>couple</b> of minutes."],
 (11, "further"): ["The shop is a little <b>further</b> down the road.", "For <b>further</b> information, call us."],
 (11, "lead"): ["This road will <b>lead</b> you to the station.", "The pipes are made of <b>lead</b>."],
 (11, "possession"): ["The land is in his <b>possession</b>.", "The old watch is her favourite <b>possession</b>."],
 (11, "smell"): ["I love the <b>smell</b> of fresh bread.", "<b>Smell</b> these flowers."],
 (11, "fit"): ["These shoes don't <b>fit</b> me.", "She stays <b>fit</b> by running."],
 (11, "care"): ["She takes <b>care</b> of her little brother.", "I don't <b>care</b> what they say."],
 (11, "record"): ["Keep a <b>record</b> of your spending.", "They will <b>record</b> the song tomorrow."],
 (11, "pants"): ["He bought a new pair of <b>pants</b>.", "She keeps clean <b>pants</b> in the drawer."],
 (11, "sheet"): ["Put a clean <b>sheet</b> on the bed.", "Write your name on a <b>sheet</b> of paper."],
 (11, "round"): ["The Earth is <b>round</b>.", "He won the first <b>round</b> of the match."],
 (11, "pattern"): ["Her dress had a flower <b>pattern</b>.", "There is a clear <b>pattern</b> in the numbers."],
 (11, "fair"): ["It isn't <b>fair</b> to blame him.", "We had fun at the book <b>fair</b>."],
 (11, "coach"): ["The <b>coach</b> taught the team new skills.", "We travelled to Rome by <b>coach</b>."],
 (11, "scene"): ["My favourite <b>scene</b> is at the end.", "Police arrived at the <b>scene</b> of the crime."],

 # ——— Grup 12 (A2) ———
 (12, "rubbish"): ["Please put the <b>rubbish</b> in the bin.", "Don't talk <b>rubbish</b>!"],
 (12, "search"): ["The <b>search</b> for the lost dog lasted hours.", "They <b>searched</b> the house for clues."],
 (12, "serve"): ["He <b>served</b> in the army for years.", "The waiter <b>served</b> our meal."],
 (12, "focus"): ["<b>Focus</b> on your work.", "The children were the <b>focus</b> of attention."],
 (12, "regular"): ["He does <b>regular</b> exercise.", "He is a <b>regular</b> customer here."],
 (12, "gas"): ["Turn off the <b>gas</b> after cooking.", "We stopped to buy <b>gas</b> for the car."],
 (12, "bright"): ["The sun is very <b>bright</b> today.", "She is a <b>bright</b> student."],
 (12, "apply"): ["She will <b>apply</b> for the job.", "<b>Apply</b> the cream to your skin."],
 (12, "oil"): ["Add some olive <b>oil</b> to the pan.", "The country is rich in <b>oil</b>."],
 (12, "bit"): ["The cup broke into <b>bits</b>.", "I'm a little <b>bit</b> tired."],
 (12, "platform"): ["The speaker stood on a <b>platform</b>.", "The train leaves from <b>platform</b> two."],
 (12, "square"): ["Draw a <b>square</b> on the paper.", "We met in the town <b>square</b>."],
 (12, "peace"): ["The two countries signed a <b>peace</b> treaty.", "I enjoy the <b>peace</b> of the countryside."],
 (12, "board"): ["The teacher wrote on the <b>board</b>.", "The <b>board</b> made an important decision."],
 (12, "score"): ["The final <b>score</b> was two to one.", "He <b>scored</b> the winning goal."],
 (12, "view"): ["What is your <b>view</b> on this matter?", "The room has a lovely <b>view</b> of the sea."],
 (12, "society"): ["Education is important for <b>society</b>.", "She joined a history <b>society</b>."],
 (12, "rest"): ["Let's take a short <b>rest</b>.", "I'll do the <b>rest</b> tomorrow."],
 (12, "direct"): ["Is there a <b>direct</b> train to Ankara?", "She will <b>direct</b> the new film."],

 # ——— Grup 13 (A2) ———
 (13, "brush"): ["Clean it with a <b>brush</b>.", "<b>Brush</b> your teeth twice a day."],
 (13, "separate"): ["The children sleep in <b>separate</b> rooms.", "<b>Separate</b> the eggs from the flour."],
 (13, "top"): ["The cat sat on <b>top</b> of the wall.", "We climbed to the <b>top</b> of the hill."],
 (13, "thin"): ["Cut the bread into <b>thin</b> slices.", "He looks <b>thin</b> after his illness."],
 (13, "competition"): ["She won first place in the <b>competition</b>.", "There is strong <b>competition</b> between the shops."],
 (13, "track"): ["We followed the <b>track</b> through the forest.", "My favourite <b>track</b> is the third one.", "The app can <b>track</b> your steps."],
 (13, "race"): ["He won the running <b>race</b>.", "People of every <b>race</b> live in the city."],
 (13, "speaker"): ["The <b>speaker</b> talked about health.", "The <b>speaker</b> plays music loudly."],
 (13, "sense"): ["Dogs have a strong <b>sense</b> of smell.", "This sentence makes no <b>sense</b>.", "I had a <b>sense</b> that something was wrong."],
 (13, "stress"): ["Too much work causes <b>stress</b>.", "Put the <b>stress</b> on the first syllable."],
 (13, "pack"): ["I need to <b>pack</b> for my trip.", "She bought a <b>pack</b> of cards."],
 (13, "temperature"): ["The <b>temperature</b> dropped last night.", "The child has a high <b>temperature</b>."],
 (13, "power"): ["The storm cut off the <b>power</b>.", "The party came to <b>power</b> last year."],
 (13, "sort"): ["What <b>sort</b> of music do you like?", "Please <b>sort</b> these papers by date."],
 (13, "rate"): ["The success <b>rate</b> is very high.", "He walked at a fast <b>rate</b>.", "Please <b>rate</b> the film out of ten."],
 (13, "heat"): ["The <b>heat</b> of the fire warmed the room.", "<b>Heat</b> the soup for five minutes."],
 (13, "painter"): ["The <b>painter</b> sold his picture.", "The <b>painter</b> painted our house white."],

 # ——— Grup 14 (A2) ———
 (14, "field"): ["The cows are in the <b>field</b>.", "She is an expert in the <b>field</b> of medicine."],
 (14, "recognize"): ["I didn't <b>recognize</b> you with your new haircut.", "The country <b>recognized</b> the new government."],
 (14, "individual"): ["Each <b>individual</b> has different needs.", "Each child gets <b>individual</b> attention."],
 (14, "secretary"): ["The <b>secretary</b> answered the phone.", "The foreign <b>secretary</b> gave a speech."],
 (14, "instrument"): ["The violin is a beautiful <b>instrument</b>.", "The dentist used a small <b>instrument</b>."],
 (14, "thick"): ["He wore a <b>thick</b> winter coat.", "A <b>thick</b> fog covered the road."],
 (14, "degree"): ["It is thirty <b>degrees</b> today.", "She has a <b>degree</b> in law."],
 (14, "cry"): ["The baby began to <b>cry</b>.", "She gave a <b>cry</b> of surprise."],
 (14, "save"): ["Firefighters <b>saved</b> the family.", "I <b>save</b> money every month.", "Don't forget to <b>save</b> the file."],
 (14, "surprise"): ["The party was a lovely <b>surprise</b>.", "The news <b>surprised</b> everyone."],
 (14, "succeed"): ["If you work hard, you will <b>succeed</b>.", "Night <b>succeeds</b> day."],
 (14, "drop"): ["Be careful not to <b>drop</b> the plate.", "A <b>drop</b> of rain fell on my hand."],
 (14, "rock"): ["The children climbed on the <b>rocks</b>.", "He plays in a <b>rock</b> band."],
 (14, "rise"): ["Prices <b>rise</b> every year.", "There was a sharp <b>rise</b> in sales."],
 (14, "reply"): ["She didn't <b>reply</b> to my message.", "I am still waiting for a <b>reply</b>."],
 (14, "patient"): ["The doctor saw ten <b>patients</b> today.", "Please be <b>patient</b>; it won't take long."],
 (14, "express"): ["It's hard to <b>express</b> my thanks.", "We took the <b>express</b> train to the city."],
 (14, "single"): ["Not a <b>single</b> person came.", "She is <b>single</b> and lives alone."],
 (14, "sign"): ["The <b>sign</b> says the shop is closed.", "Please <b>sign</b> your name here."],
 (14, "raise"): ["<b>Raise</b> your hand if you know the answer.", "The shop <b>raised</b> its prices.", "They <b>raise</b> three children."],
 (14, "desert"): ["Camels live in the <b>desert</b>.", "He <b>deserted</b> his friends in trouble."],
 (14, "following"): ["Answer the <b>following</b> questions.", "We met again the <b>following</b> day."],
 (14, "smile"): ["She gave me a warm <b>smile</b>.", "<b>Smile</b> for the camera!"],
 (14, "ring"): ["The phone began to <b>ring</b>.", "She wears a gold <b>ring</b>."],
 (14, "pop"): ["She loves <b>pop</b> music.", "The balloon <b>popped</b> loudly."],
 (14, "state"): ["The country is in a bad <b>state</b>.", "The <b>state</b> pays for schools.", "Please <b>state</b> your name and age."],
 (14, "while"): ["She sang <b>while</b> she cooked.", "Let's rest for a <b>while</b>."],
 (14, "promise"): ["I <b>promise</b> to call you tomorrow.", "He kept his <b>promise</b>."],
 (14, "trainer"): ["The <b>trainer</b> helped the team improve.", "She bought new <b>trainers</b> for the gym."],

 # ——— Grup 15 (A2) ———
 (15, "earth"): ["The <b>Earth</b> goes around the sun.", "The <b>earth</b> in the garden is dry."],
 (15, "introduction"): ["The book has a short <b>introduction</b>.", "He gave a brief <b>introduction</b> of the guest."],
 (15, "deal"): ["We made a good <b>deal</b> on the car.", "She knows how to <b>deal</b> with problems."],
 (15, "drug"): ["This <b>drug</b> reduces pain.", "Selling <b>drugs</b> is a crime."],
 (15, "cover"): ["<b>Cover</b> the pot with a lid.", "The book has a red <b>cover</b>."],
 (15, "close"): ["The station is <b>close</b> to my house.", "<b>Close</b> the door, please."],
 (15, "ring"): ["He gave her a gold <b>ring</b>.", "I'll <b>ring</b> you later."],
 (15, "can"): ["I bought a <b>can</b> of beans.", "She <b>can</b> speak three languages."],
 (15, "washing"): ["I hung the <b>washing</b> outside.", "The <b>washing</b> of the car took an hour."],
 (15, "taste"): ["This soup has a nice <b>taste</b>.", "<b>Taste</b> this and tell me if it's sweet."],
 (15, "site"): ["This is a good <b>site</b> for a new school.", "I found it on a shopping <b>site</b>."],
 (15, "brilliant"): ["The stars were <b>brilliant</b> in the night sky.", "What a <b>brilliant</b> idea!"],
 (15, "yet"): ["Have you finished <b>yet</b>?", "It's a small car, <b>yet</b> it's very fast."],
 (15, "rock"): ["We sat on a large <b>rock</b>.", "They listened to <b>rock</b> music all night."],
 (15, "term"): ["'Gravity' is a scientific <b>term</b>.", "The summer <b>term</b> ends in June."],
 (15, "condition"): ["The car is in good <b>condition</b>.", "You can come, on one <b>condition</b>."],
 (15, "hit"): ["Don't <b>hit</b> your brother.", "Her new song was a big <b>hit</b>."],
 (15, "secret"): ["Can you keep a <b>secret</b>?", "They met in a <b>secret</b> place."],
 (15, "bar"): ["We met friends at a <b>bar</b>.", "He ate a <b>bar</b> of chocolate."],
 (15, "safe"): ["Keep your passport in a <b>safe</b> place.", "The money is locked in the <b>safe</b>."],
 (15, "pick"): ["<b>Pick</b> a card, any card.", "We <b>picked</b> apples from the tree."],
 (15, "height"): ["The plane flew at a great <b>height</b>.", "What is your <b>height</b>?"],
 (15, "argue"): ["They often <b>argue</b> about money.", "She <b>argued</b> that the plan was wrong."],
 (15, "appearance"): ["She cares about her <b>appearance</b>.", "The singer made a surprise <b>appearance</b>."],
 (15, "notice"): ["Did you <b>notice</b> anything strange?", "They put a <b>notice</b> on the door."],

 # ——— Grup 16 (A2) ———
 (16, "wood"): ["We put more <b>wood</b> on the fire.", "The table is made of <b>wood</b>.", "We walked in the <b>woods</b>."],
 (16, "fight"): ["The two boys had a <b>fight</b>.", "They <b>fight</b> for their rights."],
 (16, "goal"): ["My <b>goal</b> is to speak English well.", "He scored the winning <b>goal</b>."],
 (16, "beat"): ["Our team <b>beat</b> theirs three to one.", "The drummer <b>beat</b> the drum."],
 (16, "hall"): ["The concert was held in a big <b>hall</b>.", "Hang your coat in the <b>hall</b>."],
 (16, "rest"): ["You look tired; take a <b>rest</b>.", "I'll do the <b>rest</b> of the work tomorrow."],
 (16, "nut"): ["She added <b>nuts</b> to the cake.", "Tighten the <b>nut</b> with a spanner."],
 (16, "perform"): ["The band will <b>perform</b> tonight.", "The doctor <b>performed</b> the operation."],
 (16, "cycle"): ["The washing machine has a short <b>cycle</b>.", "I <b>cycle</b> to work every day."],
 (16, "underground"): ["The animal lives <b>underground</b>.", "We took the <b>underground</b> to the centre."],
 (16, "survey"): ["We did a <b>survey</b> about shopping habits.", "The <b>survey</b> of the land took a week."],
 (16, "credit"): ["She paid with a <b>credit</b> card.", "She got all the <b>credit</b> for the idea."],
 (16, "transport"): ["Public <b>transport</b> is cheap here.", "Trucks <b>transport</b> goods across the country."],
 (16, "solution"): ["We found a simple <b>solution</b>.", "Mix the salt into the <b>solution</b>."],
 (16, "cartoon"): ["Children love <b>cartoons</b>.", "The newspaper printed a funny <b>cartoon</b>."],
 (16, "cross"): ["Look both ways before you <b>cross</b> the road.", "She wore a small <b>cross</b> on a chain."],
 (16, "tip"): ["I gave the waiter a <b>tip</b>.", "Here's a useful <b>tip</b> for cooking.", "The <b>tip</b> of the pencil broke."],
 (16, "web"): ["I found the answer on the <b>web</b>.", "A spider spun a <b>web</b> in the corner."],
 (16, "lock"): ["Don't forget to <b>lock</b> the door.", "The <b>lock</b> on the gate is broken."],
 (16, "wave"): ["A big <b>wave</b> hit the boat.", "She <b>waved</b> goodbye."],
 (16, "mine"): ["That book is <b>mine</b>.", "He works in a coal <b>mine</b>."],
 (16, "argument"): ["They had an <b>argument</b> about money.", "She made a strong <b>argument</b> for the plan."],
 (16, "suit"): ["He wore a black <b>suit</b> to the wedding.", "That colour <b>suits</b> you well."],
 (16, "act"): ["We must <b>act</b> quickly.", "A kind <b>act</b> can change someone's day."],
 (16, "sale"): ["The <b>sale</b> of the house took months.", "The shoes are on <b>sale</b> this week."],

 # ——— Grup 17 (A2) ———
 (17, "stage"): ["The singer walked onto the <b>stage</b>.", "The project is at an early <b>stage</b>."],
 (17, "professional"): ["She is a <b>professional</b> photographer.", "He gave me some <b>professional</b> advice."],
 (17, "running"): ["<b>Running</b> is good exercise.", "The <b>running</b> of the hotel is hard work."],
 (17, "support"): ["My family always <b>supports</b> me.", "Thank you for your <b>support</b>."],
 (17, "cause"): ["Heavy rain can <b>cause</b> floods.", "The <b>cause</b> of the fire is unknown."],
 (17, "certain"): ["I'm <b>certain</b> I locked the door.", "<b>Certain</b> people don't like change."],
 (17, "screen"): ["Don't sit too close to the <b>screen</b>.", "A <b>screen</b> divided the room."],
 (17, "pass"): ["Did you <b>pass</b> your exam?", "Please <b>pass</b> me the salt."],
 (17, "matter"): ["That's a serious <b>matter</b>.", "Your happiness is all that <b>matters</b>."],
 (17, "touch"): ["Please don't <b>touch</b> the paintings.", "We keep in <b>touch</b> by email."],
 (17, "neither"): ["<b>Neither</b> answer is correct.", "He can't swim, and <b>neither</b> can I."],
 (17, "mark"): ["There is a dirty <b>mark</b> on your shirt.", "The teacher will <b>mark</b> our tests."],
 (17, "since"): ["I have lived here <b>since</b> 2010.", "<b>Since</b> you're tired, let's rest."],
 (17, "light"): ["The bag is very <b>light</b>.", "Please turn on the <b>light</b>."],
 (17, "season"): ["Autumn is my favourite <b>season</b>.", "The football <b>season</b> starts in August."],
 (17, "store"): ["The <b>store</b> sells clothes and shoes.", "We <b>store</b> potatoes in the cellar."],
 (17, "shake"): ["<b>Shake</b> the bottle before you open it.", "His hands <b>shake</b> when he's cold."],
 (17, "memory"): ["She has a good <b>memory</b> for names.", "I have happy <b>memories</b> of that summer."],
 (17, "either"): ["You can take <b>either</b> road.", "I don't like it, and she doesn't <b>either</b>."],
 (17, "jam"): ["I like strawberry <b>jam</b> on toast.", "We were stuck in a traffic <b>jam</b>."],
 (17, "reception"): ["Ask for your key at <b>reception</b>.", "They held a <b>reception</b> after the wedding."],
 (17, "double"): ["I'd like a <b>double</b> room, please.", "Prices have grown to <b>double</b> what they were."],
 (17, "guide"): ["The <b>guide</b> showed us around the museum.", "She will <b>guide</b> you through the steps."],

 # ——— Grup 18 (B1) ———
 (18, "vote"): ["She got the most <b>votes</b>.", "She is old enough to <b>vote</b>."],
 (18, "agent"): ["A travel <b>agent</b> booked our trip.", "He works as a secret <b>agent</b>."],
 (18, "sink"): ["The heavy stone will <b>sink</b>.", "Wash your hands in the <b>sink</b>."],
 (18, "set"): ["<b>Set</b> the alarm for seven.", "She has a full <b>set</b> of tools."],
 (18, "range"): ["The shop sells a wide <b>range</b> of shoes.", "The gun has a <b>range</b> of two kilometres.", "Prices are in the <b>range</b> of ten to twenty liras."],
 (18, "shift"): ["She works the night <b>shift</b>.", "<b>Shift</b> the box to the left."],
 (18, "lie (tell a lie)"): ["Don't <b>lie</b> to me.", "That was a terrible <b>lie</b>."],
 (18, "exchange"): ["Can I <b>exchange</b> this shirt for a bigger size?", "He works at the stock <b>exchange</b>."],
 (18, "contact"): ["Please <b>contact</b> me by email.", "The two wires are in <b>contact</b>."],
 (18, "issue"): ["Money is a serious <b>issue</b>.", "I bought the latest <b>issue</b> of the magazine."],
 (18, "flow"): ["The river <b>flows</b> to the sea.", "There was a steady <b>flow</b> of visitors."],
 (18, "yard"): ["The children play in the <b>yard</b>.", "The pool is fifty <b>yards</b> long."],
 (18, "reservation"): ["I made a <b>reservation</b> at the restaurant.", "She had some <b>reservations</b> about the plan."],
 (18, "supply"): ["The town has a good water <b>supply</b>.", "They <b>supply</b> food to the school."],
 (18, "alcoholic"): ["They don't serve <b>alcoholic</b> drinks here.", "He is a recovering <b>alcoholic</b>."],
 (18, "update"): ["Please <b>update</b> the app.", "Here is an <b>update</b> on the news."],
 (18, "treat"): ["They <b>treat</b> their staff well.", "Doctors <b>treat</b> sick people.", "Let me <b>treat</b> you to dinner."],

 # ——— Grup 19 (B1) ———
 (19, "living"): ["Are your grandparents still <b>living</b>?", "He earns a <b>living</b> by teaching."],
 (19, "appreciate"): ["I <b>appreciate</b> your help.", "She <b>appreciates</b> good music."],
 (19, "gather"): ["A crowd began to <b>gather</b> in the square.", "They <b>gather</b> wood for the fire."],
 (19, "due"): ["The train is <b>due</b> at noon.", "The rent is <b>due</b> on the first of the month."],
 (19, "content"): ["The <b>content</b> of the letter surprised me.", "She felt <b>content</b> with her simple life."],
 (19, "stick"): ["The dog fetched the <b>stick</b>.", "<b>Stick</b> the stamp on the letter.", "The door can <b>stick</b> in wet weather."],
 (19, "policy"): ["The company changed its <b>policy</b>.", "She bought an insurance <b>policy</b>."],
 (19, "guard"): ["A <b>guard</b> stood at the door.", "Dogs <b>guard</b> the house at night."],
 (19, "operation"): ["He had an <b>operation</b> on his knee.", "The rescue <b>operation</b> lasted all night."],
 (19, "sight"): ["She lost her <b>sight</b> in one eye.", "The mountains were a beautiful <b>sight</b>."],
 (19, "shoot"): ["Don't <b>shoot</b> the birds.", "They will <b>shoot</b> the film in Italy."],
 (19, "producer"): ["The film <b>producer</b> found the money for the movie.", "Brazil is a big <b>producer</b> of coffee."],
 (19, "reflect"): ["The mirror <b>reflects</b> the light.", "He paused to <b>reflect</b> on his life."],
 (19, "judge"): ["The <b>judge</b> listened to both sides.", "Don't <b>judge</b> people by their clothes."],
 (19, "union"): ["The <b>union</b> of the two states made one country.", "He joined the workers' <b>union</b>."],

 # ——— Grup 20 (B1) ———
 (20, "claim"): ["He <b>claims</b> that he saw a ghost.", "She made a <b>claim</b> for the money."],
 (20, "mild"): ["The winter was quite <b>mild</b> this year.", "This cheese has a <b>mild</b> taste."],
 (20, "base"): ["The lamp has a heavy <b>base</b>.", "The soldiers returned to their <b>base</b>."],
 (20, "rough"): ["The road was <b>rough</b> and bumpy.", "His manners are a bit <b>rough</b>.", "She had a <b>rough</b> week at work."],
 (20, "aged"): ["A man <b>aged</b> forty applied for the job.", "They care for their <b>aged</b> parents."],
 (20, "mine"): ["That coat is <b>mine</b>.", "The workers went down into the coal <b>mine</b>."],
 (20, "measure"): ["<b>Measure</b> the room before buying a carpet.", "The government took strong <b>measures</b>."],
 (20, "production"): ["Car <b>production</b> increased this year.", "The <b>production</b> of the play took months."],
 (20, "promote"): ["They will <b>promote</b> her to manager.", "They <b>promote</b> the new product on TV."],
 (20, "episode"): ["I watched the last <b>episode</b> yesterday.", "It was a sad <b>episode</b> in her life."],
 (20, "weigh"): ["Please <b>weigh</b> the apples.", "The bag <b>weighs</b> two kilos."],
 (20, "quotation"): ["She began her speech with a famous <b>quotation</b>.", "The builder gave us a <b>quotation</b> for the work."],
 (20, "odd"): ["It's <b>odd</b> that he didn't call.", "One, three and five are <b>odd</b> numbers."],
 (20, "entry"): ["<b>Entry</b> to the museum is free.", "Each <b>entry</b> in the diary has a date."],
 (20, "plot"): ["The <b>plot</b> of the film was very exciting.", "They made a <b>plot</b> to steal the gold."],
 (20, "upset"): ["She was <b>upset</b> about the bad news.", "The sad film <b>upset</b> the children."],
 (20, "host"): ["Our <b>host</b> welcomed us warmly.", "He is the <b>host</b> of a game show."],
 (20, "current"): ["What is the <b>current</b> price of gold?", "The <b>current</b> pulled the swimmer out to sea."],
 (20, "release"): ["They will <b>release</b> the prisoner.", "The band will <b>release</b> a new album."],
 (20, "string"): ["Tie the box with <b>string</b>.", "She wore a <b>string</b> of pearls."],
 (20, "mad"): ["You must be <b>mad</b> to swim in winter.", "He was <b>mad</b> at me for being late."],
 (20, "powder"): ["Add the milk <b>powder</b> to the water.", "She put some <b>powder</b> on her face."],

 # ——— Grup 21 (B1) ———
 (21, "spirit"): ["Some people believe in <b>spirits</b>.", "The team played with great <b>spirit</b>."],
 (21, "application"): ["She sent an <b>application</b> for the job.", "This <b>application</b> helps you learn words."],
 (21, "native"): ["The <b>native</b> people know the forest well.", "English is her <b>native</b> language."],
 (21, "block"): ["A fallen tree <b>blocked</b> the road.", "The tower is made of concrete <b>blocks</b>."],
 (21, "branch"): ["A bird sat on a <b>branch</b>.", "The bank has a <b>branch</b> in every town."],
 (21, "sharp"): ["Be careful; the knife is very <b>sharp</b>.", "The car made a <b>sharp</b> turn."],
 (21, "pot"): ["Boil the water in a <b>pot</b>.", "She planted flowers in a <b>pot</b>."],
 (21, "tight"): ["These shoes are too <b>tight</b>.", "Keep a <b>tight</b> hold on the rope."],
 (21, "pipe"): ["Water flows through this <b>pipe</b>.", "He smoked a <b>pipe</b> by the fire."],
 (21, "force"): ["The wind hit the boat with great <b>force</b>.", "You can't <b>force</b> me to go."],
 (21, "pale"): ["She looked <b>pale</b> and tired.", "The walls were a <b>pale</b> blue."],

 # ——— Grup 22 (B1) ———
 (22, "press"): ["<b>Press</b> the button to start.", "The story was in all the <b>press</b>."],
 (22, "rent"): ["The monthly <b>rent</b> is high.", "We <b>rent</b> a flat in the city."],
 (22, "murder"): ["The police are investigating a <b>murder</b>.", "He was accused of trying to <b>murder</b> his wife."],
 (22, "stick"): ["The dog chewed the <b>stick</b>.", "<b>Stick</b> the photo in the album.", "The window can <b>stick</b> in summer."],
 (22, "switch"): ["Where is the light <b>switch</b>?", "<b>Switch</b> off the light before you leave."],
 (22, "race"): ["She came first in the <b>race</b>.", "The club is open to people of every <b>race</b>."],
 (22, "import"): ["The country's main <b>import</b> is oil.", "They <b>import</b> cars from Germany."],
 (22, "bother"): ["Don't <b>bother</b> him while he's working.", "Don't <b>bother</b> to cook; we'll eat out."],
 (22, "commit"): ["He would never <b>commit</b> a crime.", "She is ready to <b>commit</b> to the project."],
 (22, "solid"): ["Ice is water in a <b>solid</b> form.", "The house is built on <b>solid</b> rock."],
 (22, "live"): ["Fish can't <b>live</b> out of water.", "We watched the concert <b>live</b> on TV."],
 (22, "duty"): ["It is a nurse's <b>duty</b> to care for patients.", "You must pay <b>duty</b> on these goods."],
 (22, "hire"): ["We can <b>hire</b> a car at the airport.", "The company will <b>hire</b> ten new workers."],
 (22, "standard"): ["The hotel offers a high <b>standard</b> of service.", "This is the <b>standard</b> size for a door."],

 # ——— Grup 23 (B1) ———
 (23, "tube"): ["The paint comes in a <b>tube</b>.", "Water ran through a rubber <b>tube</b>."],
 (23, "treatment"): ["The new <b>treatment</b> cured the disease.", "The prisoners received harsh <b>treatment</b>."],
 (23, "addition"): ["In <b>addition</b> to tea, they served cakes.", "Children learn <b>addition</b> and subtraction."],
 (23, "charge"): ["There is no <b>charge</b> for children.", "The phone is on <b>charge</b>.", "He faces a <b>charge</b> of theft."],
 (23, "whether"): ["I don't know <b>whether</b> to stay or go.", "<b>Whether</b> you like it or not, we must go."],
 (23, "waste"): ["Don't <b>waste</b> water.", "The factory dumps its <b>waste</b> in the river."],
 (23, "script"): ["The actor learned his <b>script</b>.", "The old letter was in beautiful <b>script</b>."],
 (23, "grain"): ["Bread is made from <b>grain</b>.", "There wasn't a <b>grain</b> of sand in her shoe."],
 (23, "pressure"): ["Check the air <b>pressure</b> in the tyres.", "He is under a lot of <b>pressure</b> at work."],
 (23, "highlight"): ["The teacher <b>highlighted</b> the key words.", "The zoo was the <b>highlight</b> of the trip."],
 (23, "admit"): ["He <b>admitted</b> his mistake.", "This ticket <b>admits</b> two people."],
 (23, "revise"): ["We had to <b>revise</b> our plans.", "I need to <b>revise</b> for the test."],
 (23, "official"): ["This is the <b>official</b> website.", "A government <b>official</b> made a speech."],
 (23, "challenge"): ["Learning a language is a <b>challenge</b>.", "She <b>challenged</b> him to a race."],
 (23, "wonder"): ["I <b>wonder</b> what time it is.", "The children looked at the stars in <b>wonder</b>."],
 (23, "sex"): ["Please write your name and <b>sex</b> on the form.", "The film has scenes of violence and <b>sex</b>."],
 (23, "property"): ["The house is his personal <b>property</b>.", "This metal has a special <b>property</b>."],
 (23, "clause"): ["A sentence can have more than one <b>clause</b>.", "This <b>clause</b> explains the rules."],
 (23, "graduate"): ["She is a <b>graduate</b> of Oxford.", "He will <b>graduate</b> from university in June."],
 (23, "grade"): ["He got a good <b>grade</b> in maths.", "My son is in the fifth <b>grade</b>."],
 (23, "secondary"): ["The cost is of <b>secondary</b> importance.", "He goes to a <b>secondary</b> school."],
 (23, "engaged"): ["They got <b>engaged</b> last month.", "The line is <b>engaged</b>; try again later."],
 (23, "smart"): ["That's a <b>smart</b> idea.", "He looked <b>smart</b> in his new suit."],
 (23, "though"): ["<b>Though</b> it was late, they kept working.", "It's hard work. I enjoy it, <b>though</b>."],
 (23, "export"): ["Coffee is the country's main <b>export</b>.", "They <b>export</b> fruit to Europe."],
 (23, "setting"): ["The <b>setting</b> of the film is a small village.", "Turn the oven to a low <b>setting</b>."],

 # ——— Grup 24 (B1) ———
 (24, "primary"): ["Health is of <b>primary</b> importance.", "She teaches at a <b>primary</b> school."],
 (24, "qualification"): ["She has the right <b>qualifications</b> for the job.", "Patience is an important <b>qualification</b> for a teacher."],
 (24, "iron"): ["The gate is made of <b>iron</b>.", "Use a hot <b>iron</b> on the shirt."],
 (24, "used"): ["He bought a <b>used</b> car.", "I'm not <b>used</b> to getting up early."],
 (24, "bend"): ["<b>Bend</b> your knees when you lift the box.", "The car slowed at the <b>bend</b> in the road."],
 (24, "performance"): ["The <b>performance</b> starts at eight.", "The team's <b>performance</b> was excellent."],
 (24, "nail"): ["Hammer the <b>nail</b> into the wood.", "She painted her <b>nails</b> red."],
 (24, "roll"): ["The ball <b>rolled</b> under the table.", "She bought a <b>roll</b> of paper."],
 (24, "qualify"): ["Our team <b>qualified</b> for the final.", "She <b>qualified</b> as a doctor last year."],
 (24, "ban"): ["The school will <b>ban</b> mobile phones.", "There is a <b>ban</b> on smoking here."],
 (24, "fancy"): ["She wore a <b>fancy</b> dress to the party.", "Do you <b>fancy</b> a cup of tea?"],
 (24, "spot"): ["There is a <b>spot</b> of ink on the page.", "This is a lovely <b>spot</b> for a picnic.", "Can you <b>spot</b> the difference?"],
 (24, "spread"): ["<b>Spread</b> the butter on the bread.", "The fire <b>spread</b> quickly."],
 (24, "commercial"): ["The area has many <b>commercial</b> buildings.", "A TV <b>commercial</b> interrupted the film."],
 (24, "medium"): ["I'd like a <b>medium</b> coffee, please.", "Television is a powerful <b>medium</b>."],
 (24, "aim"): ["Our <b>aim</b> is to finish by Friday.", "He <b>aimed</b> the arrow at the target."],
 (24, "simply"): ["<b>Simply</b> add water and stir.", "I did it <b>simply</b> because I wanted to."],
 (24, "intelligence"): ["Dolphins have great <b>intelligence</b>.", "The spy gathered secret <b>intelligence</b>."],
 (24, "journal"): ["She published her results in a science <b>journal</b>.", "She writes in her <b>journal</b> every night."],
 (24, "court"): ["The case went to <b>court</b>.", "They played on the tennis <b>court</b>."],
 (24, "attraction"): ["The castle is a popular tourist <b>attraction</b>.", "There is a strong <b>attraction</b> between the two."],
 (24, "relative"): ["Many <b>relatives</b> came to the wedding.", "They live in <b>relative</b> comfort."],
 (24, "remote"): ["They live in a <b>remote</b> village.", "Change the channel with the <b>remote</b> control."],
 (24, "chest"): ["He felt a pain in his <b>chest</b>.", "She keeps old letters in a wooden <b>chest</b>."],
}
